### ISSUE TITLE
Command to print out all targets

### ISSUE THREAD

**Issue by lukehoersten** [ndmitchell/shake#107]
Most modern task managers have a way to print out all valid targets. It would be nice to have the same in Shake.

**Comment by ndmitchell** [comment]
@3noch in #222 asked for: Phony targets are quite often the custom interface into a build system. It would be great if shake could report them to the user automatically so we don't have to write phony "help" targets as well. Adding helpful descriptions could be another bonus feature somewhere along the line.

The complication of `shakeArgsWith` remains. I don't yet have a good strategy for that. Maybe `--help` should call `shakeArgsWith` using `[]` as the arguments, and then have `phony` write to `Rules` and gather them from there - I wonder if that works in general? Once I have access to `Rules` then I can just add a `describe` function that associates help text with a flag, and make `phony` call it by default with no help text.

**Comment by LukeHoersten** [comment]
Just to be clear I'd like it to print the pattern rules too, not just phony rules. I'm not sure the best way to get access to all those strings though.

**Comment by 3noch** [comment]
Perhaps you could add a help builder that can simply be wrapped by a phony? That way shake would just be exposing some internal structure from within the monad.

Kind of like this:
```haskell
shake $ do
   ... --build rules
   phony "help" $ do
       helpText <- generateTargetHelp
       print helpText
```

**Comment by ndmitchell** [comment]
Suggestion that this somehow provide auto-complete functionality in some shell, if possible.

**Comment by minad** [comment]
What is the status on this? I would like to have it especially for phony targets.

**Comment by ndmitchell** [comment]
Done in #625 - see `--help` and `getTargets`.
