### ISSUE TITLE
Add simplified syntax

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#142]
Add a basic syntax for interpreting YAML (probably) as Shake rules. Could easily store rules in that form, have a `loadRulesFromYaml` function, and allow them to be run by default. If we make it more powerful than Ninja (to translatable) then should be easy.

**Comment by ndmitchell** [comment]
My inclination is that for the build systems where Shake is ideally suited, you tend to end up writing an interpreter anyway, and then you need the full power of Haskell. A "simple end" Shake might be valuable for small projects, but it doubles the number of syntaxes to document and halves the reusability of questions, so I'm not going to do it. If anyone wants to build such a lite-Shake language I'd be very keen to see it and happy to link to it.

**Comment by Mathnerd314** [comment]
You already wrote a Sake implementation, which is in fact a simplified YAML syntax:
http://neilmitchell.blogspot.com/2014/05/shake-as-dependency-library.html
Perhaps running the Sake test suite could be part of Shake's test suite?

**Comment by ndmitchell** [comment]
Sake is a simplified YAML syntax, but it also doesn't give access to any of the powerful Shake features, so I don't really want to push people down that route. I also don't remember much of Sake, and don't really want to support that code (there's a reason it's a blog post and not part of Shake by default).

I suspect the Sake test suite would be great to test the Sake implementation above, so if anyone ever did decide to turn it into a proper project, that would be very useful. In contrast, there are no `.ninja` tests in the Ninja repo, which makes the Ninja binding much harder (there are tests, but they poke the C++ internals, which seems a weaker form of test). However, as it stands, I'm not sure there's much point in integrated the Sake tests.
