### ISSUE TITLE
Be more verbose when several rules match

### ISSUE THREAD

**Issue by somenxavier** [ndmitchell/shake#143]
Hi,

I received the following error

```
[xan@rulot còpia de context4]$ ./shaking 
# xsltproc (for ./tmp/tasques-previ.context)
Error when running Shake build system:
* tasques.pdf
* tasques.pdf tasques.pgf tasques.tuc tasques.log
* ./tmp/tasques-permenoritzades.context
* ./tmp/tasca-cos-*.context
* ./tmp/tasca-cos-*.md
* ./tmp/tasca-antiga-*.xml
Build system error - key matches multiple rules:
  Key type:       FileQ
  Key value:      ./tmp/tasca-antiga-*.xml
  Rules matched:  2
Modify your rules/defaultRules so only one can produce the above key
```

Can you modify `shake` for being more verbose?
- include the printing of lines of the rules? What are the conflicting rules?
- what is `FileQ`?
- I only know that it fails with tasca-antiga-\* ... but with hundreds of lines it could be a little bit than nothing :smile:

**Comment by ndmitchell** [comment]
Thinking about it afresh, I should probably have some "extra" information to associate with each rule that is printed on clashes. For `%>` that information can be the pattern. In GHC 8, which has `Location =>`, I can also include the line number, and that will work even for `?>`.

**Comment by ndmitchell** [comment]
See also #107, which requires much the same mechanism.

**Comment by nkaretnikov** [comment]
I just got hit by this, too. It's quite annoying to look through your rules in order to find the overlapping ones, I'd prefer if Shake printed them for me. If  anything could be done about this, that would be a very welcome change!

**Comment by ndmitchell** [comment]
I'm actively working on it! It involves a massive rewrite of Shake, some patches of which have already landed, with more to come before it's ready (I don't advise trying HEAD right now).

**Comment by nkaretnikov** [comment]
@ndmitchell Yay! Thanks.

**Comment by ndmitchell** [comment]
It now says:

```
Error when running Shake build system:
* overlap.txx
Build system error - key matches multiple rules:
  Key type:       FileQ
  Key value:      overlap.txx
  Rules matched:  4
  Rule 1:         "overlap.t*" %> at src/Test/Errors.hs:82:5-56:
  Rule 2:         "overlap.*" %> at src/Test/Errors.hs:83:5-54:
  Rule 3:         ["*.txx","*.tox"] &%> at src/Test/Errors.hs:84:5-52:
  Rule 4:         "*p.txx" %> at src/Test/Errors.hs:85:5-45:
Modify your rules so only one can produce the above key
```

Which I'm happy with.

**Comment by andrewufrank** [comment]
thank you very much  - this is very helpful output! (I had only to move up to 8.6. to get it in LTS - the regular delays from the developers to the users)
