### ISSUE TITLE
When are intermediate directories created? (and why?)

### ISSUE THREAD

**Issue by dbp** [ndmitchell/shake#170]
I have a set of rules like:

```
foo ~> do need ["bar/bin/bar-exe"]
          cmd "bar/bin/bar-exe"
"bar/bin/bar-exe" *> \_ -> do need ["bar"]
                              cmd (Cwd "bar") "./build.sh"
"bar" *> \_ -> do exists <- doesDirectoryExist "bar"
                  when (not exists) $ cmd Shell "git clone http://url-to-bar"
```

There are two issues I have with this:

1. The test for the directory existing seems wrong, but when I wrote a version of this (ignoring issue 2; that case didn't exist yet) without it, the rule was run even when the directory existed. My hypothesis is that the mtime for the cloned directory post-dated when the run started (as it was created during the run), which meant that the next time the rule was run, it was triggered again. Perhaps there is a way around that?

2. More to the point of the issue, this code doesn't actually work, because it seems that when the rule for "bar/bin/bar-exe" starts, the directory path "bar/bin" is created, which means that the rule for "bar" (which is triggered due to the need) thinks that there is nothing to do, and of course this means that things don't work.

The only way around it I've figured out so far is to push the dependency on "bar" up to "foo", but that seems really strange (as I'm manually unrolling the depedencies one step). The end result is this (which works):

```
foo ~> do need ["bar"]
          need ["bar/bin/bar-exe"]
          cmd "bar/bin/bar-exe"
"bar/bin/bar-exe" *> \_ -> do need ["bar"]
                              cmd (Cwd "bar") "./build.sh"
"bar" *> \_ -> do exists <- doesDirectoryExist "bar"
                  when (not exists) $ cmd Shell "git clone http://url-to-bar"
```

So I'm wondering why the path to the target is created, and if there's a way to not have it happen automatically. Or if I'm just approaching this completely wrong, in which case hopefully you can point me towards the right direction (I now have about 2 days experience with Shake, so am aware I could be totally off base).

**Comment by ndmitchell** [comment]
Documented as an FAQ, and also made a note in `need` as part of #159.
