### ISSUE TITLE
Idea: "task" rules that are half-way between file rules and phony rules

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#191]
File-based rules run when dependencies change or when the file is missing. Phony rules don't produce a file and always run. I would like to have something in the middle: a rule that does not produce a file, but only runs when its dependencies change. Of course, this behavior can be achieved with temp-files. But there is overhead to get that working properly, especially if you want these "task" based rules to match FilePatterns just like file-based rules do.

This might be a bad idea or it might not fit with the goals of the project. That's ok. I just wanted to propose it in case it was useful. I've achieved this with temporary files and it's working well.

**Comment by ezyang** [comment]
Suppose rule A depends on task B. If you don't care about rerunning rule A if task B ran this round, you can implement tasks today in Shake.

```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE MultiParamTypeClasses #-}
import Development.Shake
import Development.Shake.Rule
import Development.Shake.Classes

newtype Task = Task String
    deriving (Show, Typeable, Eq, Hashable, Binary, NFData)

instance Rule Task () where
    storedValue _ _ = return (Just ())
    equalValue _ _ _ _ = EqualCheap

main :: IO ()
main = shakeArgs shakeOptions $ do
    action $ (apply1 (Task "foo") :: Action ())
    rule $ \(Task k) -> Just $ do
        need [k]
        putNormal k
```

Example:

```
ezyang@sabre:~$ runghc Test.hs 
Build completed in 0:01m
ezyang@sabre:~$ touch foo
ezyang@sabre:~$ runghc Test.hs 
foo
Build completed in 0:01m
```

One downside of this approach is that Shake's unchanging rebuilds will assume that any rule which depends on the task does NOT need to be rebuilt.

If you want to rerun any of the rules that depended on your task when the task reruns, then you can't use a trivial sentinel in your rule: you need something like a timestamp (a monotonically increasing counter), and you need to save it somewhere. One way to do this is to associate tasks with files and look at the timestamp in the file (rm to force the task to rerun): that's the tempfile approach suggested above.

If you want to AVOID files, there is a very minor extension to `storedValue` which would allow you to this. Just extend the return type to also allow returning `NeverRecompile` (by analogy, `Just` is `RecompileIfNeq` and `Nothing` is `AlwaysRecompile`). Shake should treat a `NeverRecompile` return value by `storedValue` by simply looking up what the value is in the database and using that. (Or if it's missing, as it will be the first time you run the task, then you have to compile.) The point is that Shake is already storing the timestamp in its own database, so if there's a way to query what Shake stored, then you can eliminate the extra store.

**Comment by ezyang** [comment]
Referenced PR implements my suggested extension.

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/shake/pull/389#issuecomment-172022265 for notes on how to combine oracles and Rule rules, thus fixing this whole issue (nothing in between, since they are the same).

**Comment by ndmitchell** [comment]
There is now addOracleCache which does this task rule. I think that nails exactly what you were after, but let me know if not.
