### ISSUE TITLE
Allow a single key type to map to multiple value types.

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#192]
At the moment Phony rules, FileHash rules and ModTime rules all get mushed into one, because you want all of them to match on `String` keys. If some variant of `apply_` was introduced, which didn't care about the result type (as most of them don't) you could use separate rules for each set of rules but make them all depend on the same key type.

**Comment by ndmitchell** [comment]
Note that also rules currently do two modtime checks per file. With apply_ I could make that one and shrink the database a bit.

**Comment by ezyang** [comment]
If you don't need an open universe on strings, you could use a GADT to encode the return type. This has the added benefit that you can still support apply with a return type (pattern matching on the GADT to determine the return type). This is especially true since you don't want to allow overlaps for rules which have different outputs but the same key.

For that matter, if you apply for a specific value, and there exists a rule for that key, but a different value, what are you supposed to do?

**Comment by ndmitchell** [comment]
I definitely want an open universe, since then all the Shake rule types can be entirely separate from each other, without overlap.

I don't think there is any problem with different rules returning different keys, or overlaps. If given a particular string there are two matches, then that's an error, just like now. Overlaps of different types are not special.

> For that matter, if you apply for a specific value, and there exists a rule for that key, but a different value, what are you supposed to do?

Not totally sure what that is asking. When you call `apply` the first time it will find the associated action from `rule` and run it, producing an output type. If you do it again, it won't be looking at the rule/action, it will just see a key/value pair in the database, with types that must be unique (given the key type and the value type), and then check it. I guess the thing that stops any problems is that each entry in the database is indexed by key, key type, and value type. (Or, if it's not, it will have to be.)

**Comment by ezyang** [comment]
Yes, you'll have to index by key type and value type. If you only know about the monomorphic interface, that's kind of surprising, but OK!

**Comment by ndmitchell** [comment]
What do you mean by the monomorphic interface - via `need`? I don't think such users are even aware that the underlying rule returns a value.

**Comment by ezyang** [comment]
Yeah. (Well, it's only confusing if you decide you need to define some sort of rules on not filenames, and then you discover that it's indexed by key type and value type.)

**Comment by ezyang** [comment]
I was rereading this ticket and I am now confused by https://github.com/ndmitchell/shake/issues/192#issuecomment-88927977

How does multiple output values help with the `&%>` problem? As far as I can tell, you still need a rule key that represents the set of files your pattern is matching over.

**Comment by ndmitchell** [comment]
Hmm, maybe it doesn't. It does stop both the File and Files both storing/computing/checking the timestamp twice, but there would still be two rules in the chain.

**Comment by ndmitchell** [comment]
Given the move to `RuleResult` which seems to have been a very good idea this is no longer possible, and thus was probably a bad idea anyway.
