### ISSUE TITLE
directions to run demo are incomplete

### ISSUE THREAD

**Issue by goertzenator** [ndmitchell/shake#201]
The manual at https://github.com/ndmitchell/shake/blob/master/docs/Manual.md#readme directs the user type `shake --demo` to run the demo.  On a Kubuntu system with a freshly installed haskell-platform and shake, this does not work because shake is not in the path.  My session is below.

```
goertzen@ubuntu64 ~
$ shake --demo
The program 'shake' is currently not installed. You can install it by typing:
sudo apt-get install shake

goertzen@ubuntu64 ~
$ /home/goertzen/.cabal/bin/shake --demo
% Welcome to the Shake v0.14.2 demo mode!
...
```

**Comment by ndmitchell** [comment]
Assuming this is an issue with the Ubuntu Software Center Haskell pieces, but let me know if you find anything Shake related.
