### ISSUE TITLE
Database generated as shakeFiles.directory if shakeFiles is missing slash

### ISSUE THREAD

**Issue by changlinli** [ndmitchell/shake#203]
I'm not sure if this is desired behavior, but if I run the tutorial code in the manual and change the string passed to shakeFiles to a string without a separator, then running Shake will generate an extra `.database` file whose filepath is simply `.database` appended to the shakeFiles string rather than being a file in the shakeFiles directory.

In other words if I do 

```haskell
-- Note that it's "_build" not "_build/"
main = shakeArgs shakeOptions{shakeFiles="_build"} $ do ...
```

instead of 

```haskell
-- Now it's "_build/"
main = shakeArgs shakeOptions{shakeFiles="_build/"} $ do ...
```

I get an extra `_build.database` file which doesn't get cleaned up by the phony `clean` command since it's not in the `_build` directory. The particular line that does this seems to be [here](https://github.com/ndmitchell/shake/blob/1cfbb510ebb344130493a7cc842ef0ac600b768a/src/Development/Shake/Storage.hs#L59 "Line in Shake's Storage.hs file") where a `<.>` is used instead of a `</>`. 

Like I said not sure if desired behavior or not, just slighty inconsistent if I want to bind `_build` to a variable and let `</>` take care of adding separators as needed, especially as later on in the tutorial code we have

```haskell
let os = ["_build" </> c -<.> "o" | c <- cs]
```

**Comment by ndmitchell** [comment]
Done, as described.

**Comment by changlinli** [comment]
Awesome, thanks!
