### ISSUE TITLE
Depending on oracles in parallel

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#208]
When using `need`, the nice thing is that I can give it a list of things, that can be then built in parallel.

Does that work with oracles as well? 

For example, let's say I make some oracle

```haskell
type URL = String
newtype DownloadWebsite = DownloadWebsite URL deriving (Show,Typeable,Eq,Hashable,Binary,NFData)
rules = do
    downloadWebsite <- addOracle $ \(DownloadWebsite url) -> ... return htmlBody

    phony "downloadAll" $ do
        bodies <- mapM downloadWebsite [DownloadWebsite "google.com", DownloadWebsite "github.com"]
        ...
```

Will these independent downloads be done in parallel, like I could achieve with a `need`?

**Comment by ndmitchell** [comment]
With `addOracle`/`askOracle`, no, those are item-at-a-time single-threaded requests. However, under the hood both `need` and `askOracle` map down to `apply`, which is parallel (and can even do different types in one go). I could easily add `askOracles`, but:

* For something like downloading websites, I'd have thought downloading into a file was better, so you can consult the downloaded file if you need to do any debugging. Generally, if an oracle is expensive to compute, I'd probably put it in a file.
* Alternatively, I could have a more general `parallel` combinator that let you do things in parallel, which could include both `need` and `askOracle`. Something like `parallel :: [Action a] -> Action [a]`. That gives you maximum flexibility to combine different oracles etc in the future.

**Comment by nh2** [comment]
I don't have a good suggestion here yet. I'm using Shake more and more though, so I might have one in the future.

**Comment by ndmitchell** [comment]
Other work is starting to suggest the problem here is that oracles are a hack because defining rules directly is too difficult and too much boilerplate. If you had very easy rules, then you wouldn't ever have oracles, and the parallel stuff would come for free. I'm gradually figuring out what the design space looks like over there.

**Comment by ndmitchell** [comment]
Done as part of #269, which provides `parallel`.
