### ISSUE TITLE
No way to have a command run with a terminal

### ISSUE THREAD

**Issue by deepfire** [ndmitchell/shake#212]
This effectively prevents colorized output from recent gcc / clang from being available:
```
    phony "info" $ do
      cmd "ls" "--color=auto"
```
Additionally, it effectively prevents one from launching a useful sub-shell for the user -- a shell is run, but it has absolutely no terminal handling.

Apparently this requires jumping through the PTY hoops, which Shake doesn't do yet.

**Comment by ndmitchell** [comment]
Thanks for the report. You can certainly use other system command calls from Shake, for example:

    System.Cmd.system "ls --color=auto"

Do any Haskell functions get this right? What PTY hoops are required? Under the hood, Shake uses System.Process and the process library - can you configure that to use PTY? Or does it need upgrading to do the PTY hoops? (I'm a Windows user primarily, so not really sure about PTY details)

**Comment by deepfire** [comment]
Thank you!

`System.Cmd.system "bash"` works just fine!

**Comment by deepfire** [comment]
As to the PTY details, I'm not really sure, never touched that particular area.

For the record, neither Shelly, nor Turtle get this right -- I have submitted bug reports to them as well..

**Comment by ndmitchell** [comment]
If you call:

    cmd Shell "ls --color=auto"

Does that work? That shares some characteristics with `system`.

**Comment by deepfire** [comment]
No, it doesn't -- same plain, PTY-less stdio, apparently..

**Comment by ndmitchell** [comment]
OK, observing the code, my best guess is that if you capture the standard handles at all it will break. Shake by default captures stderr so it can use it in the exception message. If you turn off the exception message capturing it still doesn't work because Shake doesn't have an optimisation to inherit the handles in that case, it just captures stderr and throws it away. I was working on such an optimization last night for other reasons, but it sounds like with that I'll be apply to have a PTY flag which disables enough stuff for this feature to work.

**Comment by kirbyfan64** [comment]
FYI, you can use `--fcolor-diagnostics` for force colors in Clang, and maybe GCC. That's what I do.

**Comment by deepfire** [comment]
@kirbyfan64, for gcc I use `-fdiagnostics-color=always`.  But getting the colors sequences to be emitted isn't the problem.. The problem is to get a context, where those color sequences will get interpreted.

**Comment by ndmitchell** [comment]
With the HEAD version of Shake this might be possible. If you pass `WithStderr False` then it should just inherit all file descriptors, and my guess is that is what makes `system` work.

**Comment by deepfire** [comment]
I have tested it in 0.15 and I can confirm that:
```shell
    phony "lol" $ do
      cmd (WithStderr False) "bash"
```
works with a full terminal.

**Comment by ndmitchell** [comment]
Thanks for testing, I'll leave this ticket to update the docs to include the magic required.

**Comment by ndmitchell** [comment]
I've documented it with:

    By default the @stderr@ stream will be captured for use in error messages, and also echoed. To only echo
    pass @'WithStderr' 'False'@, which causes no streams to be captured by Shake, and certain programs (e.g. @gcc@)
    to detect they are running in a terminal.

Please let me know if that can be improved or is incorrect (I'm mostly guessing about what half these words mean).

**Comment by deepfire** [comment]
Neil, I have tested shake-0.15, and to my surprise, (WithStderr False) is no longer necessary -- colored output, as well as subshells work perfectly well with captured stderr.

I have no idea what's going on.

**Comment by ndmitchell** [comment]
I completely rewrote the internals of the `cmd` stuff in v0.15, so it's no great shock - I guess one of the things I did had that side effect.

**Comment by deepfire** [comment]
It's actually very pleasant, since it removes the need to choose between error logging and functioning of pty-based commands : -)

Thank you!
