### ISSUE TITLE
Add predicate phony rule

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#213]
Something like:

    phonys :: (String -> Maybe (Action ())) -> Rules ()

I think this will be easier after #192.

**Comment by deepfire** [comment]
I have to add that this is something of a usability stumbling block for Ruin, even if it's nothing fatal.

**Comment by ndmitchell** [comment]
I had hoped to do that after #192, but various release plans and other dependencies mean I'll probably release 0.15 in the next day or so with that done. Therefore, I've added your function quickly, and will aim to revamp it later on.

**Comment by ndmitchell** [comment]
I'm actually happy enough with phonys as it is, so I'll close this ticket. Expect a release in the next few hours.

**Comment by ndmitchell** [comment]
I just released it as 0.15 - more last minute things cropped up, but now the release is done!

**Comment by deepfire** [comment]
Congratulations on the new release!

Updating my local nixpkgs to the new extras & shake.. if everything goes well, I'll submit it to nixpkgs central..
