### ISSUE TITLE
Run Shakefile by default

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#219]
Suggestion from @LukeHoersten that "shake" as one of its default actions runs `.shake/shake.exe`, or calls `runhaskell` on `Shakefile.hs` or `Shakefile.lhs`.

**Comment by ndmitchell** [comment]
Done, as discussed.

**Comment by LukeHoersten** [comment]
Thanks Neil. You're a machine!

**Comment by ndmitchell** [comment]
No probs, it was a good idea. I've now added some tests so we can rely on it happily.
