### ISSUE TITLE
Provide shakeVersion convenience function that notices when the shake file changes?

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#220]
I often use a setup like this to make sure that `shakeVersion` is automatically bumped when I change Shake rules:

```haskell
-- | The name (no path) of this file we are in.
_THIS_FILE_NAME :: String
_THIS_FILE_NAME = takeFileName $(LitE . StringL . loc_filename <$> location)


-- | Get a checksum of THIS FILE to use as `shakeVersion`.
-- This will trigger a rebuild when the Shake rules defined in this file are changed.
-- This can be turned off for rule development by creating the
-- file DEVELOPING_SHAKE_DO_NOT_CHECK_IN.
getHashedShakeVersion :: IO String
getHashedShakeVersion = do
  skipChecksum <- IO.doesFileExist "DEVELOPING_SHAKE_DO_NOT_CHECK_IN"
  if skipChecksum
    then return "DEVELOPING_SHAKE_DO_NOT_CHECK_IN"
    else do checksum <- dropWhile (== '-') . show . hashWithSalt 0 <$> BS.readFile _THIS_FILE_NAME
            return $ "hash-" ++ checksum ++ "-" ++ _THIS_FILE_NAME


main :: IO ()
main = do

  hashedShakeVersion <- getHashedShakeVersion

  shakeArgs shakeOptions { shakeVersion = hashedShakeVersion } $ do
    ...
```

Making sure that Shake notices when its own file changes seems to be a common problem.

Do you think we could add something akin to `getHashedShakeVersion` to Shake, to provide the user with a "general way" to solve it?

It would have to be or provide a TemplateHaskell function, since `location` must be evaluated *in* the user's file to refer to the user's file.

**Comment by ndmitchell** [comment]
My only concern is that adding TemplateHaskell as a dependency is nasty, and (in past experiences) causes plenty of build errors for people for all kinds of unexpected reasons. If TH is essential that's not too bad, but for such a small use case its hard to justify. Adding it as a recommended pattern doesn't have the same downsides though.

**Comment by nh2** [comment]
I could also imagine that the equivalent of `getHashedShakeVersion` could take the name of the file as an argument, and that the docs of that function could recommend `takeFileName $(LitE . StringL . loc_filename <$> location)` as a sensible default for that argument; that way, all TH would stay in the user's file.

**Comment by ndmitchell** [comment]
Good plan!

**Comment by mboes** [comment]
In the common case, the filename should just be "Shakefile", right? Perhaps that could be a default.

Could the automatic version bump not best be inhibited via a command-line argument, rather than a magic file in the folder with a hardcoded name?

**Comment by ndmitchell** [comment]
I've never created a Shake file named `Shakefile`. I suggest it takes a list of file names, and then you can depend on multiple files if you like. I also suggest I add a flag `--ignore-version` which doesn't bother cleaning based on version when passed. Thoughts?

**Comment by ndmitchell** [comment]
All done. The docs read:

    -- | Get a checksum of a list of files, suitable for using as `shakeVersion`.
    --   This will trigger a rebuild when the Shake rules defined in any of the files are changed.
    --   For example:
    --
    -- @
    -- main = do
    --     ver <- 'getHashedShakeVersion' [\"Shakefile.hs\"]
    --     'shakeArgs' 'shakeOptions'{'shakeVersion' = ver} ...
    -- @
    --
    --   To automatically detect the name of the current file, turn on the @TemplateHaskell@
    --   extension and write @$(LitE . StringL . loc_filename \<$\> location)@.
    --
    --   This feature can be turned off during development by passing
    --   the flag @--no-rule-version@ or setting 'shakeVersionIgnore' to 'True'.

**Comment by nh2** [comment]
Nice, thanks a lot!

**Comment by mboes** [comment]
List of files looks great. I'm still new to Shake conventions!

**Comment by ndmitchell** [comment]
@mboes, I'm pretty new to Shake conventions as well, I've really only written tests and one huge Shake system, whereas others here have actually written loads of build systems.
