### ISSUE TITLE
Prioritise previously failed builds

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#223]
If a user builds something, and it fails, then next time I should probably prioritise that thing, on the assumption they changed it and it is the most likely thing to fail next, so faster feedback. May need to prioritise the children of a failing thing, if possible, so link errors which go away with compiler fixes work. If they aren't interested in faster feedback then staunch mode is the right thing to use anyway. Suggested on the [Ninja mailing list](https://groups.google.com/d/topic/ninja-build/yS1suH6F338/discussion) by @avikivity.

**Comment by ndmitchell** [comment]
#428 makes this pretty much impossible. You could still have a variant where you prioritise the oldest things, but sometimes that will be exactly right, and sometimes exactly wrong, so best not do anything.

**Comment by jacereda** [comment]
Would it be possible to store a list of targets failed in the last run in the database?
