### ISSUE TITLE
*.hs pattern matches *.hs#

### ISSUE THREAD

**Issue by LukeHoersten** [ndmitchell/shake#224]
`getDirectoryFiles "src" ["//*.hs"]` is matching files like `#Module.hs#`. I don't think that's right.

**Comment by LukeHoersten** [comment]
I was mistaken. It's matching `.#Module.hs` which is technically correct. I'm used to glob matching dot files separate from non-dot files.

**Comment by ndmitchell** [comment]
Yep, that's as expected. Do you think this is worth calling out in the docs?

**Comment by LukeHoersten** [comment]
I think things are OK as-is. As far as I can tell the docs never say glob patterns that was just my mistake. Sorry for the false alarm.

**Comment by ndmitchell** [comment]
Thanks for the report anyway, I'd much prefer 3 false alarms than to miss one real issue.
