### ISSUE TITLE
Support for providing Stdin via binary `Bytestring` content

### ISSUE THREAD

**Issue by hvr** [ndmitchell/shake#227]
While #27 added efficient support for handling large binary output, this leaves us with the `Stdin :: String -> CmdOption` constructor. Is there a reason this was left out?

**Comment by ndmitchell** [comment]
Don't think so - I wasn't sure anyone used stdin that much. Best to add it for completeness though.

**Comment by ndmitchell** [comment]
Add added `StdinBS` so you can pass lazy byte strings to Stdin.
