### ISSUE TITLE
Implement non-blocking cmd

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#228]
For running programs and waiting. Probably want to be able to capture the ProcessId so you can do other things later. Should return empty for all command output and success for all exit codes.

**Comment by LukeHoersten** [comment]
Perhaps what we really want for cmd is to start officially recommending `turtle` or `shelly` (or something of that nature). What I ended up doing was using the `async` library to spin up some threads and hold on to the `Async` handle to control cancellation etc. Still, getting the process ID would be good to ensure the underlying process is killed and not just the GHC green thread.

**Comment by ndmitchell** [comment]
Certainly recommending turtle or shelly is an option - if someone can make a good argument to me as why one would be "better" than the current `cmd` thing (where me not having to care about it is definitely one metric of "better") then I'd be very interested. My experience is that `cmd` in Shake actually fills the role nicely, without being too principled or too powerful. Both turtle and shelly excel at things like piped composition, but that's not typical in build systems.

**Comment by LukeHoersten** [comment]
Fair enough. It is nice not having to pull in a while scripting DSL just to run an external command.

**Comment by ndmitchell** [comment]
Added. If you capture the `ProcessHandle` coming out of a `cmd` it runs asyncronously.

**Comment by LukeHoersten** [comment]
Awesome thanks
