### ISSUE TITLE
Update semantics?

### ISSUE THREAD

**Issue by deepfire** [ndmitchell/shake#230]
Shake seems to fail to maintain the everything-is-up-to-date invariant, when the updating rule fails with error propagation.

Components:
 - a trivial error.c, which initially has no errors
 - a rule, which is supposed to build error.o, but fails to propagate an error condition

Scenario:
```shell
builder@andromedae:/$ touch error.cintercalate " "
builder@andromedae:/$ b
Build completed in 0:00m
builder@andromedae:/$ echo 'syntax error, please' > error.c
builder@andromedae:/$ b
error.c:1:1: error: unknown type name ‘syntax’
 syntax error, please
 ^
error.c:1:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ at end of input
Build completed in 0:00m
builder@andromedae:/$ b 
Build completed in 0:00m
```

I.e.:
 1. the failing run still succeeds
 2. the re-run fails to consider the rule, even if the file is not up-to-date, according to the ChangeModtime.

Or maybe it's really a question of semantics -- if the build command exits successfully, then Shake interprets that as a sign that the output is up to date, even if its timestamp isn't.

What is the useful behavior here?

```haskell
import Data.List (intercalate)
import Development.Shake
import Development.Shake.Command()
import Development.Shake.FilePath
import Development.Shake.Util
import System.Process (rawSystem)
import Text.Printf (printf)

cmd2 :: String -> [String] -> Action ()
cmd2 comm args = do
  putLoud $ printf "cmd> %s %s" comm $ intercalate " " args
  _ <- liftIO $ rawSystem comm args
  return ()

main :: IO ()
main = shakeArgsWith shakeOptions [] $ \_ _ -> return $ Just $ do

    want ["error.o"]
         
    "error.o" %> \out -> do
      let source   = out -<.> ".c"
      need ["error.c"]
      cmd2 "gcc" ["-o", out, "-c", source, "-fdiagnostics-color=always"]
```

**Comment by ndmitchell** [comment]
> Or maybe it's really a question of semantics -- if the build command exits successfully,
> then Shake interprets that as a sign that the output is up to date, even if its timestamp isn't.

If a rule executes to completion successfully then Shake assumes that the file it produces is now up-to-date. Crucially, unlike Make, this may _not_ involve the file changing its timestamp. In Make, that causes things to rebuild repeatedly. In Shake, that avoids further rebuilding. As an example, if you link `error.o` into `foo.exe` then if you recompile `error.c`, but `error.o` doesn't change (e.g. you change a comment), then the relinking will be skipped. So the solution here is to throw an exception if you fail to rebuild.

Note that if you just replace `cmd2` with `cmd` then it all works, as `cmd` throws an error on non-zero exit codes (unless you explicitly grab the exit code with `ExitCode _ <- cmd ...`.

**Comment by deepfire** [comment]
I have had such a guess, but grepping the documentation for 'time' failed to provide a definitive answer.

I admit I didn't look very hard.. : -)

**Comment by ndmitchell** [comment]
I added the docs to `%>` and `?>`:

> If the 'Action' completes successfully the file is considered up-to-date, even if the file has not changed.

Hopefully that clarifies things.

**Comment by deepfire** [comment]
Thank you!

Maybe it deserves a separate section, since it's a departure from the very well-known update semantics of make.  But maybe it's just an obscure corner and it doesn't matter.

No idea : -)

**Comment by ndmitchell** [comment]
My guess is it's an obscure corner case, and few are going to rely on it - the behaviour in Make if rules do that is deeply unpleasant (always retry building) and I find it's usually an error of the user (they forgot to write `touch`), not a deliberate intention. Putting it next to where you define rules is probably the most likely place for users to see it, since no one reads random floating sections :).
