### ISSUE TITLE
cmd ergonomics: making own cmd derivations

### ISSUE THREAD

**Issue by deepfire** [ndmitchell/shake#234]
Currently it's not easy to define a derivation of `cmd` without losing its special property -- vararg-ness.
And indeed, some derivations don't have an obvious way of making them.

Exhibit one: ..to avoid specifying the `unit $` prefix before each cmd invocation:
```haskell
type a :-> t = a
cmdn ∷ S.CmdArguments args => args :-> Action r
cmdn = unit . S.cmd
```
..fails type checking.

**Comment by ndmitchell** [comment]
That's expected - what `unit . cmd` says is that that you can eta expand to `\x -> unit (cmd x)`, which forces `cmd` into taking one argument. Unfortunately varargs functions all share these limitations, for example `printf` (https://hackage.haskell.org/package/base-4.8.0.0/docs/Text-Printf.html#v:printf) on which `cmd` was based. I don't believe it's possible to avoid the `unit`, or I would have provided it as `cmd_` (see `command_` which I do provide).

Any other examples you had in mind? It might be that some of them are possible.

**Comment by ndmitchell** [comment]
Please reopen if you have any specific `cmd` derivations you wanted which were tricky. Unfortunately, varargs-ness doesn't compose, and that's a limitation of Haskell (as far as anyone can tell), so I don't see any way round it.

**Comment by deepfire** [comment]
We probably need Oleg Kiselyov to cast his magic wand and solve vararg-ness for Haskell.. : -)
