### ISSUE TITLE
Set `close_fds` in `cmd`?

### ISSUE THREAD

**Issue by nomeata** [ndmitchell/shake#243]
Hi,

looking at the list of open files of a process spawned by a shake program, I noticed that it has, among other things, the shake data base open. At least on Linux, if you fork and exec, any open files are also available to the client.

I don’t think that this is ever, or at the most very rarely, the intended behavior in a shake program. Maybe `close_fds` should be set to `True` in `process` in `General.Process`?

Greetings,
Joachim

**Comment by ndmitchell** [comment]
Yep, seems perfectly sensible - I've done that unconditionally.
