### ISSUE TITLE
Test failure on GHC7.8.4

### ISSUE THREAD

**Issue by utdemir** [ndmitchell/shake#244]
## TESTING command
    ## BUILD command -j4
    # ghc (for output/command/shake_helper)
    [1 of 1] Compiling Main             ( shake_helper.hs, shake_helper.o )
      Linking shake_helper ...
    # shake_helper (for timeout)
    # shake_helper (for large)
    # shake_helper (for failure)
    # shake_helper (for capture)
    # shake_helper (for stdin)
    # shake_helper (for capture)
    # shake_helper (for async)
    # shake_helper (for timer)
    Command output/command/shake_helper took 2.828e-3 seconds
    # shake_helper (for file)
    # shake_helper (for file)
    Error when running Shake build system:
    * file
    ASSERTION FAILED: File contents are wrong: output/command/file.txt
    WANT: foo
    bar
    baz
 
    GOT: foo
    baz
    bar

    TESTS FAILED
    Test suite shake-test: FAIL
    Test suite logged to: dist/test/shake-0.15.1-shake-test.log
    0 of 1 test suites (0 of 1 test cases) passed.

I tested this on NixOS, and the latest version from Hackage(0.15.1)

**Comment by ndmitchell** [comment]
I've seen this once or twice, but never managed to reproduce it reliably - my best guess is a timing issue in flushing pipes. Does it reproduce reliably for you?

**Comment by ndmitchell** [comment]
To be clear, I think this is a bug in the test requiring too precise results, rather than an issue with the code in Shake itself.

**Comment by ndmitchell** [comment]
Hmm, I just got this again on Travis.

**Comment by ndmitchell** [comment]
Fixed as https://github.com/ndmitchell/shake/issues/264.
