### ISSUE TITLE
Why doesn't `cmd (Cwd dir, Shell) "task"` compile?

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#248]
I'm likely missing something, but I can't get this line to compile:

```haskell
unit $ cmd (Cwd dir, Shell) "task"
```

But of course I can do it with `command_`.

```haskell
command_ [Cwd dir, Shell] "task" []
```

**Comment by 3noch** [comment]
Nevermind, I just realized that `cmd` only takes one `CmdOption`.

**Comment by 3noch** [comment]
On a side note, the docs say that `cmd` can be run in the `IO` monad. How?

**Comment by ndmitchell** [comment]
It takes multiple options, but as separate arguments:

    unit $ cmd (Cwd dir) Shell "task"

To run it in the `IO` monad, just `:: IO ()` at the end - the return type polymorphism takes care of the rest.

**Comment by 3noch** [comment]
Thanks! Ah, that whole `:-> Action r` type throws me off every time. :wink:

**Comment by ndmitchell** [comment]
That type is just for documentation - it's defined as:

    type a :-> t = a

**Comment by 3noch** [comment]
:bulb: Wow.

**Comment by ndmitchell** [comment]
I should include an example showing how to pass multiple options.

**Comment by 3noch** [comment]
True, that'd be helpful.

**Comment by ndmitchell** [comment]
Added, along with an example of using it in IO.
