### ISSUE TITLE
Support POSIX glob syntax / pluggable pattern syntaxes

### ISSUE THREAD

**Issue by iand675** [ndmitchell/shake#249]
POSIX-style globbing is an extremely common syntax for most tools, so it would be nice to provide support for glob patterns where FilePatterns are currently used.

I think it would even be possible to add without breaking backwards-compatibility:

If you used the [Glob](http://hackage.haskell.org/package/Glob-0.7.5/docs/System-FilePath-Glob.html) library, you could replace current uses of `FilePattern` with a class:

``` haskell
class AsPattern p where
  (?==) :: p -> FilePath -> Bool

instance AsPattern FilePattern where
  (?==) = ... current definition ...

instance AsPattern Pattern where
  (?==) = System.FilePath.Glob.match
```

In any case, even if you didn't want to pull in the dependency on the `Glob` library, making it a class would be convenient because it would allow people to plug in their own pattern syntaxes.

**Comment by iand675** [comment]
Also, if you supported this, you could add a `newtype Literal = Literal FilePath` to only match against the precise same file, which would go nicely with #144 to not inflict the overhead of pattern matching when the exact filename is known.

**Comment by ndmitchell** [comment]
In the cases where `FilePattern` is a literal, I already do very cheap matching on it (I even hash them in advance and store them in sets to make bulk matching very cheap). For the pluggable syntax, an alternative is just to define something on top of `?>` (which I already use to implement `%>` anyway):

(%%>) :: String -> (FilePath -> Action ()) -> Action ()
(%%>) a b = match (compile a) ?> b

Now you can do globbing syntax with `%%>`. Is that enough, or can you think of cases where you want more?

**Comment by iand675** [comment]
My use-cases are more for the functions in the `Action` monad that use `FilePattern`.

`removeFiles`, `trackAllow`, and `getDirectoryFiles` are where I'd really love to have POSIX globbing (especially `getDirectoryFiles`!), and I don't think `?>` really does anything on that front.

**Comment by ndmitchell** [comment]
For `removeFiles`, you can just use the glob stuff directly with `liftIO` - there's no real "Action" stuff happening there.

For `trackAllow`, it's rare to use anything more than a directory, and rare to do anything at all yet (support for tracking on Linux is coming in the next version of Shake, but at the moment, `trackAllow` is mostly pointless).

For `getDirectoryFiles` there are lots of optimisations about scanning that are quite dependent on `FilePattern`. My guess is that it would be much better if you could just l lift `globDir` into a tracked Shake rule. At the moment you can write a Shake rule (just copy the existing `getDirectoryFiles` one), but it's not super-simple. I'm currently looking at how to make writing a new rule super-simple, and then that's probably the way to go.

**Comment by iand675** [comment]
OK, I'll give that a look. Thanks for the advice!
