### ISSUE TITLE
Problem with open file descriptors being inherited by started child processes (O_CLOEXEC not used)

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#253]
Hi Neil,

the following is a general program in Haskell on Linux, but I'd like to bring it to your attention first since I encountered it in Shake and it happens more often here given that Shake's purpose is often to start other programs.

Take a rule (or really any function `f` that gets called multiple times in parallel, e.g. with `forkIO`) that writes some binary file to disk, makes it executable and executes it:

```haskell
f :: IO ()
f = do
  inSomeTemporaryDirectory $ do
    BS.writeFile "mybinary" binaryContents
    setPermissions "mybinary" (setOwnerExecutable True emptyPermissions)
    _ <- readProcess "./mybinary" [] ""
   return ()
```

If this is happening in parallel (e.g. using `forkIO f >> forkIO f >> forkIO f >> threadDelay 5000000`), then on Linux the `readProcess` might often fail wit the error message `mybinary: Text file busy`. This error means *"Cannot execute the program 'mybinary' because it is open for writing by some process"*.

How can this happen, given that we're writing all `mybinary` files in completely separate temporary directories, and given that `BS.writeFile` guarantees to close the file handle / file descriptor (`Fd`) before it returns?

The answer is that by default, child processes on Unix (`fork()+exec()`) inherit all open file descriptors of the parent process. An ordering that leads to the problematic case could be:

* Thread 1 writes its file completely (opens and closes an Fd 1)
* Thread 2 starts writing its file (Fd 2 open for writing)
* Thread 1 executes "myBinary" (which calls `fork()` and `exec()`). Fd 2 is inherited by the child process
* Thread 2 finishes writing (closes its Fd 2)
* Thread 2 executes "myBinary", which fails with `Text file busy` because an Fd is still open to it in the child of Process 1

The scope of this program is quite general unfortunately: It will happen for any program that uses parallel threads, and that runs two or more external processes at some time. It cannot be fixed by the part that starts the external process (e.g. you can't write a reliable `readProcess` or `cmd` function that doesn't have this problem, since the problem is rooted in the Fds, and there is no version of `exec()` that doesn't inherit parent Fds).

This problem is a general problem in C on Unix, and was discovered quite late.

Naive solutions to this use `fcntl`, e.g. [`fcntl(fd, F_SETFD, FD_CLOEXEC)`](http://stackoverflow.com/questions/6125068/what-does-the-fd-cloexec-fcntl-flag-do), the equivalent of Haskell's `setFdOption` to set the `CLOEXEC` flag to all Fds before `exec()`ing. Fds with this flag are not inherited by `exec()`ed child processes. However, these solutions are racy in multi-threaded programs (such as typical Haskell programs), where an `exec()` made by some thread can fall just in between the `int fd = open(...); exec(...)` of some other thread.

For this reason, the `O_CLOEXEC` flag was added in Linux 2.6.23 (see e.g. [`man 2 open`](http://man7.org/linux/man-pages/man2/open.2.html)) to the `open()` syscall to atomically open a file and set the Fd to CLOEXEC in a single step.

This flag is not the default in Haskell - but maybe it should be. Other languages set it by default, for example Python. See here ([PEP-433](https://www.python.org/dev/peps/pep-0433/) and the newer [PEP-446](https://www.python.org/dev/peps/pep-0446/)) for a very good description of the situation; Python >= 3.2 closes open Fds *after* the `exec()` when performed with its `subprocess` module. Python 3.4 uses O_CLOEXEC by default on all Fds opened by Python.
It is also noted that [The programming languages Go, Perl and Ruby make newly created file descriptors non-inheritable by default: since Go 1.0 (2009), Perl 1.0 (1987) and Ruby 2.0 (2013)](https://www.python.org/dev/peps/pep-0446/#related-work).

A work-around for Haskell/Shake is to use `O_CLOEXEC` explicitly, as in this module `System/Posix/IO/ExecSafe.hsc`:

```haskell
-- | Exports some functions from `System.Posix.IO`, with the difference
-- that `Fd`s are opened with the `O_CLOEXEC` function, which makes sure
-- that the `Fd`s are not inherited by child processes (or more precise,
-- processes that are exec()ed from the current process).
module System.Posix.IO.ExecSafe
  ( openFd
  , createFile
  ) where

import           Foreign.C
import           Data.Bits
import           System.Posix.Types
import           System.Posix.Error
import           System.Posix.IO hiding (createFile, openFd)
import           System.Posix.Internals (withFilePath, c_open)

-- For O_CLOEXEC:
#include <fcntl.h>


-- | Like `System.Posix.IO.Common.open_`, but with `O_CLOEXEC` set.
open_  :: CString
       -> OpenMode
       -> Maybe FileMode -- ^Just x => creates the file with the given modes, Nothing => the file must exist.
       -> OpenFileFlags
       -> IO Fd
open_ str how maybe_mode (OpenFileFlags appendFlag exclusiveFlag nocttyFlag
                                nonBlockFlag truncateFlag) = do
    fd <- c_open str all_flags mode_w
    return (Fd fd)
  where
    all_flags  = creat .|. flags .|. open_mode

    flags =
       (#const O_CLOEXEC) .|. -- this is the critical difference to `System.Posix.IO.Common.open_`
       (if appendFlag    then (#const O_APPEND)   else 0) .|.
       (if exclusiveFlag then (#const O_EXCL)     else 0) .|.
       (if nocttyFlag    then (#const O_NOCTTY)   else 0) .|.
       (if nonBlockFlag  then (#const O_NONBLOCK) else 0) .|.
       (if truncateFlag  then (#const O_TRUNC)    else 0)

    (creat, mode_w) = case maybe_mode of
                        Nothing -> (0,0)
                        Just x  -> ((#const O_CREAT), x)

    open_mode = case how of
                   ReadOnly  -> (#const O_RDONLY)
                   WriteOnly -> (#const O_WRONLY)
                   ReadWrite -> (#const O_RDWR)


-- | Like `System.Posix.IO.openFd`, but with `O_CLOEXEC` set.
openFd :: FilePath
       -> OpenMode
       -> Maybe FileMode -- ^Just x => creates the file with the given modes, Nothing => the file must exist.
       -> OpenFileFlags
       -> IO Fd
openFd name how maybe_mode flags = do
   withFilePath name $ \str -> do
     throwErrnoPathIfMinus1Retry "openFd" name $
       open_ str how maybe_mode flags


-- | Like `System.Posix.IO.createFile`, but with `O_CLOEXEC` set.
createFile :: FilePath -> FileMode -> IO Fd
createFile name mode
  = openFd name WriteOnly (Just mode) defaultFileFlags{ trunc=True }
```

Then we can implement a safe version of `BS.writeFile`:

```haskell
-- | Writes a `BSL.ByteString` to a path, like `BSL.writeFile`, but opens the
-- path with the `O_CLOEXEC` option to make sure that the (write) file
-- descriptor is not inherited / held open by fork()+exec()ed child processes.
writeFileExecSafe :: FilePath -> BSL.ByteString -> IO ()
writeFileExecSafe f txt =
  bracket
    (do fd <- ExecSafe.createFile f stdFileMode
        fdToHandle fd `onException` closeFd fd)
    hClose
    (\hdl -> BSL.hPut hdl txt)
```

I'm using `writeFileExecSafe` now for my Shake build System that has this problem.

However, this is quite subobtimal, since all programs and library functions that open files will inherently trigger the `Text file busy` problem.

I wonder whether

* Shake should provide functions to provide exec-safe opening of `Fd`s / `Handle`s / writing of files, or whether
* this should be brought up in general on the GHC/libraries mailing lists, as many other programming languages have opted to make `O_CLOEXEC` the default.

**Comment by ndmitchell** [comment]
Did your comment get truncated?

**Comment by nh2** [comment]
> Did your comment get truncated?

Yes, I just updated with the full post.

**Comment by ndmitchell** [comment]
So it seems like a very general problem, and that one that all languages seem to be solving with the same solution. As such, it seems like bringing it up on the GHC/libraries mailing list is the right thing to do. While Shake could potentially provide a few of the `O_CLOEXEC` wrapped functions, they aren't going to be complete, and people probably won't actually use them.

Wouldn't a simple workaround be to write out the binary to `mybinary_` then do a `cp mybinary_ mybinary` call, so that the only open handles to `mybinary` occur in a `cp` subprocess that you know closes before you call `readProcess`?

**Comment by nh2** [comment]
> So it seems like a very general problem, and that one that all languages seem to be solving with the same solution. As such, it seems like bringing it up on the GHC/libraries mailing list is the right thing to do.

I have started a [discussion thread for this topic on the haskell-cafe mailing list](https://mail.haskell.org/pipermail/haskell-cafe/2015-July/120523.html), and will move it to GHC/libraries once some opinions have been collected.

As such, I think we can close this Shake issue.

> While Shake could potentially provide a few of the O_CLOEXEC wrapped functions, they aren't going to be complete, and people probably won't actually use them.

Yes.

> Wouldn't a simple workaround be to write out the binary to mybinary_ then do a cp mybinary_ mybinary call, so that the only open handles to mybinary occur in a cp subprocess that you know closes before you call readProcess?

Yes, that is a work-around.
