### ISSUE TITLE
Re-export types necessary for ShakeValue

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#258]
From somewhere (perhaps `Shake.Rules`) it would be convenient if you re-exported all the types necessary to define a `ShakeValue` (for an oracle, maybe). As is, oracles are very heavy-weight to add since you need half-a-dozen new import lines just to make the type! If you use cabal, you also have to add the same number of new dependencies. It's a lot of weight for something so simple IMHO.

**Comment by ndmitchell** [comment]
Excellent idea! So excellent, I've already done it: https://hackage.haskell.org/package/shake-0.15.2/docs/Development-Shake-Classes.html :)

**Comment by 3noch** [comment]
Haha, that's even *more* excellent. Thanks for the gracious response.
