### ISSUE TITLE
Being blocked on withResource counts to rule execution time

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#259]
In the shake report.html (Rule table), the `time` field is counted even if a rule is blocked on a resource.

Example:

```haskell
r <- newResource "sleepresource" 1
phony "sleep1" $ withResource r 1 $ cmd Shell "sleep 1"
phony "sleep2" $ withResource r 1 $ cmd Shell "sleep 1"
```

It somehow makes sense technically, since `withResource` guards an `Action` and not a `Rule`, but nevertheless it seems weird that the time being blocked counts to the rule execution time, since that will give you very different rule execution times, depending on which rule is chosen first (and that's chosen randomly).

Example: You want to link 3 binaries, `a`, `b`, and `c`, but you declare a with a resource that only 1 link shall happen at a time. Let's say `a` takes 1 second to link, `b` takes 10 seconds, and `c` takes 100 seconds.

Then if Shake decides to go for the order `c, b, a` you'll get a report on the following rule run times:

```
name   count  time
a      1 x    111.00s
b      1 x    110.00s
c      1 x    100.00s
```

Which doesn't reflect reality (or help with optimizing rule run time) very much.

I wonder whether Rule "timing" should be stopped when the rule is blocked on a resource, or whether non-blocked and total rule time should be measured and reported separately.

**Comment by ndmitchell** [comment]
I don't want to complicate the times by introducing two different times. Discounting the resource blocked time seems reasonable - I think I already do that in other places.

**Comment by ndmitchell** [comment]
OK, I discount time waiting for a resource in the profile report. Let me know if you still have issues with that.

**Comment by nh2** [comment]
Nice, this will be very useful for me.

I'm building a distributed Shake based build system, where my rules can offload tasks to other machines. To not block local resources for that (and to not have to determine a global, cluster-wide `-j`), I'm using `unsafeExtraThread`, and restricting how many jobs get run on each node using `withResource`.

So far, that messed up my reports, as all rules would start immediately due to `unsafeExtraThread`, and all rules would take equally long (the entire duration of the build system running). With this change being implemented, I can get accurate timings.

**Comment by ndmitchell** [comment]
Have you tried it yet, and did it work? It is in the latest release.
