### ISSUE TITLE
Test tracking stuff on Linux

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#261]
Should be tested as standard, and advertised properly.

**Comment by kirbyfan64** [comment]
I can do this if you want, provided you say how...

**Comment by ndmitchell** [comment]
Thanks for the offer @kirbyfan64 - but its pretty involved. It needs to go in my Travis script, which boostraps itself via a wget to some shell script in the `neil` repo, which bootstraps itself to the `neil` executable, which finally bootstraps itself back to the `shake` repo. It's mostly trial and error, and without immediate access to all the repos, the trial becomes much harder.

**Comment by ndmitchell** [comment]
Cc @jacereda, who wrote all the fsatrace stuff. This is the ticket I'm going to use to turn on the test suite, tidy up any hacks we find, and then aim to announce it for testers in the next release.

**Comment by ndmitchell** [comment]
It's all supported now, and tested only on Linux, ironically. Next release it will be first-class supported.
