### ISSUE TITLE
Test suite is non-deterministic

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#264]
There is some non-determinism involved, as the failures vary; I see

    Error when running Shake build system:
    * capture
    ASSERTION FAILED: failed in ===
    LHS: "1\n3\n2\n"
    RHS: "1\n2\n3\n"

or

    Error when running Shake build system:
    * file
    ASSERTION FAILED: File contents are wrong: output/command/file.txt
    WANT: foo
    bar
    baz
    GOT: foo
    baz
    bar

Reported by @nomeata

**Comment by ndmitchell** [comment]
Done. In both tests I was capturing from both Stdout and Stderr, and wanting a particular interleaving. That's a bit dodgy as they are different streams, and runtime differences may mean I pull from both in a different order. To make that robust, I added a wait (0.1s in one case, 0.2s in the other). On Windows 0.0s is enough about 90% of the time. For my tests I now start at 0.0s and gradually work up to 10.0s, which should make it only fail when it really is broken.

**Comment by nomeata** [comment]
Thanks

**Comment by ndmitchell** [comment]
Still broken on Travis:

    Error when running Shake build system:
    * file
    user error (Development.Shake.cmd, system command failed
    Command: output/command/shake_helper ofoo w10 ebar w10 obaz
    output/command/file.txt: openFile: resource busy (file is locked))

My guess is that I don't close files promptly enough on errors, so the handle is still open, and that makes the retries fail. I now start at 0 wait, so that increases the change a retry is necessary.

**Comment by ndmitchell** [comment]
Actually it was my tester that seemed to be hanging on to output, the actual Shake library uses `withFile` properly. I've updated the tester and am trying again.

**Comment by ndmitchell** [comment]
I'm going to make the completely invalid assumption that the test suite is now free from non-determinism - or rather squish whatever pops up next time.
