### ISSUE TITLE
Unable to build report from relocated shake executable

### ISSUE THREAD

**Issue by hesselink** [ndmitchell/shake#268]
We build our shake executable on a build server and copy it to developer machines. This works, but running it work `--report` crashes with:

```
/some/path/on/build/server/shake-0.15.2/html/profile.html: openBinaryFile: does not exist (No such file or directory)
```

This is probably due to the use of cabal data dirs. I have no idea how to fix this, though.

**Comment by ndmitchell** [comment]
You could copy the data around and set various paths/env variables, but I'm guessing a single binary would be easier for you? I had a vague plan to support bundling the HTML into the binary so that works, so if that works better for you, I could do that.

**Comment by hesselink** [comment]
Your vague plan sounds easier for us, but perhaps not for you :) I don't think it's important enough for us to muck around with the files and env vars... for now I just compile it locally if I want the reporting functionality, but it would be great if it could work out of the box at some point.

**Comment by ndmitchell** [comment]
I don't think it will be that difficult actually - or at least that's my hope.

**Comment by ndmitchell** [comment]
From #189 which asks for basically the same thing we have:

> Some users ship a Shake exe to their development team as a standalone binary, but if they do that, --profile doesn't work. One option is to have it search the directory next to the exe for profile files. Another option is to include a --bundle feature that takes the running exe and appends the profile files on the end, and then have the binary read the tail of itself first.
