### ISSUE TITLE
Idea: Parallel action running that isn't `need`

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#269]
There are a few places in Shake that invite to write less parallel build systems than they could be.

One of the main ways to introduce parallelism is `need`: When I `need [a, b, c]`, they can be built in parallel, but when I

```haskell
do need [a]
   need [b]
   need [c]
```

They cannot because there might be `Action` code between `need [a]` and `need [b]` that assumes that `a` was built, and Shake doesn't have knowledge of that there isn't in this case.

The type of `need :: [FilePath] -> Action ()` introduces the problem that I can't `need` an a normal file, an oracle, or a `newCache` at the same time; I have to run them sequentially in the `Action` monad, giving up parallelism.

I wonder whether it makes sense to introduce a construct that allows me to run multiple `Actions` in parallel, guaranteeing at compile time that they can't depend on each other's outputs.

The simplest way to do that would be adding a combinator `parallelly :: [Action ()] -> Action ()` or `:: [Action a] -> Action [a]`, but that doesn't do so well when I want to use the results (I either can't, or in the second example have to do a pattern match).

This calls for `Applicative`. [`Concurrently` from `async`](https://hackage.haskell.org/package/async-2.0.2/docs/Control-Concurrent-Async.html#t:Concurrently) is what solves this problem in IO.

Having something like that for `Action` would allow us to depend on all kinds of `Action` things in parallel, and them being `Applicative` would make the semantics clear (no order is enforced -> parallelism is possible).

**Comment by nh2** [comment]
I should also mention the more obvious alternative (;-)):

`Action`'s ``Applicative` instance could be parallel by default.

That would make it different from its `Monad` instance (e.g. `a *> b` wouldn't make sure that `a` runs before `b`, you'd have to use `a >> b` for that) - but that's allowed!

In theory that's exactly what e.g. parsers ought to do (but in practice nobody actually implements that): Their Applicative instance can be more efficient than their Monad instance since it gives them more statically known information.

In terms of a build system monad (which `Action` is), I wouldn't find that surprising at all.

**Comment by nh2** [comment]
I just discovered that this would also automatically make `for_ :: (Foldable t, Applicative f) => t a -> (a -> f b) -> f ()` parallel, which is exactly what I want in many cases.

**Comment by ndmitchell** [comment]
Making `Action` support `Applicative` with parallelism would be nice, and fits with the ideas of Haxl which does that. But I have two concerns:

* It's not obvious. While it is technically allowed by the semantics, I consider it walking on dodgy ground. You would generally expect someone to replace those constructs interchangeably, so every use of Applicative to gain parallelism is going to require a comment. If you have to comment it, why not have a function that makes it explicit?
* Technically it's quite fiddly. The `Action` monad is a continuation monad under the hood, and to make it be able to capture the requirements in advance is a lot of refactoring, that potentially slows down the normal "execute in order" case.
* While `need` and oracles are based on the same ideas (and can thus be packaged up into one call), the same isn't true of caches, which happen in an entirely different way. There parallelism would require spawning extra threads, which is hard to account for in the profiling.

So the question is how often do you think this is useful, and how much does it buy you? I've never needed it, but perhaps that's just a quirk of the type of things I'm doing. Does the profiling show that you are short of tasks to run, and if you could parallelise these things it would be a significant advantage?

The other thing is perhaps Applicative is just too limiting and awkward - you might "know" you need a particular dependency right at the beginning of the rule, but not actually need it til the end. While you can convert that to Applicative style, it's pretty ugly. You might imagine:

    defer :: Action a -> Action (Action a)

Which says to start computing the action, but don't block on it until I call the returned action. With that, you can get your parallelism. However, if you need to go that far, there's probably too much stuff in your rule.

My current thought is probably `defer` is the simplest implementation vs biggest payoff.

**Comment by ndmitchell** [comment]
As part of another feature, I had to introduce [parallel](https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Core.hs#L907):

    -- | Execute a list of actions in parallel.
    parallel :: [Action a] -> Action [a]

This isn't as efficient as parallel need, but my guess is that it's good enough, and gives you full flexibility. I thought about `defer`, but it has issues that you don't get errors back as fast, and if you spawn something but don't request it the semantics could be a bit surprising, especially if it raises an error. I'll clean that up, and then you'll be able to synthesise a parallel Concurrency applicative on top, if you need it, but I suspect most people won't.

I do have two parallelism helpers in https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Forward.hs#L97, namely:

    -- | A 'parallel' version of 'forM'.
    forP :: [a] -> (a -> Action b) -> Action [b]

    -- | Execute two operations in parallel.
    par :: Action a -> Action b -> Action (a,b)

So  maybe they should be available more generally? Both are trivial to implement in terms of `parallel`.

**Comment by ndmitchell** [comment]
I've made `parallel` generally available, and fixed up the issues and tested it. You could certainly layer a concurrency monad over the top of it, but I don't personally think it's worthwhile - if you try it in your build system and it seems valuable I'd be very interested. So now the underlying primitive is available you can do what you are after.

**Comment by nh2** [comment]
Cool, I'll try it out once the next release is available to my build systems!
