### ISSUE TITLE
Recursive invocations of build script

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#275]
Is it possible and safe to have a build script that launches itself via `cmd`, obviously leading to some sort of base case? I imagine that the shake database would not like that very much.

**Comment by ndmitchell** [comment]
If they use different databases you can do it, otherwise it will fail. Rarely should you do it though, for all the reasons given in the classic "Recursive Make considered harmful" paper.

**Comment by ndmitchell** [comment]
What's your use case?

**Comment by 3noch** [comment]
Well "harmful" is the least of my issues right now. :wink: My use case is a mess, but it's a mess we have to live with for now. I use a Shake-based build script to do all sorts of things, one of which is to launch a Visual Studio build. One of our Visual Studio projects builds a Haskell DLL as part of its build process. Building a Haskell DLL on Windows is...not pretty yet...so I wrote another build script using Shake to do that part of it. Right now it's using `stack runghc BuildDll.hs -- ...` in Visual Studio to do that part of it. I was considering simply joining the two scripts and doing the recursive call as I described.

**Comment by 3noch** [comment]
`stack` is a life saver here, because both the root build script and the inner build script can share `yaml` which guarantees that `Shake` is installed.

**Comment by ndmitchell** [comment]
Use a different build database and it should work out fine. Given you are currently going via Visual Studio that shouldn't be any worse. However, I would suggest trying to rationalise/simplify quite soon - complex build systems tend to get more complex quite rapidly.

**Comment by 3noch** [comment]
I would like to completely replace Visual Studio for doing builds (but keep it around as an editor). #247 is my challenge in that regard, however, since Visual Studio uses projects to isolate different components and I currently have no ways of doing that with Shake. I've considered building a thin configuration layer on top of Shake using yaml or JSON files, but of course, that starts to be a maintenance overhead by itself.

**Comment by ndmitchell** [comment]
One approach is to either interpret the Visual Studio file as metadata (so people can edit the build rules in VS), or have YAML/JSON files and interpret them to generate a the VS projects (we do that at work). I generally find that having Shake be an interpreter for some language actually works quite nicely. Shake ships with one simple configuration language at https://hackage.haskell.org/package/shake-0.15.4/docs/Development-Shake-Config.html

**Comment by 3noch** [comment]
> interpret the Visual Studio file as metadata

Do you have a parser for that? I realize it's XML, but there are a lot of fields to think about.

**Comment by ndmitchell** [comment]
I have a template to generate a file (which isn't hard) but no parser. I suspect parsing the resticted subset from any one project should be relatively easy.

**Comment by 3noch** [comment]
Interesting. I'll consider both of these options as I contemplate using Shake for all the legwork.

Feel free to close this issue.
