### ISSUE TITLE
Build failure in fclabels on armv6hf with ghc-7.4.1

### ISSUE THREAD

**Issue by gohai** [ndmitchell/shake#282]
While trying to build a C++ project that uses shake, I am hitting this build failure in fclabels: https://github.com/sebastiaanvisser/fclabels/issues/25.

The shake manual says to install the Haskell Platform - which I did by installing the Debian package haskell-platform (2012.2.0.0 with ghc-7.4.1). Is this not a supported environment or platform for running shake? Thanks!

**Comment by ndmitchell** [comment]
I support GHC all the way back to 7.2, but generally I'd encourage trying with 7.8 or 7.10 as they are the newest versions. I also don't particularly recommend the Haskell platform anymore - just plain old GHC (or MinGHC on Windows). I have confirmed that shake itself doesn't require fclabels, so I guess whatever build system you have written using Shake requires them? And I guess fclabels requires a newer version?

**Comment by gohai** [comment]
Thanks for the quick reply @ndmitchell. You're right - and apologies for that oversight - it was https://github.com/samplecount/shake-language-c that pulled in fclabels.

If GHC 7.4.1 is the highest my distribution offers, and the binaries for GHC [don't include arm](https://www.haskell.org/ghc/download_ghc_7_10_2#binaries), then the only thing I could do is to compile the compiler myself? Thanks!

**Comment by ndmitchell** [comment]
Certainly building the compiler yourself would work. Sometimes you can get bits from other distros to install - although I'm ignorant in this area, using either Ubuntu or Windows, both of which supply recent GHC versions compiled.

**Comment by ndmitchell** [comment]
Doesn't sound like a Shake issue, so I'll close this. Please reopen if you need further help.
