### ISSUE TITLE
removeFile on a literal file should be optimised

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#283]
@snowleopard reports that:

    liftIO $ removeFiles "." "file.bak"

On a single literal file does a complete recursive scan of the current directory. That should be optimised.

**Comment by snowleopard** [comment]
To be completely precise, the file is in a (deep) subdirectory:
```haskell
liftIO $ removeFiles "." ["a/b/c/d/e/file.bak"]
```

**Comment by ndmitchell** [comment]
This should now be super fast - 4 `doesDirectoryExist` followed by a `doesFileExist` and a `removeFile`.

**Comment by snowleopard** [comment]
Thanks! I'll test this and bring removeFiles back.
