### ISSUE TITLE
Temporary files/directories in other places

### ISSUE THREAD

**Issue by nomeata** [ndmitchell/shake#290]
Not always in `/tmp` the right choice for temporary directories, and the use of, say [withTempDirectory](file:///usr/share/doc/libghc-temporary-doc/html/System-IO-Temp.html#v:withTempDirectory) from the temporary package is not easily possible as there is no `MonadMask Action` type class. Therefore it would be nice to have variants of `withTempFile` and `withTempDirectory` that allow to specify a base directory.

For now it seems I have to copy the code from `extra` and `shake` and add a parameter.

**Comment by ndmitchell** [comment]
What's the rationale for creating a temp directory anywhere else? Whenever I've seen functions that take a temp dir argument, I've seen lots of lazy people pass ".", and garbage leak into people's current directory. My motivation for removing the option was to guide people towards the right behaviour. But I guess you're not one of those lazy people, so I'm keen to understand your reasons.

The reason `Action` doesn't have `MonadMask` is covered at https://github.com/ndmitchell/shake/issues/240#issuecomment-97186860 - it's pretty much an FAQ and needs a blog post on it.

**Comment by ndmitchell** [comment]
I turned it into a real StackOverflow question: http://stackoverflow.com/questions/32125187/why-does-shake-not-provide-a-monadmask-instance-for-action

**Comment by nomeata** [comment]
The motivation is that I need the temporary directory in a specific directory that is also made available (via a bindmount into a schroot) to the container that actually performs the build. Other uses for this might be the desire to choose /dev/shm, for being a tmpfs, or another partition known to be large enough.

**Comment by ndmitchell** [comment]
OK, that all seems reasonable - all I need is a name. `withTempFileAt`? `withTempFileEx`? `withTempFileInside`? I'll then add it to extra, and on to Shake.

**Comment by nomeata** [comment]
`withTempFileInside` sounds good

**Comment by l-d-s** [comment]
I second this request.

I'm using Shake on an HPC cluster, submitting jobs to be run on nodes that have their own , non-shared `/tmp`.

**Comment by l-d-s** [comment]
I suggest `withTempFile'` and `withTempDir'` or similar.

**Comment by ndmitchell** [comment]
I've just released `extra-1.6.1` containing `newTempFileInside` and `newTempDirInside` on which I can build these functions in Shake, so shouldn't be too hard soon.

**Comment by ndmitchell** [comment]
Super cool that you are using Shake on an HPC cluster. I've just pushed the code so it will be in the next release.
