### ISSUE TITLE
Multifile rules can go wrong when using digest for input files only

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#296]
Given:

    ["Bug1.txt","Bug2.txt"] &%> \[out1,out2] -> do
        need ["Bug3.txt"]
        writeFile' out1 "X"
        writeFile' out2 "Y"

If I run:

    writeFile (obj "Bug3.txt") "X"
    build ["--digest-and-input","Bug1.txt","--sleep"]
    writeFile (obj "Bug3.txt") "Y"
    build ["--digest-and-input","Bug1.txt","--lint"]

Then I get the error:

    Lint checking error - value has changed since being depended upon:
      Key:  output/digest/Bug1.txt
      Old:  File {mod=0x5731BD99,size=0x1,digest=NEQ}
      New:  File {mod=0x57369FB9,size=0x1,digest=0x8D268A1C}

The logic is:

* Look at the timestamp of Bug1.txt, observe it hasn't changed.
* Look at the dependencies of Bug1.txt Bug2.txt, observe it has changed.
* Rebuild Bug1.txt Bug2.txt.
* Look at the hashes of Bug1.txt and Bug2.txt, observe they haven't changed.
* Since Bug1.txt Bug2.txt has not changed, declare that Bug1.txt alone has not changed.
* Lint notes that the timestamp of Bug1.txt changed.

So the bug is when you look at the hashes of Bug1.txt/Bug2.txt to declare they haven't changed, since they are not inputs so should not be compared by hash.

**Comment by ndmitchell** [comment]
I now check ChangeModtimeAndDigestInput when looking at the files.

**Comment by snowleopard** [comment]
My issue seems relevant to this one. Consider the following build system:
```haskell
import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions { shakeFiles="_build"
                              , shakeChange = ChangeModtimeAndDigest} $ do
    want ["A1-plus-B"]

    "A1-plus-B" %> \out -> do
        a1 <- readFileLines "A1"
        b  <- readFileLines "B"
        writeFileLines out $ a1 ++ b

    ["A1", "A2"] &%> \[o1, o2] -> do
        writeFileLines o1 $ ["This is", "A1"]
        writeFileLines o2 $ ["This is", "A2"]

    "B" %> \out -> do
        writeFileLines out $ ["This is", "B"]
```

If I delete `A2` after a successful build, I get the following lint error in the subsequent rebuild:
```
Lint checking error - value has changed since being depended upon:
  Key:  A1
  Old:  File {mod=0x49DEEABD,size=0xD,digest=0x5136A886}
  New:  File {mod=0x4D5CA3FF,size=0xD,digest=0x5136A886}
```
Am I using multifile rules incorrectly? This happens to me in Hadrian, see https://github.com/snowleopard/hadrian/blob/master/src/Rules/Compile.hs#L41. If I delete a `hi` file and rebuild, I get a lint error similar to the above.
