### ISSUE TITLE
Shake for Cabal Packages with `setup-depends`

### ISSUE THREAD

**Issue by Ericson2314** [ndmitchell/shake#304]
With `setup-depends` finally on the horizon (see http://www.well-typed.com/blog/2015/07/cabal-setup-deps/), it seems like it would be possible to use Shake to build a cabal package.

What needs to be done to make this as convenient as possible? I have little Shake or custom Setup.hs experience, but it seems like there would be a bunch of boilerplate (command line argument parsing, etc) that could be put in Shake (or an additional library)

**Comment by ndmitchell** [comment]
I guess the first question is why you would want to use Shake to build a Cabal package rather than the normal `ghc --make`? If it's pure Haskell and Cabal can already build the package I can't see much advantage to using Shake. By identifying where Shake is of benefit, we might be able to tune what we are aiming for. I suspect the first thing to doing this well is for someone to try it and see what is hard, and probably write up a blog post giving a "how to" guide.

**Comment by Ericson2314** [comment]
Fair enough regarding `ghc --make`. Certainly for pure Haskell this is overkill, and most packages that aren't are wrapping some legacy library whose build system is not worth messing with. But I'd imagine that there are packages that might use make or shake or something else today (especially with cabal's support for make) and aren't wrapping a legacy library. I'd say it's both nicer to user shake than make etc, and cleaner to leverage Setup.hs than shell out to yet another process.

If that comes off as a flimsy rational, my "ulterior motive" is that I've been thinking about using this and the new shake-based build system for a quick-and-dirty way to make GHC buildable from cabal.

**Comment by ndmitchell** [comment]
Generally, build systems shell out to 100's of processes anyway, so reducing one shell out makes little difference. Perhaps for a few projects, but I doubt there are that many large projects using Cabal as their outer shell, which don't just write their own top-level command.

However, your ulterior motive seems awesome! I would like that a lot!!! Ping @snowleopard who is currently porting the GHC build system to Shake.

**Comment by snowleopard** [comment]
Hi there!
At the moment I do build GHC library packages (array, base, etc.) using Shake but I don't know whether my solution will be able to handle other Cabal packages. Maybe it will handle some, maybe it will be not too difficult to generalise it for building any Cabal package. I will discuss this with @ndmitchell next week when I will be in Cambridge (Neil, I hope you will be there?).

**Comment by Ericson2314** [comment]
> Generally, build systems shell out to 100's of processes anyway, so reducing one shell out makes little difference. Perhaps for a few projects, but I doubt there are that many large projects using Cabal as their outer shell, which don't just write their own top-level command.

Ah, I didn't mean the dynamic cost of forking processes, but rather the syntactic overhead marshaling argv etc in `Setup.hs` vs just using shake directly. Also, Cabal doesn't know how to build executables needed for the build process (e.g. Alex, Happy). In other words my concern is, elegance, not performance.

@snowleopard First of all, I haven't taken a good look at your's or the old GHC build system, so take this with a grain of salt.

For now, I'm just thinking of writing a dummy package to build all of GHC-the-executable: It wouldn't have any interesting or meaningful dependencies, just a custom `Setup.hs` which would import your shake work to kick off the build.

Once that is done, there are some interesting thing to pursue. As that article I linked hints at, the changes to the constraint solver will finally allow Cabal to understand bootstrapping: packages can use a different version of itself to satisfy a compile time dependency. Maybe it's possible to let cabal manage the "cyclic" GHC->GHC dependency, and shake manage the acyclic dependencies within GHC.

Finally, it would be cool to cabalize array, base, etc individually. This would I assume mean rewriting a good bit of your work somewhat by splitting a single Shake build system into one for each of those packages. Hopefully Cabal can be made smart enough to understand all the dependencies between those packages.

**Comment by snowleopard** [comment]
Thanks, this sounds very interesting. We can certainly try to reuse (parts of) the new Shake-based build system in the way you suggest. It's not ready yet but I'll let you know once I have a working prototype and will also be happy to help understanding it.

**Comment by Ericson2314** [comment]
Sweet! I'm pretty busy with school but would love to take a peek at such a prototype with the time I have.

**Comment by ndmitchell** [comment]
I don't think there's any concrete steps to make the setup-depends work nicely, so I'll leave it for now, and we can revisit once GHC installs with Shake. The other option would be to get Stack to integrate this nicely, so you could `stack setup --ghc-head` or similar.
