### ISSUE TITLE
Quoting is lost when printing executed commands

### ISSUE THREAD

**Issue by moosotc** [ndmitchell/shake#310]
q.hs
import Development.Shake
import Development.Shake.Util
import Development.Shake.Classes
import Development.Shake.FilePath

main = shakeArgs shakeOptions { shakeVerbosity = Loud } $ do
  want ["quoted", "unquoted"]
  "quoted" %> \out -> do
    (Stdout stdout, Exit _) <- cmd "cat" "hello world"
    writeFileChanged out stdout
  "unquoted" %> \out -> do
    (Stdout stdout, Exit _) <- cmd "cat" ["hello world"]
    writeFileChanged out stdout

/tmp% runghc q.hs -B
cat hello world
cat: hello world: No such file or directory
cat hello world
cat: hello: No such file or directory
cat: world: No such file or directory
Build completed in 0:01m

In the former case shake printed that it executed 'cat hello world' while in fact it did:
'cat "hello world"' i.e. quoting was lost while printing the executed commands.

**Comment by ndmitchell** [comment]
I don't think I ever intended to include the quoting, but there's no reason I shouldn't, and it would seem like a good idea for people trying to reproduce the commands - thanks for pointing it out.

**Comment by ndmitchell** [comment]
Looking at the process function, the Windows quote adding thing is very pessimistic, so I've written a version that does better on Windows and then used the default one on Linux.
