### ISSUE TITLE
Use operational package?

### ISSUE THREAD

**Issue by Mathnerd314** [ndmitchell/shake#318]
Rules and Action are contained rather neatly in Core, so they could be replaced with GADT's from the [operational](http://hackage.haskell.org/package/operational-0.2.3.2/docs/Control-Monad-Operational.html) package, e.g.:
```
data RulesADT a where
  NewResource :: String -> Int -> Rules Resource
  NewThrottle :: String -> Int -> Double -> Rules Resource
  NewCache :: (Eq k, Hashable k) => (k -> Action v) -> Rules (k -> Action v)
  Rule :: Rule key value => (key -> Maybe (Action value)) -> Rules ()
  Action :: Action a -> Rules ()
  Priority :: Double -> Rules () -> Rules ()
  Alternatives :: Rules () -> Rules ()
  WithoutActions :: Rules () -> Rules ()
  RulesIO :: IO a -> Rules a

type Rules a = Program RulesADT a

data ActionADT a where
    ActionBoom :: Bool -> Action a -> IO b -> Action a
    RunAfter :: IO () -> Action ()
    Apply :: Rule key value => [key] -> Action [value]
    ApplyKeyValue :: [Key] -> Action [Value]
    GetShakeOptions :: Action ShakeOptions
    GetProgress :: Action Progress
    Traced :: String -> IO a -> Action a
    PutWhen :: Verbosity -> String -> Action ()
    GetVerbosity :: Action Verbosity
    WithVerbosity :: Verbosity -> Action a -> Action a
    TrackUse :: ShakeValue key => key -> Action ()
    TrackCheckUsed :: Action ()
    TrackChange :: ShakeValue key => key -> Action ()
    TrackAllow :: ShakeValue key => (key -> Bool) -> Action ()
    BlockApply :: String -> Action a -> Action a
    WithResource :: Resource -> Int -> Action a -> Action a
    WithResources :: [(Resource, Int)] -> Action a -> Action a
    UnsafeExtraThread :: Action a -> Action a
    UnsafeIgnoreDependencies :: Action a -> Action a
    LiftIO :: IO a -> Action a

type Action a = Program ActionADT a
```
Besides being more pure, this approach would allow batching up Apply operations so that ``need ["a", "b"]`` and ``need ["a"] >> need ["b"]`` can be equally parallel.

I'm not sure how to handle the MonadFix instance for Rules (#270), so maybe this only makes sense for Action.

**Comment by ndmitchell** [comment]
I'm not sure I'd consider this a desirable direction to go in. We've gone from a place where individual features can be added without having a central list of permissible features, to one where everything needs to go into a central data type. For example, currently the tracked features are split off to the side, whereas now they need to be known about in the center.

The chance to merge adjacent `need`s would be cool, so maybe there is some benefit there. Any other benefits? And how would it interact with things like the continuation monad at the moment? I imagine I'd need to interpret this monad in a continuation monad?

**Comment by Mathnerd314** [comment]
Well, my initial idea for implementing the need-merging won't work, because ``apply`` returns a value instead of ``()``. I guess that could be changed. There aren't any other benefits to using operational that I can think of. It is low-overhead though, the same RAW monad used currently would be the interpreter.

**Comment by ndmitchell** [comment]
Did you have a particular example where `need` merging pays off? This kind of ties in with https://github.com/ndmitchell/shake/issues/269

**Comment by Mathnerd314** [comment]
Well, ``need`` itself isn't going to provide an example, since it's limited to files.

More interesting is this paper I just found: http://www.informatik.uni-marburg.de/~seba/publications/pluto-incremental-build.pdf. Their model allows running ``need <file>`` *after* the command that uses said file. This lets them run LaTeX without doing a Turing-complete dependency analysis.

**Comment by ndmitchell** [comment]
I've seen Pluto, and am a little concerned with some of their approaches. Their model doesn't actually let you run `need` after the file uses the command if that file also requires generating. In the case that Pluto works you can also do `need` in Shake, or `needed` (which is just `need` with a check you aren't going to have problems). The recursive knot tying is interesting, but I remain a little unconvinced - you can encode it pretty easily in Shake [as per here](http://stackoverflow.com/questions/14622169/how-to-write-fixed-point-build-rules-in-shake-e-g-latex) - and it's really only interesting for latex, and even then only if you have a latex file that reaches a fixed point (not all of them do), so I don't think it's worth baking it in the inside.

Anyway, I have a plan to write a more complete blog post on Pluto in the future.

**Comment by Mathnerd314** [comment]
After trying to understand Pluto's dependency injection, I ended up with this:
```
import Development.Shake
import Development.Shake.Command
import Development.Shake.Util

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles="_build"} $ do
    want ["test"]

    "test" %> \out -> do
        need ["a.png"]
        need ["x.pdf"]
        cmd "cp x.pdf test"

    "a.png" %> \out -> do
        need ["a.png.in"]
        cmd "cp a.png.in a.png"

    "x.pdf" %> \out -> do
        need ["x.tex"]
        () <- cmd "sort --merge x.tex a.png -o x.pdf"
        -- pretend a.png was dynamically discovered from the above command
        need ["a.png"] 
```
I think it violates Shake's dependency model, but for this program optimizing ``need x >> need y`` to ``need [x,y]`` is not correct (because then 'test' would be racy).

**Comment by ndmitchell** [comment]
I think it's entirely allowable, but certainly not a good idea without a huge comment. Maybe if I ever do automatically combine `need` we'd need some kind of `barrier` command to ensure needs before were all built before needs after.

If writing this in Shake, I'd encourage changing the final `need ["a.png"]` to `needed` then it checks you don't run into problems after. In Shake, if you `need` something after using it (as you do in the `.pdf` rule, you are under the obligation that it doesn't change during the `need`. The `needed` just checks that obligation, but `need` is still correct.

Note that if you think you might use `a.png` but are not sure, you can put `orderOnly` before the `cmd`, and then it isn't a dependency, but will have been built. That's probably a cleaner way to put the dependency, unless you really do want the `a.png` output.

**Comment by Mathnerd314** [comment]
Interesting. If it is supposed to work, then there's a bug in ``-B``:
```
$ touch a.png.in && runhaskell Main.hs x.pdf
# cp (for a.png)
# sort (for x.pdf)
$ touch a.png.in && runhaskell Main.hs -B x.pdf
# sort (for x.pdf)
# cp (for a.png)
```

**Comment by ndmitchell** [comment]
I stand corrected - I don't think that is supposed to work. It works if you build `test`, but if you build `x.pdf`, or do anything funky with `-B` or similar it's not going to work.

**Comment by Mathnerd314** [comment]
I think it "could" work, in the sense that there is enough information available in the recorded dependency graph to force doing a.png before x.pdf (using Pluto's assumption that "a builder may not drop a requirement if all previous requirements are up-to-date"). It would require changing Shake's algorithm a bit though.

**Comment by Mathnerd314** [comment]
> Anyway, I have a plan to write a more complete blog post on Pluto in the future, many of their comments on Shake are somewhat incorrect.

I guess [this](https://groups.google.com/d/msg/shake-build-system/FgHVGpuxhfE/IRf7kqiJCgAJ) is that post.

**Comment by Mathnerd314** [comment]
> I think it "could" work, in the sense that there is enough information available in the recorded dependency graph to force doing a.png before x.pdf

And now that is Shake's actual behavior, checking dependencies before running the main rule.

**Comment by Mathnerd314** [comment]
I'm closing this issue since it doesn't seem like an ADT for Rules / Action would gain anything, and the Latex example now works.

**Comment by ndmitchell** [comment]
I think I agree with that - and putting every possible option in the same ADT centralises things I'd rather be separate. I am happy to expose `apply_prim` or similar if you have a use case for it? However, I suspect `parallel` combined with `apply` is probably simpler and has similar parallelism results (although I'm sure performs worse in microbenchmarks).

**Comment by Mathnerd314** [comment]
For apply_prim, to quote from #269:
> The type of need :: [FilePath] -> Action () introduces the problem that I can't need an a normal file, an oracle, or a newCache at the same time; I have to run them sequentially

`need` could instead be based on a typeclass:
```haskell
apply_prim :: [Key] -> Action [Value]
apply :: (Appliable a) => a -> Action (Result a)
apply x = fromValueList . apply_prim . toKeyList
need :: (Appliable a) => a -> Action ()
need x = void $ apply x
class Appliable a where
  type Result a :: *
  toKeyList :: a -> [Key]
  fromValueList :: [Value] -> Result a
instance Appliable Key where Result Key = Value
instance Appliable FilePath where Result FilePath = ()
instance (Appliable a, Appliable b) => Appliable (a,b) where Result (a,b) = (Result a, Result b)
...
```

Oracles would need an instance for each type, but using it would be as easy as
```haskell
(_, res) <- apply (["a" "b" "c"], MyOracle ...)
```

The general difference is that `apply_prim` takes a single database lock and uses as many cached values as possible, while `parallel` + `apply` will have to lock many times and must spawn a thread regardless of caching.

Using this for `newCache` is trickier, as that also has to avoid using `build`, and it doesn't need the database lock, so `parallel` might still be preferred there.

**Comment by ndmitchell** [comment]
Hmm, another potential option would be to define:

    (ShakeValue k1 v1, ShakeValue k2 v2) => ShakeValue (Either k1 k2) (Either v1 v2)

And then you could do:

    [_, _, _, Right res] <- apply [Left "a", Left "b", Left "c", Right $ MyOracle ...]

You could imagine it doing just nested calls to `apply`, but then you could also imagine optimising away the intermediate `Either` key. For the new formulation you would do it in a slightly different way, but with much the same principle - probably baking the `Either` dispatching into `apply` itself.

Does that seem valuable? My initial inclination was that the extra verbosity and complexity required to define `Appliable` made it not worth it - but perhaps sticking to simple `Either` it's simple enough once more and doesn't "infect" people not using this style.

**Comment by Mathnerd314** [comment]
I don't particularly care; any method can be implemented using applyKeyValue, newKey, and fromValue, so just exposing those would work.
