### ISSUE TITLE
Export :-> from Development.Shake.Command

### ISSUE THREAD

**Issue by kaoskorobase** [ndmitchell/shake#336]
Could the `:->` type operator be exported from Shake? This would make creating abstractions based on `cmd` more straightforward.

**Comment by ndmitchell** [comment]
What abstraction do you have in mind? Since `:->` is a type alias, it's really exposed whether I export it or not.

**Comment by kaoskorobase** [comment]
For example something like:

````
{-# LANGUAGE TypeOperators #-}
module Git where

import Development.Shake
import Development.Shake.Command

git :: CmdArguments args => args :-> Action r
git = cmd "git"
````

Currently fails with

    Not in scope: type constructor or class ‘:->’

**Comment by ndmitchell** [comment]
Now done. Note however that `a :-> b` is an alias for `a`, so you could equally write:

    git :: CmdArguments args => args
    git = cmd "git"

I only use `:->` to hint at the expected result type - it's not checked.

**Comment by kaoskorobase** [comment]
OK, now I get it! Anyway, now I can just copy-paste `cmd`'s signature ;-)
