### ISSUE TITLE
Typo in documentation for &%>

### ISSUE THREAD

**Issue by kaoskorobase** [ndmitchell/shake#337]
In the [documentation](https://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake.html) for `&%>`, instead of

> Think of it as the OR (||) equivalent of %>.

it should read

> Think of it as the AND (&&) equivalent of %>.

unless I am missing something.

**Comment by ndmitchell** [comment]
If you read the docs, it actually says both ways round - whoops (AND at the top, OR at the bottom). I've deleted the OR one. Thanks!

**Comment by kaoskorobase** [comment]
Ah yes, I've missed the AND part. Thanks for the fix!
