### ISSUE TITLE
Change the manual to use neededMakefileDependencies

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#344]
That's the recommended way of doing it, as raised by @ezyang.

**Comment by ezyang** [comment]
BTW, I'm OK with submitting patches for this sort of thing, if that would make your life easier.

**Comment by ndmitchell** [comment]
This one is a bit bigger, rewrite the manual, balance the presentation everywhere. If you want to have a whirl, I'd very much welcome a patch, but it's the kind of thing I'll do sooner or later anyway (the main task before the next release is redoing most of the website, which is already fairly different in HEAD to on the website). I am very keen for documentation patches from users in general, since they tend to describe what users want to know, rather than my guesses at what users want to know.

**Comment by ezyang** [comment]
OK, well, I can also file bugs saying where things are confusing/unclear and leave it to you :)

**Comment by ndmitchell** [comment]
The bugs are most appreciated!

**Comment by dwijnand** [comment]
Fixes in https://github.com/ndmitchell/shake/pull/699

**Comment by ndmitchell** [comment]
Thanks @dwijnand
