### ISSUE TITLE
Development.Shake.Rule unclear about stored value semantics; does "not stored externally" mean phony?

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#348]
The manual states:

> For rules whose values are not stored externally, storedValue should return Just with a sentinel value and equalValue should always return EqualCheap for that sentinel.

I don't understand what this means. For example, if I want to make a separate namespace of phony targets (rather than the built-in phony support, which lives in the same namespace as files), this is not something that is "stored externally"; so should I follow the advice here? The answer is no!

```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
import Development.Shake
import Development.Shake.Classes
import Development.Shake.Rule
import Control.Monad

newtype Phony = Phony String
    deriving (Show, Typeable, Eq, Hashable, Binary, NFData)
newtype PhonyVal = PhonyVal ()
    deriving (Show, Typeable, Eq, Hashable, Binary, NFData)

instance Rule Phony PhonyVal where
    storedValue _ _ = return (Just (PhonyVal ()))
    equalValue _ _ _ _ = EqualCheap

main :: IO ()
main = shakeArgs shakeOptions $ do
    action (void (apply [Phony "foo", Phony "bar"] :: Action [PhonyVal]))
    rule $ \(Phony x) -> Just (liftIO (putStrLn x) >> return (PhonyVal ()))
```

Then I get:

```
ezyang@sabre:~/Dev/labs$ ./aaa 
bar
foo
Build completed in 0:01m
ezyang@sabre:~/Dev/labs$ ./aaa 
Build completed in 0:01m
```

which is not what phony rules are supposed to do. So it seems stored value should always return `Nothing`. (What should equalValue do? I don't see a difference either way.)

(For that matter, what is something that is not stored externally?!)

**Comment by ndmitchell** [comment]
`equalValue` is doc bug, I don't remember writing that piece of the docs, and it's definitely not true. If your type supports sensible equality (as `()` does), then you don't need to worry.

The basic idea behind storedValue is you are asking "is the value consistent on disk". If you have a value on disk, you should return it, and if it sometimes has a value but not always, Nothing. However, if your rule never has a value on disk then returning Just () says "never rebuild" unless one of the other dependencies changes, and Nothing says "always rebuild". I'll make the docs much clearer, and probably add an example or two.

For curiosity, why are you trying to redefine phony rules in a different namespace? Any particular reason? The fact that phony is in the same namespace as files is a bit sad (from a nice theory point of view), but alas, what users seem to expect.

**Comment by ezyang** [comment]
While reimplementing `ghc --make A B.hs` etc, the arguments are the targets that I should want. But they don't live in the file namespace: A says "I want you to build the outputs corresponding to the module name A", and B.hs says "I want you to build the outputs corresponding to source file B.hs".

**Comment by ndmitchell** [comment]
Makes sense. Although you could translate them directly to action statements and skip the rule step, perhaps.

**Comment by ezyang** [comment]
Good idea. In fact, I'll do that, because the rule infrastructure is otherwise not helping me.

**Comment by ndmitchell** [comment]
Yes, I do that in the Ninja translator - I guess phony should mention this technique.

**Comment by ndmitchell** [comment]
All the functions have changed, and all the docs too, so hopefully the new stuff is cleaner - but if not, do shout.
