### ISSUE TITLE
Make style Shake output?

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#351]
I am quite fond of Make's command line output, and I would quite like it if Shake did the same. I didn't see anything obvious in Shake's command line set which would do this; --trace didn't really output anything. Am I supposed to add "output" myself?

**Comment by ndmitchell** [comment]
Is --verbose close? Can you give a concrete example of the make output you like?

**Comment by ezyang** [comment]
Actually, I realized what's going on: `cmd` has calls to the tracing function itself, but if you don't use `cmd` (as I am) then obviously no tracing will occur.

So there's some missing doc hint, which is that Shake does NOT print out anything when it starts a rule (it wouldn't want to, because if you're doing all cmd then adding extra output would make your output look distinctly not Makelike) but that means if you don't use cmd, you have to do your own tracing.

**Comment by ndmitchell** [comment]
In that case you are recommended to use traced. Where would you expect to find such docs?

**Comment by ezyang** [comment]
I... don't know, actually. I almost want Shake to mention that you need to trace yourself if there's no trace output.

I suppose what I was looking for was a mode where Shake reports every rule it's running, I thought `--verbose` did this, but actually I had to write the trace rules myself, and that's what I ACTUALLY want.

**Comment by ndmitchell** [comment]
You seem to be describing `--verbose --verbose` which I believe prints at the start and exit of a rule. However, rules often get highly interleaved, since the `need` switches from one to another and back again, so using `traced` is usually the only sane way to do it.

**Comment by ezyang** [comment]
Yeah, traced is clearly what I want. I guess we should close this, unless you think there's a legit doc bug.

**Comment by ndmitchell** [comment]
I think it's mentioned everywhere,

**Comment by dwijnand** [comment]
Fixed in https://github.com/ndmitchell/shake/commit/9b42a2d191bc7eaccdeb2cf016cfd7610e4f4c3a
