### ISSUE TITLE
Grammar-check Shake report help

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#352]
> does (is) the rule a leaf, with no dependencies.

>  last time the rule was build (built), was the value detected as unchanged(?)

The two that popped out for me. My corrections in parens.

**Comment by ndmitchell** [comment]
Thanks for the spots.

**Comment by ndmitchell** [comment]
I must have been in a hurry when writing those the first time round... Changes applied, and I fixed the (?) with:

> last time the rule was built, did the value not change
