### ISSUE TITLE
shakeArgs flags should be documented somewhere

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#359]
Yes I know I can get it using `shake --help` but sometimes doing that is really annoying.

**Comment by ndmitchell** [comment]
The website could also explain how to set them as shakeOptions and more details that are too long for a single line.

**Comment by ndmitchell** [comment]
There's now https://github.com/ndmitchell/shake/blob/master/docs/CommandLine.md, which will go on the website next time I upload.
