### ISSUE TITLE
traced should be decomposed into two functions

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#362]
Currently, the string passed to traced is used for two purposes:

1. It is printed out to the console,
2. It is used to organize the timing information in the profiler.

Suppose that you want to print out the estimated time remaining with these trace messages. You could add that information to the string you pass to "traced", but then it will leak into your profiler (and you don't want that.)

It seems like these should be decoupled in some way: there should be a "silent" variant of traced which sets up profiling information, but doesn't print anything; a user can then manually add any extra logging they want.

**Comment by ndmitchell** [comment]
I think you should be able to do:

    putNormal $ "Message I want to show"
    quietly $ traced $ actionIWantToRun

If you confirm that works (I believe it should), then there is a solution, and it becomes a documentation problem - probably docs for `traced`.

**Comment by ezyang** [comment]
Confirmed that this works!

**Comment by ndmitchell** [comment]
Docs for `traced` should say what it does (both profiling and printing to the screen), and say how to get only one (either use putNormal, or quietly).
