### ISSUE TITLE
Add website page detailing progress options and tricks

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#363]
I'm using a windowing manager which doesn't have titlebars, so I can't actually easily see asynchronous progress messages that Shake is configured to do by default. I'd like to have Shake output progress to the command line as it handles "big" commands, but there does not seem to be any good way to actually do this. I can get Progress, of course (on HEAD) but I have to then manually format it myself, which is a chore.

**Comment by ndmitchell** [comment]
The fact that Shake prints its async progress messages to the titlebar is entirely controlled by https://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake.html#v:shakeProgress, which defaults to:

    progressSimple :: IO Progress -> IO ()
    progressSimple p = do
        program <- progressProgram
        progressDisplay 5 (\s -> progressTitlebar s >> program s) p

How do you mean output to the command line? Have you considered having a separate status window where Shake can put this output? Overwriting `progressSimple` to instead use:

     progressDisplay 5 print

Might be sufficient.

Tagging this as website, since the website could do with a whole page detailing options for progress, how it works etc.

**Comment by ezyang** [comment]
If it's going to be asynchronous to the command line, then a better aesthetic is for it to "overwrite the old status with a new status" terminal stuff. But that's pretty nontrivial to do if you also want to support other diagnostic output.

But, I guess what I could do is put the (asynchronously) passed in string to an MVar and then read it out when I want to give an update...

**Comment by ndmitchell** [comment]
Stack does something quite nice - the last line is always the "progress", and then the diagnostics scroll above that, which is quite easy to implement. Writing the output async into an MVar isn't a bad plan.

**Comment by ezyang** [comment]
Yes, but Shake needs to play ball: for example, the tracing functions need to be responsible for clearing out the bar, and then redrawing it after you've put in the diagnostic. It's not too difficult to implement but you need cooperation from the messagers.

**Comment by ndmitchell** [comment]
Shake only writes messages via https://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake.html#v:shakeOutput - so you should be able to do that yourself. Some people have changed that function to write to a web server, rather than a console.

**Comment by ezyang** [comment]
Nifty. OK, that should be enough for my use case. Closed!

**Comment by ndmitchell** [comment]
This ticket seems to have turned into a list of neat tricks and explanations for progress reporting. It should be collected with other information into a web page.

**Comment by ndmitchell** [comment]
Contents have been dumped into a Profiling page.
