### ISSUE TITLE
putLoud / putQuiet do the opposite thing

### ISSUE THREAD

**Issue by 01mf02** [ndmitchell/shake#369]
Using `putLoud` with default verbosity currently displays nothing, whereas `putQuiet` does.
This is due to a bug in `putWhen`:

```
putWhen :: Verbosity -> String -> Action ()
putWhen v msg = do
    Global{..} <- Action getRO
    verb <- getVerbosity
    when (verb >= v) $ -- BUG! it should be: when (v >= verb) $
        liftIO $ globalOutput v msg
```

**Comment by ndmitchell** [comment]
I think that's intentional. The idea is that if you `putQuiet` you want it to appear when running normally, and _even_ when running with `--quiet`. In contrast, with `putLoud` you are saying print this message only when running with `--verbose`. If you flip the comparison then `putNormal` would only appear in verbosity Quiet and Normal, which doesn't make much sense - generally you want a message to appear at a particular verbosity and all higher levels.

I agree the docs aren't very clear, because they are the same for all of the `put*` things. Changing that seems like a good idea.

Does that all seem to make sense?

**Comment by ndmitchell** [comment]
Regardless of which way it should be, the Haddock docs aren't very clear, so should be improved after agreeing about the intended behaviour.

**Comment by 01mf02** [comment]
Ah, now I see your intention! :)
I interpreted it completely the other way around, though. I thought that `putQuiet` is like whispering -- you only hear something if you listen really close (with --verbose), and `putLoud` is like shouting -- you always hear it.

> If you flip the comparison then putNormal would only appear in verbosity Quiet and Normal, which doesn't make much sense - generally you want a message to appear at a particular verbosity and all higher levels.

Yes, I expect that a message should appear at a particular verbosity and all higher levels. So when using putNormal, I expect it exactly to appear in verbosity Quiet and Normal. Why do you think it does not make sense? :)

**Comment by 01mf02** [comment]
Ok, looking at the verbosity data type, I think that I now understand your intention also for the naming of putLoud / putQuiet. But I still find it very confusing, mostly because messages are not verbose -- people are. So the current concept of verbosity in Shake is the problem.

How about we look at another Haskell package made for the purpose of logging, namely "hslogger"? There, we do not have "verbosity", but "priority", ranging from DEBUG to EMERGENCY. "Verbosity" could then be defined as "which priorities to print". That is, `type Verbosity = Priority -> Bool`. So users could set something like `shakeVerbosity = (>) Debug` to print everything that has a higher priority than Debug messages, or just `shakeVerbosity = (=) Alert` to print only alerts.
Similarly, one could then define something like `putNotice`, `putDebug` etc. to call the shakeVerbosity predicate to determine whether to print the message.

**Comment by ndmitchell** [comment]
Assuming Emergency is higher than Alert, when would someone want to print equal to Alert but skip the Emergency things? I think inherently people want an importance level and anything more important than it. Maybe the mistake here was talking about verbosity and not priority, which as you say, makes a lot more sense. I think more docs are a necessity at a minimum.

**Comment by ndmitchell** [comment]
I've now made the docs clearer. I can entirely see `putLoud` both ways round - one is `putWhenLoud`, the other is `putLoudly` - and `putLoud` works for both. One thought I had was adding `putImportant` (alias for `putQuiet`) and `putUnimportant` (alias for `putLoud`), then deprecating the old ones, which might make the intention clearer. Thoughts @01mf02 and @ezyang?

**Comment by 01mf02** [comment]
I strongly support `putLoudly` and `putQuietly` (shorter than `putImportant`), then deprecating the old ones. Cool that you are so open to suggestions regarding Shake! :)
(I really enjoy using it. Thanks for your awesome work.)

**Comment by 01mf02** [comment]
(Even if I still think that `Loud` and `Quiet` as verbosity levels carry large potential for confusion. As volume is not necessarily related to verbosity.)

**Comment by dwijnand** [comment]
I'm proposing a replacement in https://github.com/ndmitchell/shake/pull/706

**Comment by ndmitchell** [comment]
Fixed since now putLoud and putQuiet are both deprecated, and it's much more standard. Very nice work!
