### ISSUE TITLE
Is the Hashable instance in newCache guaranteed not to be serialized to disk?

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#373]
The description seems to suggest so.

**Comment by ndmitchell** [comment]
It is not serialised. NewCache has no disk impact at all.

**Comment by ezyang** [comment]
Great! (In fact, is any Hashable results assumed to be stable across program invocations?)

**Comment by ndmitchell** [comment]
No, I never assume Hashable is reliable across runs. That's especially true with the salted hash stuff that Hashable supports.

**Comment by ezyang** [comment]
OK great. Consider this a doc bug!

**Comment by ndmitchell** [comment]
Tagged as such, thanks.
