### ISSUE TITLE
"/a/.//*.c" ?== "/a/b.c" is False

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#375]
I think it should be `True`.

Context: I was building patterns using `</>`, but if you say `"/foo" </> "//*.hs"` you end up with `//*.hs`, not `/foo//*.hs`. The dot should make it clear that this pattern is relative.

**Comment by ezyang** [comment]
Reading the internal documentation, `**` may be an acceptable workaround.

**Comment by ezyang** [comment]
Related problem: `**/*.hi` matches `/not/my/directory/Foo.hi`, which is not desirable.

**Comment by ndmitchell** [comment]
File patterns don't ignore `/./` pieces, deliberately - they are more lexical and less based around FilePath notions. Generally, don't include `/./` in a file path pattern. I think once you use `**` for patterns you stop having the `</>` issue in the first place, and thus the desire to insert `.` goes away. In the meantime, you can use `"/foo" <//> "*.hs"`, which inserts two slashes without doing the ignoring of the LHS.

**Comment by ndmitchell** [comment]
For more discussion about patterns in general, see #376 .

**Comment by ndmitchell** [comment]
The docs say:

> Patterns with constructs such as `foo/../bar` will never match
> normalised 'FilePath' values, so are unlikely to be correct.

Which hopefully when combined with all the other file pattern pieces is sufficient.
