### ISSUE TITLE
How do I run the test suite?

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#378]
I tried running the executable but I got this error:

```
ezyang@sabre:~/Dev/shake-pr$ /srv/code/cabal-shake/dist-newstyle/build/shake-0.15.5/build/shake-test/shake-test test
Longest file modification time lag was 5ms
## BUILD tar test
## TESTING tar
## BUILD tar --abbrev=output=$OUT -j3
Writing report to $OUT/tar/report.html
/home/ezyang/.cabal/share/x86_64-linux-ghc-7.11.20151220/shake-0.15.5/html/profile.html: openBinaryFile: does not exist (No such file or directory)
TESTS FAILED

```

**Comment by ndmitchell** [comment]
Did you `cabal install` first? That looks like you are running the test suite without access to the `data-dir` files. Alternatively, setting the `shake_datadir` environment variable to point at where `html/profile.html` lives (probably `pwd`) should work.

One for the website on the developer page.

**Comment by ezyang** [comment]
Nope, I was trying to run the test suite in place, so that would explain it.

**Comment by ndmitchell** [comment]
As a standard Cabal convention, is that expected to work?

I could also modify the code to when testing immediately check for the profile file, and if missing, give a polite and complete explanation, so no one has to go hunting for the docs.

**Comment by ezyang** [comment]
It works unless you have a `data-dir`. :) An error message would be sufficient, IMO.

**Comment by ndmitchell** [comment]
It now says:

```
C:\Neil>shake\dist\build\shake-test\shake-test.exe
******************************************************************
** Running shake test suite, run with '--help' to see arguments **
******************************************************************

shake-test.exe:
ERROR: Must run the test suite from a directory containing the Shake repo.
```

**Comment by ndmitchell** [comment]
I was originally going to document this, but `cabal test` is now sufficiently well known that it doesn't need it.
