### ISSUE TITLE
Generalize 'ShakeOptions' argument in Rule's storedValue method

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#383]
It would be very helpful if 'ShakeOptions' had a user-programmable, 'TypeRep' map which they could use to add their own data to be available when implementing 'storedValue' and 'equalValue'. Otherwise, it's too difficult to implement a Rule instance when the 'storedValue' needs some (non-global) configuration. File gets a config flag; why not our own rules too!

**Comment by ndmitchell** [comment]
Yes, I actually agonised over the file config flag for a while, since it bakes files into the "heart" of Shake, when otherwise they would be purely on the outside. Agreed having other rules have access is a good idea.
