### ISSUE TITLE
Export unsafeIgnoreDependencies

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#393]
Without it, there's no way to define `orderOnly` equivalents for non-file rules.

**Comment by ndmitchell** [comment]
Do you have a real case where you want to define something like `orderOnly` on non-files? Generally, I'm a little cautious of `orderOnly`, so expanding that power to reuse more widely might be a bad thing.

**Comment by ezyang** [comment]
I use it here: https://github.com/ezyang/ghc-shake/blob/master/GhcShake.hs#L265

I suppose I need a custom rule here partially because of #382 but also partially because structuring the build system this way makes it clearer.

**Comment by ezyang** [comment]
Still on hot path.

**Comment by Mathnerd314** [comment]
Permalink: https://github.com/ezyang/ghc-shake/blob/9cf14b33a02b1228189295a0f69bf21b4cf14d39/GhcShake.hs#L268

**Comment by ndmitchell** [comment]
I added this as `orderOnlyAction` - in general it's no more unsafe than `orderOnly`, and can be synthesised from the existing primitives (e.g. a rule which always returns the same sentinel value).
