### ISSUE TITLE
Oracles should warn against oracles whose keys have many inhabitants

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#394]
Oracles are run every invocation of Shake, so oracles who take unbounded keys can quickly run up a hefty "repeatedly rerun" cost.

**Comment by ndmitchell** [comment]
If oracles run too much they should show up quite clearly on the profile, so I'm not overly concerned about that. There are lots of good uses for "unbounded" oracles, in particular Strings, and I've done that many times - for example library to version number mapping, or file name to command line.

I think it is important to add that information to the oracle docs though. The docs currently say:

> Actions passed to addOracle will be run in every build they are required

But then goes on to talk about rebuild behaviour. A warning about not making them numerous or expensive is a good idea.

**Comment by ezyang** [comment]
Here's an example run of a build with a lot of oracles: http://web.mit.edu/~ezyang/Public/ghc-shake-report.html?mode=rule-table&query=run()%20==%200&sort=!name

There are certainly a lot of oracles in the output, but they all take zero time. Should I be concerned? Not concerned?

**Comment by ezyang** [comment]
(Not hot path.)

**Comment by ndmitchell** [comment]
Looking at http://web.mit.edu/~ezyang/Public/ghc-shake-report.html?mode=rule-table&query=run()%20==%200%20&&%20name(/%5E(%5Cw%2B)/) it becomes even clearer that both Oracle and Cache have zero runtime impact on that build. I've made a note in the docs that people should be careful with expensive actions. Hopefully after splitting into `oracleRerun` and `oracleCache` then that warning can go on its own with just the right places.
