### ISSUE TITLE
Oracles should not be defined over Action (except perhaps for code reuse)

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#395]
The action monad is primarily used to track dependency usage. But dependency usage doesn't matter for oracles: they are always invalid and must be rerun. So it doesn't matter what dependencies you specify for oracles; you might as well just give them IO actions (or pure values you computed in the IO section of your program.) So the usage of Action in addOracle is incredibly misleading (and seems to imply that the dependencies might make a difference... they do not.)

Indeed, the whole POINT of oracles is to give you a way to let Shake interface with the parts of your build system which do not have nice dependency tracking in the action monad. If you do have dependency tracking, don't use an oracle! (Use a cache instead.)

**Comment by ndmitchell** [comment]
While a change in the dependencies won't change the amount of recomputation, it can be very useful to have oracles that call `need` to build files, so the oracle's result depends on another result and it can be properly wired into the dependency graph. As a practical example, see [`usingConfigFile`](https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Config.hs#L63) - that is an oracle that ultimately does a `need` on the config file that it grabs pieces from.

Certainly worth making this clearer in the docs though.

**Comment by ezyang** [comment]
You could have equally used `orderOnly` in this example, right? The need is solely being usd to make sure the config file actually exists.

**Comment by ndmitchell** [comment]
Inside an oracle need and orderOnly are equivalent, yes.

**Comment by ezyang** [comment]
(Not hot path, just something I observed)

**Comment by ndmitchell** [comment]
In fact, if you have alwaysRerun in an action block, then orderOnly and need are entirely equivalent - Oracle is just a special case of that. I think once we have oracles that are rerun and oracles that aren't then the difference will be clearer, and the reason for `Action` makes a lot more sense.
