### ISSUE TITLE
Only require old-time with portable turned on with GHC 7.4

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#398]
In all other circumstances the old-time library is not required, so I should avoid having it as a dependency. cc @snowleopard

**Comment by snowleopard** [comment]
Note: in my use-case (as part of the new GHC build system) `old-time` will never be required at all, because the bootstrapping GHC must be 7.10+.

**Comment by ndmitchell** [comment]
All sorted, now only requires old-time for GHC 7.4 in portable mode.
