### ISSUE TITLE
Lock the .database file on Linux

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#4]
Evan Laforge reported that Shake does not lock the .database file on Linux, which means that you can run two concurrent copies of Shake against the same database, and they damage each other. Evan says: you can lock with files, which has a nice '80s feel to it, but there is also fcntl().  It looks like the stdlib has a binding to fcntl, though poorly documented:

```haskell
import qualified System.Environment as Environment
import qualified System.Posix.IO as IO
import qualified System.IO as IO

main :: IO ()
main = do
    [fn] <- Environment.getArgs
    fd <- IO.openFd fn IO.ReadWrite Nothing IO.defaultFileFlags
    IO.waitToSetLock fd (IO.WriteLock, IO.AbsoluteSeek, 0, 0)
    print "locked"
    getLine
    return ()
```

This one blocks, you can also call IO.setLock and catch the exception
(ick) if it fails. Historically you would use lock files because fcntl wasn't reliable
over NFS, but I hear that has been fixed at some point.  I'm hardly an
expert though.

**Comment by ndmitchell** [comment]
This breaks on Windows now - I think they loosened the semantics of openFile on Windows (now shared rather than exclusive), so I should come up with a cross-platform fix.

**Comment by ndmitchell** [comment]
Random thought: If you rename a file that is in use elsewhere, does the other process automatically switch to the new name? Or fail? If it has detectable behaviour, might provide some safety.

**Comment by ndmitchell** [comment]
Added and implemented for both Windows and Linux. Based on Evan's original code for Linux.

**Comment by pacak** [comment]
It would be nice to have that configurable. That prevents you from starting any long running processes from shake in one tab (such as ghcid) and doing regular compilation in another.

**Comment by ndmitchell** [comment]
You mean so two processes are both working on the Shake database at the same time? The lock is there because without it the database gets corrupted - removing the lock wouldn't make it work. Having multi-process simultaneously is way more complicated because the two processes need to communicate a lot.

**Comment by pacak** [comment]
Not technically at the same time. One process starts, installs missing packages, deals with TH related stuff then creates command line for ghcid and starts it. After that nothing is going on in this process and I can use second one to actually compile things. It's been working like that for more than a year so there might be cases when both processes actually worked at the same time. I've seen no issues.

**Comment by ndmitchell** [comment]
@pacak - OK, that makes sense. It sounds like invoking `ghcid` waits until `ghcid` exits, but you don't do any further build actions after that. I'd instead suggest to spawn `ghcid` after Shake returns, and after the Shake database has been closed. While what you have probably works most of the time, there's always the chance Shake will flush the database on the `ghcid` spawning process after you have done something else, and then the database will corrupt itself.

**Comment by bitc** [comment]
> I'd instead suggest to spawn ghcid after Shake returns, and after the Shake database has been closed

Do you have any advice how to do this? The only thing I can think of is to `forkIO` and then run `ghcid` from the forked thread. And before forking set some MVar or such to indicate to the main thread that when `shakeArgs` completes it should block. Is there a simpler way?

**Comment by bitc** [comment]
Ok, this is what I've come up with:

```haskell
main :: IO ()
main = do
    postBuildAction <- newIORef (pure ())
    let addPostBuild = \newAction ->
            liftIO $ atomicModifyIORef postBuildAction $ \a -> (a >> newAction, ())
    shakeBuild addPostBuild
    id =<< readIORef postBuildAction

shakeBuild :: (IO () -> Action ()) -> IO ()
shakeBuild addPostBuild = shakeArgs shakeOptions{shakeFiles=buildDir ++ "/"} $ do
    phony "ghcid" $ do
        -- Do whatever shake stuff you want
        -- ...
        addPostBuild $
            callProcess "ghcid" ["arg1", "arg2"]

```

**Comment by ndmitchell** [comment]
Have you seen [`runAfter :: IO () -> Action ()`](https://hackage.haskell.org/package/shake-0.16.4/docs/Development-Shake.html#v:runAfter) ? It's basically your `postBuildAction` - and in fact even the implementation is basically the same as you've sketched above.

**Comment by bitc** [comment]
Looks like `runAfter` was  recently added. Works like a charm! :+1:
