### ISSUE TITLE
getDirectoryFiles should be clear and tested

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#401]
https://github.com/snowleopard/shaking-up-ghc/issues/117#issuecomment-169290771 shows the confusion over what happens when which directories don't exist. Looking through, I didn't see enough tests, so a ticket to add haddock docs and tests.

**Comment by snowleopard** [comment]
An additional question about the lint error behaviour: if I run `getDirectoryFiles "" [dir -/- "*.o"]` and `dir` does not exist at this point (so the result is []), but it is created later in the build process, will lint also complain? Presumably it should complain about `getDirectoryFiles` returning a different result, not about `doesDirectoryExist` as in my case.

**Comment by ndmitchell** [comment]
Yes, it will complain. So it ultimately leaves you with exactly the same error as before in your case.

**Comment by snowleopard** [comment]
Thanks. That's good. I think the error is also going to be more useful (it'll show the newly added files).

**Comment by ndmitchell** [comment]
The test I used to answer these questions was:

        putNormal . show =<< getDirectoryFiles "C:/spacework/shake/docs" ["*.md"]
        putNormal . show =<< getDirectoryFiles "C:/spacework/shake" ["docs/*.md"]
        putNormal . show =<< getDirectoryFiles "C:/spacework/shake/doc" ["*.md"]

**Comment by snowleopard** [comment]
I am confused by this travis log: https://api.travis-ci.org/jobs/102204258/log.txt?deansi=true. The built ended with the following error:
```
* getDirectoryFiles  [.build/stage0/gmp/objs/*.o]
.build/stage0/gmp/objs: getDirectoryContents: does not exist (No such file or directory)
```
Here is the corresponding piece of code:
```haskell
getDirectoryFiles "" [gmpObjects -/- "*.o"]
```
I thought that there shouldn't be any error if the directory does not exist with the above code. Am I mixing up things again? My current understanding is that the following should error instead:
```haskell
getDirectoryFiles gmpObjects ["*.o"]
```
/cc #168

**Comment by ndmitchell** [comment]
Your understanding matches mine. I will extensively test and audit this tomorrow morning and let you know if we were correct...

**Comment by ndmitchell** [comment]
Hmm, I had some optimisations in Shake released version to do faster searches for concrete prefixes. I wonder if I screwed that up...

**Comment by ndmitchell** [comment]
@snowleopard - confirmed, this is incorrect in the released Shake and got fixed when I rewrote the directory search optimiser, but I didn't realise it got fixed.

**Comment by snowleopard** [comment]
OK, I'll use a workaround with `doesDirectoryExist` while we are waiting for the next Shake release.

**Comment by ndmitchell** [comment]
Now documented and tested.
