### ISSUE TITLE
Phony actions with backslashes don't work correctly on Windows

### ISSUE THREAD

**Issue by mtolly** [ndmitchell/shake#405]
If you make a `phony` action using the `</>` operator, which uses backslashes on Windows, the action isn't run correctly. It says there is no rule available, unless a file/folder by that name exists, in which case it does nothing (the action isn't run).

Compile the following, or clone https://github.com/mtolly/shake-phony-path

  ```hs
module Main where

import Development.Shake
import Development.Shake.FilePath

main :: IO ()
main = shakeArgs shakeOptions $ do
  phony "foo/bar" $ do
    liftIO $ print 1
  phony ("baz" </> "quux") $ do
    liftIO $ print 2
  ```

On OS X, the correct results:

```
$ stack exec shake-phony-path foo/bar
1
Build completed in 0:01m

$ stack exec shake-phony-path baz/quux
2
Build completed in 0:01m

$ mkdir -p foo/bar baz/quux

$ stack exec shake-phony-path foo/bar
1
Build completed in 0:01m

$ stack exec shake-phony-path baz/quux
2
Build completed in 0:01m
```

On Windows 7, 64-bit but compiling 32-bit, in an `msys2` shell:

```
$ stack exec shake-phony-path foo/bar
1
Build completed in 0:00m

$ stack exec shake-phony-path foo\\bar
1
Build completed in 0:00m

$ stack exec shake-phony-path baz/quux
Error when running Shake build system:
* baz/quux
Error, file does not exist and no rule available:
  baz/quux

$ stack exec shake-phony-path baz\\quux
Error when running Shake build system:
* baz/quux
Error, file does not exist and no rule available:
  baz/quux

$ mkdir -p foo/bar baz/quux

$ stack exec shake-phony-path foo/bar
1
Build completed in 0:00m

$ stack exec shake-phony-path foo\\bar
1
Build completed in 0:00m

$ stack exec shake-phony-path baz/quux
Build completed in 0:00m

$ stack exec shake-phony-path baz\\quux
Build completed in 0:00m
```

All results are the same in the normal `cmd` shell; just replace all the double backslashes in commands with single ones.

**Comment by ndmitchell** [comment]
Thanks for the detailed report. The issue is that with `%>` I match `/` and `\` without distinction, and with `need` I always replace `\` with `/` for consistency. I now also replace `\` with `/` in the phony rule, so the code above works.

For info, how come you are adding phony targets with `/` in them? Do they represent file paths? If so, why are you using phony?

**Comment by mtolly** [comment]
They represent directories, and the phony actions are simply to build a certain set of files inside those directories. The way I have my program set up, the sequence of directories for a filename encodes "options" for that file, so for example `gen/x/y/z/file.ext` is the file `file.ext` but with options x, y, and z chosen. So then the phony action `gen/x/y/z/dir` is a shortcut for `need`ing `gen/x/y/z/dir/foo`, `gen/x/y/z/dir/bar`, etc. and thus I want the action to look like the directory even though it doesn't have to, so it will have those options encoded in it.

This is probably not the most elegant way to do it, and eventually I'll probably make a nicer interface where the options are real command line options and the built files just get immediately copied out of the `gen` directory to wherever the user wants them.

Here are the actual places in my code where this came up:
https://github.com/mtolly/onyxite-customs/blob/master/haskell/build/src/Main.hs#L672-L679
https://github.com/mtolly/onyxite-customs/blob/master/haskell/build/src/Main.hs#L973-L983
`dir` in the code is the `gen/x/y/z` part, so it is defining those rules for a specific combination of options.

And here's one that isn't a directory; when you build `gen/x/y/z/problems`, it builds some other files in the `gen/x/y/z` directory and then runs a diagnostic step on them, so it's more like a traditional phony command. https://github.com/mtolly/onyxite-customs/blob/master/haskell/build/src/Main.hs#L1004-L1045

**Comment by ndmitchell** [comment]
Using phony for directories makes a lot of sense - thanks for sharing. It looks an interesting project :)
