### ISSUE TITLE
newCache documentation

### ISSUE THREAD

**Issue by Mathnerd314** [ndmitchell/shake#409]
The documentation has this sentence:

> Using the cached result will still result include any dependencies that the action requires.

Before ed92129d9b4b37783fd3e6328d0e9061391e7fe0, it read:

> Using the cached function will still result in a dependency on the original file. The argument function should not access any files other than the one passed as its argument. 

I'd prefer it if the documentation specified the actual behavior of calling `need` in the action/function passed to `newCache`...

**Comment by ndmitchell** [comment]
Good idea. Before ed92129d9b4b37783fd3e6328d0e9061391e7fe0 the function had different semantics, so ignore what it says before that. The basic rule is any key is computed at most once, anyone who asks for something in the cache will get the value and also depend on anything that the computing the value depended on. (I don't find that very clear as a description, so I'll try and figure something clearer out.)

**Comment by ndmitchell** [comment]
It now says:

> Using the cached result will still result include any dependencies that the action requires - e.g. if the action does 'need' then those dependencies will be added to every rule that uses that cache.
