### ISSUE TITLE
Precompiled binaries fail on RedHat 4.1.2-54

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#411]
Using the normal binaries I get:

    $ ./stack
    ./stack: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

Using the CentOS 6.x binaries, I get:

    $ ./stack
    ./stack: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./stack)

Not sure if there's anything that can be done about this. Any chance of reducing the dependencies of stack, e.g. by linking in more stuff?

I appreciate this system is ancient, and understand you may not want to bother fixing it.

**Comment by vasiliyl** [comment]
You can compile stack as a static binary. Unfortunately glibc can't be linked statically, so you should use some other C library like musl. After that will "weight" tens of megabytes, but it will work anywhere.

**Comment by ndmitchell** [comment]
I meant to raise this against stack, but had the wrong tab open. Now reraised properly: https://github.com/commercialhaskell/stack/issues/1721. Thanks for the feedback @vasiliyl, I've copied it to Stack.
