### ISSUE TITLE
Option to embed data-files into the library

### ISSUE THREAD

**Issue by vasiliyl** [ndmitchell/shake#413]
My team uses shake to build the product we develop. Me and one of my colleagues, we are maintaining the build system while others just use it. We would like it to be as independent as possible so we compile and distribute the build script as a static binary. Everything works great except reports - shake tries to find it's report templates in a compile-time-defined directory, which obviously does not exist when you run a static binary you've just downloaded. 
We would like to have a build option to embed the data files into binary so that the static binary could generate reports.
I have googled 'http://haddock.stackage.org/lts-5.0/file-embed-0.0.9.1/Data-FileEmbed.html', looks like it can be used to accompliish the task.
I think, I can do that by myself, but I'd like to discuss the feature beforehand.

**Comment by ndmitchell** [comment]
See also #189, which seems to be the same feature request but targeted at a different implementation mechanism, and #268 which asks much the same question. I think I prefer the solution here to the one floated in #189, but I wouldn't want to add a dependency on `file-embed` since it requires Template Haskell which complicates GHC bootstrapping stories. I think we need:

* A nice 1-liner that integrates file-embed and Shake and profiling properly.
* A description of how to set environment variables properly so Shake profiling works with profiling files next to the binary.

**Comment by vasiliyl** [comment]
Yes, those are the same issues. Sorry, I didn't notice them before posting a new one.

> A nice 1-liner that integrates file-embed and Shake and profiling properly.

Not sure if I understood you right. Can we use cabal build flags or, maybe, preprocessor defininions to specify if file-embed should be used?

> A description of how to set environment variables properly so Shake profiling works with profiling files next to the binary.

Does Shake provide this functionality or should it be implemented first?

**Comment by ndmitchell** [comment]
> Not sure if I understood you right. Can we use cabal build flags or, maybe, preprocessor definitions to specify if file-embed should be used?

Hmm, I hadn't thought of that, I was imagining something quite different. Some way that I could advertise the complete list of files and embed them, likely by adding them to the tail of the executable.

> > A description of how to set environment variables properly so Shake profiling works with profiling files next to the binary.

> Does Shake provide this functionality or should it be implemented first?

Cabal provides this functionality as https://www.haskell.org/cabal/users-guide/installing-packages.html#prefix-independence.

**Comment by vasiliyl** [comment]
> Hmm, I hadn't thought of that, I was imagining something quite different. Some way that I could advertise the complete list of files and embed them, likely by adding them to the tail of the executable.

Ah, I know that trick. I used it in shell script with embedded data. The data is a compressed tar archive which is concatenated to the end of script. When run the script scans itself, finds the beginning of the archive and extracts what it needs. Not very elegant, perhaps, but quick and straightforward.

> Cabal provides this functionality as https://www.haskell.org/cabal/users-guide/installing-packages.html#prefix-independence.

Ah, I've seen that paragraph, but it says that it's Windows specific feature. The docs may be outdated though.

**Comment by vasiliyl** [comment]
While browsing Shake's reports code I noticed that html is not the only report format it supports.
After looking at the API docs I discovered that in addition to html it can generate json, js, and chrome's trace files. So I have another idea related to current issue.

In my case developers _users-of-build-system_ do not read reports, in case of any trouble they just send them to me _build-system-maintainer_.After that I need to analyze them. Shake could have an option to create html report using json report. Or it could provide html page like the existing one but with a button to open json report. Or something like this. That would satisfy all of my team needs.

Secondly, I didn't find the docs about different report formats on http://shakebuild.com, I think they should be mentioned there.

Should I open new issues perhaps?

**Comment by ndmitchell** [comment]
Ah, if you pass --report=output.json and then splice that JSON into an existing report (should be relatively easy to figure out where), you'll get what you need. Yes, all those things sound desirable - documentation of what exists, and the JSON splicing (although it really is easy in a text editor).
