### ISSUE TITLE
Support GHC 8.0

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#415]
In RC1 I hit https://ghc.haskell.org/trac/ghc/ticket/11379 and https://ghc.haskell.org/trac/ghc/ticket/11458, both of which got fixed for RC2.

RC2 gave us https://github.com/haskell/directory/issues/42 which is now fixed. I'm currently running into into https://ghc.haskell.org/trac/ghc/ticket/11555.

**Comment by ndmitchell** [comment]
Now the fact that fclabels doesn't support GHC 8.0 is my current bottleneck (since I test the shake-language-c project), so test suite and compilation all seem fine.

**Comment by kaoskorobase** [comment]
Hi Neil, FWIW eventually I'd like to switch `shake-language-c` to `lens` again, not sure if that would help. Can't give an ETA at the moment unfortunately.

**Comment by ndmitchell** [comment]
@kaoskorobase - doesn't make much odds to me either way, no real rush on this, since I know the real bits of Shake all work.

**Comment by ndmitchell** [comment]
I raised the fclabels issue at https://github.com/sebastiaanvisser/fclabels/issues/31, and they seem to have a few fixes circulating, e.g. https://github.com/sebastiaanvisser/fclabels/pull/32.

**Comment by hesselink** [comment]
Yes, sebastiaanvisser/fclabels#32 is the full fix. There's currently a [a transformers issue](http://hub.darcs.net/ross/transformers/issue/22), but if you really need it, I could release without that. That will probably mean the test suite will break again with RC3.

**Comment by ndmitchell** [comment]
@hesselink - thanks for the offer, but no real need - I'm happy to wait until after RC3. I've got the fundamental Shake test suite working so I'm happy to wait a bit.

**Comment by ndmitchell** [comment]
fclabels is in, I've turned back on the full test suite for 8.0 and it passes. Only remaining issue is https://ghc.haskell.org/trac/ghc/ticket/11555.

**Comment by ndmitchell** [comment]
Another GHC bug - https://ghc.haskell.org/trac/ghc/ticket/11830. Seems `-I0` is buggy in the later RC variants.

**Comment by ndmitchell** [comment]
I think we're now fully working with GHC 8.0 rc4 - mostly because GHC keeps fixing the bugs, which is great. Backing out the GHC 11555 tweaks then closing this ticket.

**Comment by ndmitchell** [comment]
Backed out the 11555 fixes. Shake works out of the box with GHC 8.2 so all happy.
