### ISSUE TITLE
--assume-new / --assume-old are not implemented

### ISSUE THREAD

**Issue by Mathnerd314** [ndmitchell/shake#419]
They're present in the argument parser, but don't work:
```
$ touch a.png.in && ./Main --trace --assume-old=a.png.in
cp a.png.in a.png
Build completed in 0:01m
$ ./Main --trace --assume-new=a.png.in
Build completed in 0:01m
```

#161 could probably be implemented in the same code, using ``AssumeNew`` for files that changed and ``AssumeOld`` for everything else. And this would also do #251 with --assume-old=stage1/compiler.exe.

**Comment by ndmitchell** [comment]
Are you sure they don't work at all? They might just have bad semantics, I've never been very happy with the design of these bits. I was working on the design of a better assume-new/assume-old yesterday, so might be able to solve this by making things simpler and more powerful.

**Comment by Mathnerd314** [comment]
From what I can tell, https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Args.hs#L128 (an error message) is the only place they are used.

**Comment by ndmitchell** [comment]
I removed them, and #436 will add better alternatives.
