### ISSUE TITLE
**.c pattern does not work as expected

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#420]
"**.c" ?== "foo/test.c"
    False

I would guess that should be true, but it really isn't.

**Comment by ndmitchell** [comment]
I note that FishEye doesn't list this as an example, https://ja.confluence.atlassian.com/fisheye/pattern-matching-guide-298976797.html, and neither does Ant, https://ant.apache.org/manual/Types/fileset.html

@ezyang - do you have any opinion on whether this is a valid pattern? Seems that it reasonably could be, but the less of the world I reinvent the better. I don't have any tools installed that use such patterns so I can test.

**Comment by ezyang** [comment]
I guess permitting `**.c` is non-standard. Honestly, this pattern is uncommon enough that I don't care what Shake, as long as it can be specified formally in a concise way.

**Comment by ndmitchell** [comment]
I guess it's non standard so it will get whatever the formal semantics implies - which is probably equivalent to `**/.c`. People can still write `**/*.c` if they want, which is nice and clear.
