### ISSUE TITLE
Temporary files aren't so temporary

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#429]
I'm finding lots of `extra-file-xxxx` in my Temp directory under Windows. Some of them contain fsatrace results, some contain console output that I capture via `FileStdout` or `FileStderr`. 

I don't know how to reproduce, it's only a very small percentage of the total temporary files created. 

I get them even if there's no interruption in the build process (I end up with roughly 50 temporaries after a full build).

Anyone experiencing the same?

**Comment by jacereda** [comment]
Not extremely important, but I think this could be deleted now?

https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Command.hs#L563

**Comment by jacereda** [comment]
Doh! The latest build didn't leak any file. I don't know what happened, perhaps it was leaking because I was trying to observe files as they leaked by updating my dired buffer under emacs and the deletion failed... 
Closing.

**Comment by ndmitchell** [comment]
Yep, the algorithm is to try to delete the file, but if you can't, just ignore and continue. Thanks for investigating.
