### ISSUE TITLE
Rules for directories

### ISSUE THREAD

**Issue by fakedrake** [ndmitchell/shake#430]
First of all thank you for this awesome package. The following is a variation of an [SO question](http://stackoverflow.com/questions/35938956/haskell-shake-special-rule-for-building-directories) I asked the other day.

Sometimes it is the case that to create a directory `mkdir` is not the right tool. It may be `git clone` or `rsync` or `mount`. So when we have a rule like this:

```
needDir dirs = filterM ((fmap not) . doesDirectoryExist) dirs >>= need

rules = do {
  "project" </> "tool" %> \out -> do {
    needDir [takeDirectory out];
    cmd "make -C" [takeDirectory out];
    }

  "project" %> \out -> cmd "git clone a.url.to/repo.git" [out]
  }
```

As one might expect the `"project" </> "tool"` creates the directory project before anything else and git clone isn't even run. Is there a way to go around this?

My best guess ATM is that we should:

- Make an equivalent to `%>` for `DoesDirectoryExistQ`, or make a new `Rule DirQ DirA` that would have the equivalent end user functionality as `FileQ`.
- Change the `root` function in `Rules/File.hs` to try to find a `DirQ`/`DoesDirectoryExistQ` based rule for creating the directory before falling back to `createDirectoryIfMissing`.

If these suggestions are misguided, we should at least be exposing `Rule` and `apply` to the end user.

**Comment by fakedrake** [comment]
Someone on SO suggested (but the answer was deleted) some trickery using intermediate and phony rules. I just wanted to point out here that while this approach *could* work, I feel like it would add the kind of complexity that we use a build system to avoid.

**Comment by ndmitchell** [comment]
I saw your SO question, and was about to answer later today, but the SO format doesn't really encourage refinement of the question and dialogue, so let's discuss here and then update SO afterwards.

Agreed, we want a simple solution. I also note that `Rule` and `apply` are both available from `Development.Shake.Rule`, but you probably don't want them. The other thing to note is from the docs for `%>` we have:

    This function will create the directory for the result file, if necessary.

So generally it's not necessary to call `mkdir` or `createDirectoryIfMissing`. The other thing to note is that having dependencies on directories isn't really an idea Shake has - all things must be dependencies on files.

So if I were going to have something that did a git clone if the file was missing, I'd do:

    "project/.git/index" %> \out -> do
        cmd "git clone a.url.to/repo.git" ["project"]

Does that make sense? Does it have some issue with that I haven't envisaged? (The git example seems simpler, so lets solve that one first, then solve the make one after)

**Comment by fakedrake** [comment]
Aha that makes sense. Thank you very much for the advice.

Here is some sample code (pity there are so few examples for shake out there):

*shakefile.hs*
``` haskell
import Development.Shake
import Development.Shake.FilePath

main :: IO ()
main = shakeArgs shakeOptions{shakeVerbosity = Chatty} $ do {
  want ["b.bin"];
  "b.bin" %> \out -> do {
      need ["project/a.bin"];
      cmd "touch" [out];
      };

  "project/a.bin" %> \out -> do {
      need ["project/.git/index"];
      cmd "touch" [out];
      };

  "project/.git/index" %> \out -> do{
      cmd "git clone https://github.com/ndmitchell/shake" [out];
      };
}
```

And how to run it:

```
$ runhaskell shakefile.hs 
# project/a.bin
# project/.git/index
git clone https://github.com/ndmitchell/shake project/.git/index
Cloning into 'project/.git/index'...
touch project/a.bin
# b.bin
touch b.bin
Build completed in 0:12m
```

**Comment by fakedrake** [comment]
Sorry about the open/close. Let me redefine the problem:

`b.bin` depends on the existence of `project`. However `project` needs to be patched in some way, in our case that means creating `project/a.bin`. So basically `b.bin` depends on `project/a.bin` and `project/a.bin` depends on `project/.git/index`.

So here is some code that does not work updated with your advice:

``` haskell
import Development.Shake
import Development.Shake.FilePath


main :: IO ()
main = shakeArgs shakeOptions{shakeVerbosity = Chatty} $ do {
  want ["b.bin"];
  "b.bin" %> \out -> do {
      need ["project/a.bin"];
      cmd "touch" [out];
      };

  "project/a.bin" %> \out -> do {
      need ["project/.git/index"];
      cmd "touch" [out];
      };

  "project/.git/index" %> \out -> do{
      cmd "git clone https://github.com/ndmitchell/shake" ["project"];
      };
}
```
And the command

```
$ runhaskell shakefile.hs 
# project/a.bin
# project/.git/index
git clone https://github.com/ndmitchell/shake project
fatal: destination path 'project' already exists and is not an empty directory.
# b.bin
Error when running Shake build system:
* b.bin
* project/a.bin
* project/.git/index
user error (Development.Shake.cmd, system command failed
Command: git clone https://github.com/ndmitchell/shake project
Exit code: 128
Stderr:
fatal: destination path 'project' already exists and is not an empty directory.
)
```

The problem actually as I see it is that  `createDirectoryIfMissing` is called [before](https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Rules/File.hs#L198L199) action has a chance to assert it's dependencies or run `git clone`.

Now I see two solutions to this kind of problem:

- `b.bin` would depend on both `project/.git/index` and `project/a.bin` but really `b.bin` only cares that we have `a.bin`, not how we got there. This method also asserts the sequence of resolving dependencies, ie that `project/.git/index` will be resolved first.
- Clone and build in one go, but maybe cloning succeeds and build fails. That would be quite bad.

Hope all the above made some sense...

**Comment by fakedrake** [comment]
I managed to figure out the `Rules` system. I actually kind of like this solution although it duplicates some code from the internals of shake. @ndmitchell would you be so kind as to review it.

``` haskell
{-# LANGUAGE MultiParamTypeClasses, GeneralizedNewtypeDeriving  #-}
import qualified System.Directory as IO

import Control.Exception
import Control.Monad
import Development.Shake
import Development.Shake.FilePath
import Development.Shake.Rule
import System.Directory
import System.Time
import Data.Time.Clock
import Data.Time.Calendar
import Data.Maybe
import Data.Binary
import Data.Typeable
import Data.Hashable
import Control.DeepSeq

infix 1 $%>, $>

-- Directory rules
newtype DirQ = DirQ FilePath
    deriving (Typeable,Eq,Hashable,Binary,NFData)

instance Show DirQ where
  show (DirQ dir) = "Directory " ++ dir

newtype DirA = DirA Bool
    deriving (Show,Typeable,Eq,Hashable,Binary,NFData)

instance Rule DirQ DirA where
    storedValue _ (DirQ x) = (Just . DirA) <$> IO.doesDirectoryExist x

dirExists :: ShakeOptions -> FilePath -> Action (Maybe DirA)
dirExists opts path = liftIO $ storedValue opts (DirQ path)

($>) :: FilePattern -> (FilePath -> Action ()) -> Rules ()
pattern $> act =
  rule $ \(DirQ path) -> if not $ (pattern ?== path)
                         then Nothing else Just $ do {
  act path;
  opt <- getShakeOptions;
  DirA exist <- fromMaybe (DirA False) <$> dirExists opt path;
  if not exist then error "Failed to create dir" else return $ DirA exist;}

needDir :: [FilePath] -> Action [DirA]
needDir dirs = apply $ map DirQ dirs;


-- Files with dependent dirs
newtype DirFileQ = DirFileQ FilePath
    deriving (Typeable,Eq,Hashable,Binary,NFData)

instance Show DirFileQ where
  show (DirFileQ file) = "Dependent file " ++ file

-- | Just use the modification date for these.
type IntegerTime = (Integer, Integer);
newtype DirFileA = DirFileA IntegerTime
    deriving (Show,Typeable,Eq,Hashable,Binary,NFData)

instance Rule DirFileQ DirFileA where
  -- storedValue :: ShakeOptions -> DirFileQ -> IO (Maybe DirFileA)
  storedValue _ (DirFileQ path) = do {
    exist <- System.Directory.doesFileExist path;
    if not exist then return Nothing else do {
      time <- getModificationTime path;
      return $ Just $ DirFileA (toModifiedJulianDay $ utctDay time,
                                round $ utctDayTime time);
      }}

-- Make sure the file exists.
checkFile :: FilePath -> Action DirFileA
checkFile path = do {
  opt <- getShakeOptions;
  file <- (liftIO $ storedValue opt $ DirFileQ path) :: Action (Maybe DirFileA);
  if isNothing file
  then error $ "File was not created" ++ path
  else return $ fromJust file}

-- |Make a rule for a file but if it's parent directories are missing,
-- don't just make them, look for a corresponding rule.
-- For now we don't fall back to just mkdir-ing but that would be nice.
($%>) :: FilePattern -> (FilePath -> Action ()) -> Rules ()
pattern $%> act =
  rule $ \(DirFileQ path) -> if not $ (pattern ?== path)
                             then Nothing else Just $ do {
  needDir [takeDirectory1 path];
  act path;
  checkFile path;
  }

needLite :: [FilePath] -> Action [DirFileA]
needLite paths = apply $ map DirFileQ paths;

main :: IO ()
main = shakeArgs shakeOptions{shakeVerbosity = Chatty} $ do {
  want ["b.bin"];
  "b.bin" %> \out -> do {
      needLite ["project"</>"a.bin"];
      cmd "touch" [out];
      };

  "project" </> "a.bin" $%> \out -> do {
      cmd "touch" [out];
      };

  "project" $> \out -> do{
      cmd "mkdir" [out];
      };
  }
```

**Comment by ndmitchell** [comment]
I am forever open/closing GitHub issues - just too easy to do!

Looking only at the first comment of these two first (I'll review the code in a few mins), it seems you are almost there. Wouldn't adding `removeDirectory` on the two directories it just created (namely `project` and `project/.git`) solve the issue? Git gets upset if the directory isn't blank, so best make it blank first.

**Comment by ndmitchell** [comment]
I thought of another approach:

    "project/a.bin" %> \out -> do
        cmd "git clone https://github.com/ndmitchell/shake project"

Now Shake creates the directory `project`, but git doesn't mind that as long as its empty. Since you know `a.bin` is in the directory that is safe.

For the second comment, very interesting. You could do the fallback to mkdir by adding:

   priority 0 $ rule $ \(DirQ x) -> Just $ liftIO $ createDirectoryIfMissing True x

Or you might want to do a `DirQ` query of `takeDirectory`, which might fit in better with your principle.

It's certainly an interesting approach, and looks like it could potentially work, if everyone agreed the absence/presence was meaningful. However, I worry it's a bit fragile - most tools treat empty directories as roughly the same as missing directories, so you might get weird things happening.

**Comment by fakedrake** [comment]
> For the second comment, very interesting. You could do the fallback to mkdir by adding:
> 
>     priority 0 $ rule $ (DirQ x) -> Just $ liftIO $ createDirectoryIfMissing True x

Thanks for the tip!

> 
It's certainly an interesting approach, and looks like it could potentially work, if everyone agreed the absence/presence was meaningful. However, I worry it's a bit fragile - most tools treat empty directories as roughly the same as missing directories, so you might get weird things happening.

I agree. I think I will find the `($>)`/`($%>)` combination quite handy in along with `(%>)`. If we were to consider adding the former operators in the main package I guess we could put a big fat warning on the documentation regarding your legitimate concerns. 

Otherwise, while 100 lines of code hardly qualify as a standalone extension to shake, they do provide a nice example of advanced usage, that IMHO shake really really needs. I can put together a blog post about it.

Also, while we are on the subject, beside personal projects, I am using shake in-house at codebender.cc to manage the various javascript packages that implement the various arduino protocols and handle communication between the browser and arduino devices. In case you want to add that to "who uses shake?" at shakebuild.com :)

**Comment by ndmitchell** [comment]
Given the warnings that would be required, I'd prefer to keep these rules out of the main build, unless they do end up being widely used. I suspect someone will want to create a shake-contrib package at some point in future, for rules that aren't big enough to deserve their own package, but are worth sharing - these rules seem perfect for that. More blog posts about the advanced usage of Shake are always appreciated!

Thanks for the note about codebender.cc - I've added them to the Markdown document I generate the website from, and when I regenerate the website (in the next few weeks) they will show up.

**Comment by ndmitchell** [comment]
#170 asks pretty much the same question, so I've turned it into an FAQ and added warnings to the `need` documentation. As part of #431 I'll turn it into an error - the fact `need` works on directories is currently a bug.

**Comment by fakedrake** [comment]
Having used the code I wrote above for a while, probably the biggest problem with the approach (I have fixed a few bugs at this point) is that it is -- as far as my haskell skills can get me -- impossible for `needLite [a]` to compare the current target's modification date to the modification date of `a`.

**Comment by ndmitchell** [comment]
@fakedrake - how do you mean? Are you talking about comparing times on directories? Or do you mean you want to compare in some more powerful way than just `Eq`?
