### ISSUE TITLE
Is using a directory as a rule disallowed

### ISSUE THREAD

**Issue by smurphy8** [ndmitchell/shake#440]
I have several rules that are creating directories.

They worked as of 0.15.5 but stopped working in 0.15.6 with the following error:
``` 
getFileInfo, expected a file, got a directory: 
```
What is the intended behavior?  Should I move my pattern matches on rules to non-directories?

**Comment by Mathnerd314** [comment]
@ndmitchell wrote an [FAQ entry](https://github.com/ndmitchell/shake/blob/master/docs/FAQ.md#q-how-can-i-depend-on-directories), the summary is that directories were mostly broken before and now don't work at all.

**Comment by smurphy8** [comment]
K thanks, I checked around for an update a couple places but missed this.
We adjusted stuff

**Comment by Mathnerd314** [comment]
It's in the changelog near the top: http://hackage.haskell.org/package/shake-0.15.6/changelog

**Comment by smurphy8** [comment]
Lol my eyes skipped right over that.

**Comment by ndmitchell** [comment]
@smurphy8, sorry for the breakage, I never expected it to work, it was just happenstance that it did, and even then, I don't guarantee what "work" meant. I hadn't expected anyone was relying on it, or I would have called it out in the release email.

If rewriting any of the pieces to avoid it is problematic do let me know and I can try and help.

Thanks @Mathnerd314 for the help in my absence.

**Comment by smurphy8** [comment]
We have been talking about ending reliance on it any way because it had odd
behavior.

Thanks!
