### ISSUE TITLE
how do I keep shake running and watch for file changes ?

### ISSUE THREAD

**Issue by rvion** [ndmitchell/shake#441]
Is there a way for me to keep shake running, continuously rebuilding upon file modifications ?

I could re-run shake everytime something change, using an external file monitoring tool, but it seems sub-optimal since shake already knows about the dependency tree.

Am I wrong ?

**Comment by ndmitchell** [comment]
You're not wrong that it would be desirable, but it isn't currently available in any easy form - you might be able to hack it up using the `--live` feature, but it's not going to be particularly pleasant and might stop working if there is a compile error. I'm tracking this request in #371 (which I've just renamed to make it clearer what it does).
