### ISSUE TITLE
Reports seem to be broken

### ISSUE THREAD

**Issue by mjgpy3** [ndmitchell/shake#442]
I'm loving shake, thanks for all the hard work!

From my browser, the reports that are generated (as well as http://hackage.haskell.org/package/shake-0.15/src/html/profile.html) seem to be stuck on "Loading...".

My browser is spitting out:
![image](https://cloud.githubusercontent.com/assets/1709849/14793134/9daa8838-0aeb-11e6-8fee-0bbf56bd29cd.png)

I've tried to open the file using a few different networks. That being said, I may be doing something dumb.

Thanks again for this wonderful tool.

**Comment by ndmitchell** [comment]
So I expect the profile.html in the source release to have references to jquery.js etc. which are not found. The way profiling works is that it takes the template file, then when you run `--profile` (or set `shakeProfile`) it grabs `profile.html` as a template, fills in the javascript files inline, and then saves it. If you do:

    mybuildsystem --profile=new_profile_output.html

Then look for the file `new_profile_output.html` does that one work?

For info, the following page contains more details on profiling: http://shakebuild.com/profiling

**Comment by ndmitchell** [comment]
And I'm glad you are enjoying Shake :)

**Comment by mjgpy3** [comment]
When I open the `new_profile_output.html` locally I get a security error (the as I am seeing for a non-profiled report):
![image](https://cloud.githubusercontent.com/assets/1709849/14797024/867a915e-0afe-11e6-94e1-3e08fd5d7ffb.png)

This is actually not a huge deal because I can manually change the `mode` query param and get to the data I want.

Any thoughts on that error?

**Comment by ndmitchell** [comment]
Which version are you running? I think I fixed that in the most recent version. It was a consequence of Chrome applying a stricter security policy in a later version.

**Comment by ndmitchell** [comment]
Which version of Shake, that is. And fixed in a later version of Shake.

**Comment by mjgpy3** [comment]
Good call! It works perfectly fine on Firefox. My shake version is 0.15.5

**Comment by ndmitchell** [comment]
This was tracked as #305 and got fixed in 0.15.6 which was out a few days ago.

**Comment by mjgpy3** [comment]
Thank you so much!
