### ISSUE TITLE
Add partial version of getEnv

### ISSUE THREAD

**Issue by kaoskorobase** [ndmitchell/shake#443]
This is a suggestion to add a partial version of `getEnv`, because I end up defining it in almost every shake build system; maybe others, too?

Something like

``` haskell
getEnv_ :: String -> Action String
getEnv_ name =
  getEnvWithDefault
    (error $ "Environment variable " ++ name ++ " is undefined")
    name
```

Where `error` probably should be replaced by a more suitable error signalling mechanism.

**Comment by ndmitchell** [comment]
It's somewhat annoying - there is a perfect name for a partial version of `getEnv` and it is exactly `getEnv` just like in the base library. And there's a great name for `getEnv` too, which is `lookupEnv`.

However, for now I suggest just naming this one `getEnvError` - does that seem reasonable?

**Comment by kaoskorobase** [comment]
Why not follow Shake's convention of adding a tick to `Action` versions of library functions with the same name? So there could be `getEnv'`, corresponding to `System.Environment.getEnv` and `lookupEnv'` corresponding to `System.Environment.lookupEnv` (aliased by `getEnv`). In a later release `getEnv` could just be removed.

**Comment by ndmitchell** [comment]
Shake has many conventions - way too many conventions. There's `readFile'` for the `Action` version of that, `doesDirectoryExist` for the `Action` version of that... It's way too inconsistent, and I'm not even sure what my preferred approach is.

**Comment by kaoskorobase** [comment]
Flip a coin? ;-)

Anyway, I'd be happy to see `getEnvError` in Shake regardless of what it's called! A minor convenience of the tick approach is that you can import Shake and base modules without qualifying imports.

**Comment by ndmitchell** [comment]
Rather than flip a coin I thought I'd solicit opinions: https://groups.google.com/d/msg/shake-build-system/8ZWQr2g3XM0/Z_hpQaEFAwAJ

Should that not work, I'll flip a coin :)
