### ISSUE TITLE
Propagate command environment on windows

### ISSUE THREAD

**Issue by fakedrake** [ndmitchell/shake#447]
I am running bash on windows (not the fancy new thing on windows 10, mingw bash) and from there shake. From what I understand it is possible for a command on windows to edit the environment of `cmd`. In my usecase I don't want to make assumptions on how the environment will be changed, I just want the next command to run in that changed environment. Is that possible?

The ideal scenario would be something like

``` haskell
(Environment env, Stdout out) <- cmd Shell (Cwd dir) "path/to/script.cmd" [arg1] [arg2]
-- Do stuff with out
cmd Shell (Cwd dir) (Env env) "env/dependent/command.cmd"
``` 

I would also be happy with running both commands in the same shell even if it means that I can't `Do stuff with out` but I couldn't figure out how to do that either

EDIT: I guess in makefile terms what I want is similar to `.ONESHELL:`
EDIT2: And while we are on the subject it would be nice to optionally get the explicitly set environment variables in the error message when a command fails.

**Comment by ndmitchell** [comment]
Each `cmd` invocation in Shake is separate, so any environment variables don't persist. Assuming you want to treat `script.cmd` as a black box, there are two options:

1. Run both commands in a single go. Something like: `Stdout out <- cmd Shell (Cwd dir) "path/to/script.cmd" arg1 arg2 "&& env/dependent/command.cmd`.
2. Capture the environment from the first command and pipe it into the second. You can capture the environment by running `path/to/script.cmd .... && set`, capturing that with `Stdout`, parsing it, and then supplying it with `Env`.

If you want to reuse the `Env` more than once then the second is probably faster, but both should work.

This is an excellent question, so do you mind if (once we are happy you have what you need) that I transfer it over to StackOverflow under the `shake-build-system` tag? Alternatively, feel free to ask the question on StackOverflow yourself and I'll add this reply, if you want to reflect the "real" question author.

**Comment by fakedrake** [comment]
I wasn't sure if this was going to result in changes in the codebase. Thank you though that worked. Here here is a quick parser for set:

``` haskell
{-# LANGUAGE FlexibleContexts #-}
import Text.Parsec

envEnd :: Stream s m Char => ParsecT s u m ()
envEnd = eof <|> try (endOfLine >> eof)

variableName :: Stream s m Char => ParsecT s u m String
variableName = do
  name <- many1 alphaNum
  char '='
  return name

variableValue :: Stream s m Char => ParsecT s u m String
variableValue = manyTill anyChar $ envEnd  <|> try
  (endOfLine >> lookAhead variableName >> return ())

variable :: Stream s m Char => ParsecT s u m (String, String)
variable = do
  name <- variableName
  value <- variableValue
  return (name, value)

parseEnv :: String -> Either ParseError [(String, String)]
parseEnv = parse (many variable) "Environment dump"
```

A small demo:

```
Œª> parseEnv "abc=hello\ncde=bYe\n"
Right [("abc","hello"),("cde","bYe")]
Œª> parseEnv "abc=hello\ncde=bYe\nt"
Right [("abc","hello"),("cde","bYe\nt")]
Œª> parseEnv "abc=hello\ncde=bYe\nt=yes"
Right [("abc","hello"),("cde","bYe"),("t","yes")]
Œª>  parseEnv ""
Right []
```

And here is the [stackoverflow question](http://stackoverflow.com/questions/37053180/handling-effects-on-the-shell-environment-with-the-shake-build-system)

Also thank you for being so responsive, I really appreciate it.

**Comment by ndmitchell** [comment]
Glad it was nice and easy to solve :). I've attached my answer to the question, and a link to your code.

For reference, I'd have written a far simpler parser as:

    import Data.List.Extra
    parse = map (splitOn "=") . lines

But of course that doesn't have error reporting etc.

**Comment by fakedrake** [comment]
It also doesn't account for multiline values...

**Comment by ndmitchell** [comment]
Ah, true - I don't think I have any on my system, and they are pretty rare, but could be necessary.
