### ISSUE TITLE
Build system usage statistics

### ISSUE THREAD

**Issue by snowleopard** [ndmitchell/shake#449]
Designers of a build system often need to optimise it for the most common use-case, to make life easier for as many people as possible. There is currently no easy way to collect usage statistics in Shake.

What kind of statistics am I talking about? Average build time. Total build time over a particular period. Frequency of using particular command line flags. Targets that get rebuilt most often in real development. How frequently the build system fails. And others.

Can we come up with a non-intrusive, fast, easy-to-implement solution? What comes to mind: a file that is persistently updated after each build: e.g., the command line + the runtime + a short build digest.

If there is such a file then designers of a build system could sometimes ask their users to email them the file for analysis. (Automating this further is probably a bad idea as people may not want their build system to send out any data, even with their explicit consent.)

What do you think?

**Comment by ndmitchell** [comment]
So, I'm skeptical this will be of any real use... It would be fantastic information to have for all users of Hadrian to get these stats, and given the complete aggregated/anonymous data you could really figure out very useful information and improve things. But, the only way you get lots of data is to automatically upload it to a server, and as you say, I don't think anyone will want that. If you are relying on explicit "people sending a file" you're not going to get much data, and the data you get will be atypical and usually associated with a precise bug, in which case profiling output is probably more useful to track it down.

However, if you still want to do that, you can do about 90% of it without any involvement from Shake. Just add `try $ duration $ shakeWithArgs ...` or similar, and then you'll be capturing success/failure and duration. Add in `getArgs` and you have command line info. You can then `appendFile` it to some log.

If I'm wrong and it does turn out to be useful in ways I haven't foreseen adding a `shakeLogFile` option and storing a one-line summary of each build would be a reasonable next step.

**Comment by snowleopard** [comment]
> It would be fantastic information to have for all users of Hadrian to get these stats, and given the complete aggregated/anonymous data you could really figure out very useful information and improve things. But, the only way you get lots of data is to automatically upload it to a server, and as you say, I don't think anyone will want that.

Yep, and that's sad :-(

> However, if you still want to do that, you can do about 90% of it without any involvement from Shake. Just add `try $ duration $ shakeWithArgs ...` or similar, and then you'll be capturing success/failure and duration. Add in `getArgs` and you have command line info. You can then `appendFile` it to some log.

I was thinking about something like this too. Anyway, I wanted to write this down here; perhaps you can come up with something better at some point.

I guess automated sending of aggregated/anonymous data to a server may work well within a company, or in a distributed/cloud build system where some data is being sent anyway.

**Comment by ndmitchell** [comment]
Yep, I am now very tempted to do this collection internally. Would be great data!

**Comment by ndmitchell** [comment]
Closing on the basis it can be done outside the build system just as effectively, and probably more aggressively in internal company settings.

**Comment by ndmitchell** [comment]
BTW, if anyone ever does do this, I'd be keen to know what they did exactly, and how valuable the data was.
