### ISSUE TITLE
Space leak in QuickCheck test

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#450]
The error:

    shake-test: Stack space overflow: current size 33568 bytes.

Reducing the number of QuickCheck tests to 500 makes it pass.

**Comment by jacereda** [comment]
Forgot to say that I'm building with ghc 8 in case it matters.

**Comment by ndmitchell** [comment]
Does stubbing out the property still fail? Eg could it be a Mac specific QuickCheck bug? To stub out properly you would need the same type and some kind of deep seq to force the input.

**Comment by jacereda** [comment]
Do you mean something like this?

    Success{} <- quickCheckWithResult stdArgs{maxSuccess=1000} $ \(Pattern p) (Path x) -> p `deepseq` x `deepseq` (property True)

That passes with -K1K

**Comment by ndmitchell** [comment]
Can you reinstate the property but print p and x before so we can see which value it fails on.

**Comment by jacereda** [comment]
With `print (p,x)`, this is the last pair printed:

    ("b*\\/**ab//b\\\\\\b\\a\\b*\\b/baab\\b/*a///\\b\\\\/b/*/aaaa*b/b\\b\\\\a\\*bb/*a//\\///\\/**bb\\/aab//\\\\\\**","\\\\/baa\\/ab\\a/\\ab\\a\\/\\aaa///\\ab///\\a\\bb/b\\a/\\/\\/\\///a\\abbb/\\/ab\\//baab/\\\\//a\\a\\a\\//b\\/b\\\\\\/\\/")

**Comment by jacereda** [comment]
I have reduced the problem to:

    Success{} <- quickCheckWithResult stdArgs{maxSuccess=1000} $ \(Pattern p) (Path x) -> label "foo" True

**Comment by jacereda** [comment]
Changing `label "foo" True` to `property True` terminates properly. I guess it's normal since quickcheck is collecting those labels. Isn't reducing `maxSuccess` to 500 an option here? Would be good to know why you don't get this same error though...

**Comment by ndmitchell** [comment]
If you change it to `\(p :: Double) (x :: Double)` do you still get the overflow? What version of QuickCheck are you using?

**Comment by ndmitchell** [comment]
Reducing maxSuccess to 500 is certainly an option, but I'd like to understand what's causing it first. It seems _something_ has a space leak, and from where you are getting to, that something is looking increasingly like QuickCheck, and thus would be good to fix upstream.

**Comment by jacereda** [comment]
QuickCheck version is 2.8.2, but I found the reason.
I was building with `stack test --profile`. As soon as I changed my build command to `stack test` the problem disappeared.
Is there some way to detect profiling in cabal so a larger stack can be used there?

**Comment by ndmitchell** [comment]
Thanks, I'll try and reproduce later. If profile is the culprit it's probably a space leak in QC that gets fixed by optimisation. Should still be quite easy to track down and fix.

**Comment by ndmitchell** [comment]
OK, I can reproduce this in QuickCheck alone, so nothing to do with Shake. Will track it down there.

**Comment by ndmitchell** [comment]
Space leak diagnosed and patched, pull request at https://github.com/nick8325/quickcheck/pull/93.

**Comment by ndmitchell** [comment]
My thoughts are if this gets patched quickly, do nothing to Shake, if not, remove the `label` call until a release is made.

**Comment by jacereda** [comment]
Great, thanks.

**Comment by ndmitchell** [comment]
In fact, no point even leaving this open. The `label` coming out of QuickCheck is of marginal interest at best. Next time I care what the value is I'll reenable it, but until then we can leave it off.
