### ISSUE TITLE
sleepFileTimeCalibrate takes too long

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#451]
Starting a single test is quite slow. Wouldn't it be better to just use `sleepFileTime` with something "safe" (1.5 or 2 secs?).

**Comment by ndmitchell** [comment]
On my machine sleepFileTime calibration takes a fraction of a second. What time is your sleep time calibrated to? Not doing the calibration massively slows down the full test run.

**Comment by ndmitchell** [comment]
On Linux it calibrates to 6ms.

**Comment by jacereda** [comment]
Calibration took 9.836575s. Longest file modification time lag was 1007ms

**Comment by jacereda** [comment]
The machine is 7 years old iMac, but I would attribute that to the OS. I'll test later with a newer MacBook.

**Comment by jacereda** [comment]
Same on MacBook with ghc 7.10.3:

    Calibration took 9.614034s. Longest file modification time lag was 1005ms

**Comment by ndmitchell** [comment]
Are Mac timestamps only to the nearest second? What is the filesystem you are using? If that really is correct we can do something like in calibration if the first is > 0.5s then default to 1.5s or something. But if it's just a bug in the code failing to get the high res timestamps that would be far better to fix.

**Comment by jacereda** [comment]
I don't think so, most probably utime() is used where utimes() should be used. I've been grepping ghc sources and there're FFI calls to both APIs. Probably some incorrect conditional is making the OSX version use the former.

**Comment by ndmitchell** [comment]
Thanks. I'll check exactly where I am expecting it to come from and let you know... Perhaps the UNIX package, at a guess.

**Comment by jacereda** [comment]
I have written a small C test and UNIX is innocent. utimes() ignores the tv_usec field.

**Comment by ndmitchell** [comment]
I'm use the `unix` library to call `getFileStatus` then I extract `modificationTimeHiRes`. The code is at 
https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/FileInfo.hs#L152-L164. Not sure what that corresponds to, I was expecting a `stat` call.

**Comment by jacereda** [comment]
Looks like stat() is the culprit. I get 0 for the `st_mtimensec` or `st_mtimespec.tv_nsec` fields.

**Comment by ndmitchell** [comment]
So that's a bug in where? Mac OS itself? Seems a bit surprising...

**Comment by jacereda** [comment]
This prints 0 for any file you throw at it:

```
#include <sys/stat.h>
#include <stdio.h>

int main(int argc, char **argv) {
  struct stat st;
  stat(argv[1], &st);
  printf("%ld\n", st.st_mtimespec.tv_nsec);
  return 0;
}

```

**Comment by jacereda** [comment]
Same happens when defining _POSIX_C_SOURCE and using `st_mtimensec` field instead.

**Comment by jacereda** [comment]
Not sure if this is the relevant piece of code:

http://opensource.apple.com//source/xnu/xnu-1228.15.4/bsd/hfs/hfs_attrlist.c

But if it is, `tv_nsec` fields are zeroed in all cases.

**Comment by ndmitchell** [comment]
I've pushed some code to only run the calibration twice. In reality I double the calibrated value and cap it at 1s anyway, so I don't think 2 measurements will matter. Note however that one measurement would be problematic, since I might start measuring at 0.99s and stop at 1s and conclude an accuracy of 0.01s.

I'd love to have higher precision timestamps on Mac OS, but looking at http://stackoverflow.com/a/9543891/160673 it suggests HFS doesn't store them.

**Comment by jacereda** [comment]
https://en.wikipedia.org/wiki/HFS_Plus

> 
> Examples of modern file-system features not supported by HFS+:
> 
> nanosecond timestamps
>

**Comment by ndmitchell** [comment]
Yep, so it seems HFS+ doesn't support subsecond timestamps, and that's known and expected. Certainly a surprise to me!

With the tweak to calibration it should only delay starting tests by an average of 1.5s, so hopefully that's liveable. Do you agree?

**Comment by jacereda** [comment]
I was as surprised as you. I just hope they'll realise we're in the 21st century at some point and change the filesystem...

Sure, 1.5 is great compared to what I get now :-)
