### ISSUE TITLE
Use a different serialization library

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#458]
I recently read two papers on Shake: the initial one and the one about shaking up GHC. In both it's mentioned that serialization could be improved by switching to a different library. I don't know whether it's still an issue or not. But if so, have you looked into using the following lib?
https://github.com/well-typed/binary-serialise-cbor
I've heard good things about it, but I don't have any hands-on experience.

Ah, I've just found this issue:
https://github.com/ndmitchell/shake/issues/86
But it's from 2013, so lots of things might have changed since then.

**Comment by Mathnerd314** [comment]
This was mentioned in #453; currently Neil wants to use his own API. If you run https://github.com/fpco/serial-bench, you will see that even binary-serialise-cbor adds a huge encode/decode overhead.

I've been designing my own API, based on those results; it's going OK.

**Comment by ndmitchell** [comment]
Yep, my plan is use a to and from ByteString function, on the basis it removes all overhead - then I can write the internal functions using raw Ptr manipulations (should be the absolute fastest) and people building on top of Shake can either write their functions by hand, or use one of the new faster libraries people are currently working on.

Binary CBOR was the original plan for a long time, but it's still very overhead-full.

**Comment by ndmitchell** [comment]
I'm now about 80% of the way through switching to a different serialisation library. Results so far show time to load the database has dropped somewhere between 5x and 10x, so a nice speedup already.

**Comment by Mathnerd314** [comment]
I still like the store package (and its Peek / Poke monads); using `ByteString -> a` and `a -> Builder` doesn't compose.

**Comment by ndmitchell** [comment]
I entirely agree! If dependencies were no issue I'd have gone for Store. As it is, the number of lines of serialisation code is sufficiently short that it doesn't matter for Shake and I won't expose it to the user. My one also allows the trick of not copying the ByteString when loading, which reduces memory allocation and fragmentation.

**Comment by ndmitchell** [comment]
With the current code we're on a different serialisation approach, so all done. It's very low-level and not at all compositional, but I'm not convinced that's a problem (the things I wrote using it were pretty simple).
