### ISSUE TITLE
List the phony targets

### ISSUE THREAD

**Issue by fakedrake** [ndmitchell/shake#462]
Phony targets are in my workflow the only entry points to the build system. I am not really sure how doable this is but it would be a great first step towards tab completion.

**Comment by ndmitchell** [comment]
Great idea! We're already tracking this at at #107, including the idea of doing tab completion, so I'll close this bug and suggest you subscribe there. Designing and coding of exactly how to wire this information through is currently ongoing, mostly as part of #453.
