### ISSUE TITLE
Use a better-matching wildcard rule if there are overlapping ones

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#468]
I have some rules that look like this:

```
dir <> "//*.c.o" ...
dir </> subDir <> "//*.c.o" ...
```

Given a file like `dir/subDir/foo.c.o`, I expected the second rule to match automatically, but Shake (0.15.5 at least) refuses to do anything, complaining about overlapping rules (without listing them, see #143). (I worked around this with `priority 2`).

Is this done intentionally, to prevent mistakes when designing a build system? I'm new to Shake, so I don't have an opinion on this. I guess it's better to be safe than sorry. On the other hand, I wonder whether it could lead to excessive use of `priorities` in complex build systems.

**Comment by ndmitchell** [comment]
It's deliberate - absolute patterns are considered more precise than wildcard patterns, but other than that, you can't have two duplicates. The options are to use priority, or use `?>` for the first with a rule that can't match `subDir`. Another option is to use `alternatives`, which takes order of patterns into account.

You certainly could define rules which measure how "precise" any given pattern is, but I've seen CSS go that way, and it makes things horribly complex and fairly unpredictable. In the past I've used `?>`, but my current inclination is probably towards `alternatives` and have the alternatives scope over as few rules as possible.

**Comment by nkaretnikov** [comment]
Okay, I'm closing this issue, then.

**Comment by ndmitchell** [comment]
I think the advice on here is probably better than that in the FAQ at http://shakebuild.com/faq#can-file-patterns-overlap, so I should copy some of the notes there.

**Comment by ndmitchell** [comment]
I think the advice on the website is pretty good actually - I moved all the nasty details in the Haddock.
