### ISSUE TITLE
The -s flag prints the output of shakeTimings

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#469]
In 0.15.10 the help string near `-s` says "Don't print anything," which is clearly not the case when `shakeTimings = True` is used.

**Comment by ndmitchell** [comment]
But `--timings` which sets `shakeTimings` says `Print phase timings.` - one of them has to win, and one has to be ignored. I don't really have a preference which one gets ignored - certainly `-s` could also disable `shakeTimings`, but I'm not sure people would expect that behaviour?

**Comment by ndmitchell** [comment]
I don't think either behaviour is strictly superior, so leaving it as since that is least work.

**Comment by ndmitchell** [comment]
On further thought, I think silent should take preference, since it does for everything else.

**Comment by ndmitchell** [comment]
Fixed.
