### ISSUE TITLE
Pool test is flakey

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#479]
@nomeata reports that a build of shake-0.15.10 on Debian failed:

```
## TESTING pool
TESTS FAILED
shake-test: ASSERTION FAILED: failed in ===
LHS: (3,0)
RHS: (5,0)
Test suite shake-test: FAIL
```

From https://buildd.debian.org/status/fetch.php?pkg=haskell-shake&arch=amd64&ver=0.15.10-1%2Bb1&stamp=1468409225&file=log

**Comment by ndmitchell** [comment]
Looking at the code, it spawns 5 threads, then expects there to be a 0.01s gap they are all running. That's a very tight gap! I've adjusted the code to a 0.1s gap, but really need to think about what I'm doing here and come up with more robust tests.

**Comment by Mathnerd314** [comment]
I think you want a barrier in the individual threads, instead of a wait, and then a special controller thread that releases the barrier.

**Comment by ndmitchell** [comment]
I thought about that - but for one case I'm looking to spawn 6 threads in pool, wait for 5 to meet at the same time, but want to allow the 6th to meet too if it is being run simultaneously, but I really hope it isn't.  I don't see any way to check for that condition without a sleep.

That said, I could certainly make it more robust, and make it only give false-negatives - and certainly should.

**Comment by ndmitchell** [comment]
I've done nice robust waits for all but the first test. That really does need to have time based meet since I don't want the final one to be penalised for being slow - if it ever meets it will be a failure. Unfortunate, but its now 10x more tolerant.
