### ISSUE TITLE
Document how exceptions should be raised

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#481]
Would be nice to see this mentioned somewhere in the haddocks. After looking through the mailing list and issues, I settled on using `error` inside `Rules`. But this has the following disadvantages:
- Error messages are not prefixed with the word "error", so it's easy to miss them.
- It's implicit, so there doesn't seem to be a way to structure the program around that, I think.

What I'd really like is a way to add an error to a list of errors and output them all after processing all the rules. Something like `Either [String] (Rules ())`, which wouldn't require me to propagate the error state to the `main` function to call `error` on the `Left` value there.
Another issue with this particular type is that it makes impossible (or just harder?) to work with `liftIO` because there's no instance for `Either [String]`.

Is there anything like this? If not, any ideas how to make it work?

**Comment by ndmitchell** [comment]
I expect a lot of error calls inside `Action`, and there you can use `error` or `liftIO $ throwIO` or `fail` - I deliberately make it work with everything. I've now documented that.

I don't really expect a lot of calls to error inside `Rules`, so it's not as set up for that. I would think about defining your build system around `IO (Rules ())` or `Either [String] (Rules ())`. If you do that you can track errors that occur inside Rules before calling into Shake, so you essentially build the `Rules ()` with whatever exception mechanism and behaviour suits you, then only if there are no errors do you call on to Shake. You would have to propagate the error state upwards, but I think using the right monad transformers that probably all becomes quite clean.

**Comment by ndmitchell** [comment]
Documented how errors should be raised. I don't think there's much to do in the Rules monad, so closing.
