### ISSUE TITLE
Print command timings

### ISSUE THREAD

**Issue by feuerbach** [ndmitchell/shake#483]
This seems like an obvious feature, yet I can't figure out if it's there and how to enable it. All I want is `--trace` plus the timing of each command.

I tried `--timings`, but it prints shake's internal timings, not the rules/actions timings.

I also tried `-r`, but:

* it's not generated until the build is over
* it shows all the historic timings, while I am interested in the specific run that is happening right now

**Comment by ndmitchell** [comment]
Are you after timings on each rule when it completes? Or timings of the command line executions?

You can restrict `-r` to active timings with `run(0)` in the filter, but it's still quite a different thing to what you seem to be after.

**Comment by feuerbach** [comment]
Command, I think.

Basically, every line printed by `--trace` followed by a duration.

**Comment by feuerbach** [comment]
... although timings for rules would be a useful addition, too!

**Comment by ndmitchell** [comment]
Hmm, interesting idea - certainly everything which says traced already has a valid time.

Out of curiosity, what's the desire for this feature? To do rough and ready profiling? To understand progress?

**Comment by feuerbach** [comment]
Yeah, I guess this doesn't make so much sense if you consider a build system, where most individual commands are instantaneous. But I am using Shake as a driver for a bioinformatics pipeline, where a single command takes (in my case) from several minutes to 22 hours.

So, it'd be useful to have a sense of how long each particular command takes without navigating through the report.

**Comment by ndmitchell** [comment]
You can write that yourself on top of `cmd`, as I did in bake, see https://github.com/ndmitchell/bake/blob/0ca31272e80c23fba3641e9d2f32feca4b2223f9/src/General/Extra.hs#L131, which reads:

```time :: IO (CmdLine, CmdTime, a) -> IO a
time act = do
    (CmdLine msg, CmdTime tim, res) <- act
    tot <- logTime
    putStrLn $ "[BAKE-TIME] " ++ showDuration tim ++ " (total of " ++ showDuration tot ++ "): " ++ msg
    return res
```

So I just write: `time $ cmd "whatever"`, and it prints out duration at the end and the command line.

**Comment by feuerbach** [comment]
Fair enough. Thanks!
