### ISSUE TITLE
SERIOUS: Parallel and par don't track dependencies

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#488]
Given:

```
readFile' "a" `par` readFile' "b"
```

That won't introduce a dependency on either `a` or `b`. The underlying bug is in the parallel function - it should be taking the pieces from the local state of the computations and applying them back to the caller, but it doesn't.

Needless to say, very serious, and probably deserves a backport.

**Comment by matthiasgoergens** [comment]
Ha, I stumbled on that one recently, too.  I replaced all my forP with for_.  It's good to see the bug's already raised.

**Comment by ndmitchell** [comment]
Fixed in HEAD with a test. Now need a backport.

**Comment by ndmitchell** [comment]
I backported this to 0.15 and released 0.15.11 with the fix included.
