### ISSUE TITLE
Commands running concurrency with a Cabal build aren't reaped until the cabal build finishes

### ISSUE THREAD

**Issue by enolan** [ndmitchell/shake#490]
I have a Shake based system where the component written in Haskell is built by calling into Cabal (which in turn runs GHC) and the other components are build with `cmd`/`command`. While the Cabal build process is running, some (maybe all?) of the other processes don't get reaped until it finishes. Here's a Setup.hs to show what I mean:

``` Haskell
import Development.Shake
import Development.Shake.FilePath
import Distribution.Simple
import Distribution.Simple.Build
import Distribution.Simple.LocalBuildInfo
import Distribution.Simple.Setup

main = defaultMainWithHooks $ simpleUserHooks {buildHook = myBuildH}

myBuildH pkgdesc lbi userhooks buildFlags =
  shake shakeOptions {shakeThreads = 0} $ rules pkgdesc lbi buildFlags

rules pkgdesc lbi buildFlags = do
  let buildPref = fromFlag $ configDistPref $ configFlags lbi
      exePath = buildPref </> "build" </> "shaketest" </> "shaketest" <.> exe
  want $ [exePath] ++ map ("out-" ++) (map show [1..50])
  exePath %> \_ -> do
    hsFiles <- getDirectoryFiles "" ["src" <//> "*.hs"]
    need hsFiles
    traced "haskell compile" $ build (localPkgDescr lbi) lbi buildFlags []
  "out-*" %> \p -> do
    cmd "echo Hello" p (FileStdout p)
```

The `echo` processes stay in zombie state until GHC is done, and no other rules fire until they get reaped. I made a test case repo: https://github.com/enolan/shake-zombies

To reproduce (on Linux at least):
- clone the repo
- `stack build`
- in another terminal: `ps ax|grep echo`

You should see a bunch of lines like `6540 pts/19   Z+     0:00 [echo] <defunct>`. It's inconsistent in how many.

Any ideas? Adding `{-# OPTIONS_GHC -threaded #-}` doesn't help. I don't know enough about Shake's parallelism system to debug this.

**Comment by ndmitchell** [comment]
Hmm, weird - I've been developing Shake on Windows, so I'm not sure if I'd have seen this even if it had been occurring. Which version of the `process` library are you building Shake with? If you switch from running `echo` with `cmd` to using something in `System.Process`, e.g. `readProcess`, does that fix the zombies or not?

**Comment by enolan** [comment]
Figured it out. From the `process` docs:

> GHC Note: in order to call waitForProcess without blocking all the other threads in the system, you must compile the program with -threaded.

`cabal-install` builds `Setup.hs` files with `-threaded` but `stack` doesn't. If you set `-threaded` in `OPTIONS_GHC` it's ignored.

I'm not sure why this problem doesn't occur with long running commands spawned from `cmd`. Does Shake have some trick for waiting on spawned processes without blocking the build process?

A warning to the effect of "You must pass `-threaded` to GHC when building your Shake executable if you spawn processes outside of Shake's `cmd`/`command` infrastructure, or you will get no paralellism." would be good for the next guy.

**Comment by ndmitchell** [comment]
`-threaded` is a link time option, and while link time options can be set on individual files (with `GHC_OPTIONS`) they are ignored - they have to be set in cabal or the command line when linking.

I am somewhat surprised though - I've written many build systems without `-threaded` that run multiple processes in parallel just fine (`-threaded` used to segfault with Shake, so it was unavoidable). That said, I've now updated everywhere (user manual etc) to say use `-threaded`, as that should be the default on GHC 7.8 and above, so fixes your issue.
