### ISSUE TITLE
Lint error with multiple-output build rules

### ISSUE THREAD

**Issue by snowleopard** [ndmitchell/shake#496]
Let me create a separate issue here, so that [my comment](https://github.com/ndmitchell/shake/issues/296#issuecomment-255193248) is not lost.

Consider the following build system:

``` haskell
import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions { shakeFiles="_build"
                              , shakeChange = ChangeModtimeAndDigest } $ do
    want ["A1-plus-B"]

    "A1-plus-B" %> \out -> do
        a1 <- readFileLines "A1"
        b  <- readFileLines "B"
        writeFileLines out $ a1 ++ b

    ["A1", "A2"] &%> \[o1, o2] -> do
        writeFileLines o1 $ ["This is", "A1"]
        writeFileLines o2 $ ["This is", "A2"]

    "B" %> \out -> do
        writeFileLines out $ ["This is", "B"]
```

If I delete `A2` after a successful build, I get the following lint error in the subsequent rebuild:

```
Lint checking error - value has changed since being depended upon:
  Key:  A1
  Old:  File {mod=0x49DEEABD,size=0xD,digest=0x5136A886}
  New:  File {mod=0x4D5CA3FF,size=0xD,digest=0x5136A886}
```

Am I using multiple-output rules incorrectly? This happens in Hadrian, see https://github.com/snowleopard/hadrian/issues/216 and https://github.com/snowleopard/hadrian/issues/291.

**Comment by ndmitchell** [comment]
I rewrote the file rules, and the linting, and the bug has gone away. I added your example as a test though - thanks for the small test case.

**Comment by snowleopard** [comment]
Awesome, thanks!
