### ISSUE TITLE
command/cmd with quotes

### ISSUE THREAD

**Issue by mchaver** [ndmitchell/shake#497]
I can't seem to get Shake to handle quotes properly. Some command line flags expect things to be quoted. If Shake can already handle this properly then it would be nice to mention this in the manual.

#### Haskell

```Haskell
(Stdout diffUntrimmed) <- command [] "diff" ["-r", pPath, (buildDir </> target), "-x", "*.js_hi",  "-x", "*.js_o", "-x", ".*"]
```

#### Output

```
diff -r ../dir _builds/dir -x *.js_hi -x *.js_o -x .*
```

#### Haskell

```Haskell
(Stdout diffUntrimmed) <- command [] "diff" ["-r", pPath, (buildDir </> target), "-x", "\"*.js_hi\"",  "-x", "\"*.js_o\"", "-x", "\".*\""]
```

#### Output

```
diff -r ../dir _builds/dir -x '"*.js_hi"' -x '"*.js_o"' -x '".*"'
```

#### Haskell

```Haskell
(Stdout diff) <- command [] "diff" ["-r", source, (buildDir </> target), "-x", "'*.js_hi'", "-x", "'*.js_o'", "-x", "'.*'"]
```

#### Output

```
diff -r ../dir _builds/dir -x ''\''*.js_hi'\''' -x ''\''*.js_o'\''' -x ''\''.*'\'''
```

#### Haskell 

```Haskell
(Stdout s) <- cmd Shell "diff -r ../dir _builds/dir -x '*.js_hi' -x '*.js_o' -x '.*'" :: IO (Stdout String)
```

#### Output

```
Command: diff -r ../dir _builds/dir -x '"*.js_hi"' -x '"*.js_o"' -x '".*"'
```

None of the outputs work because `diff` needs to look like this:

```
diff -r ../dir _builds/dir -x "*.js_hi" -x "*.js_o" -x ".*"
```

**Comment by mchaver** [comment]
For this particular case I was able to work around the issue by using `--exclude` because it allows for non-quoted arguments. Also, for `diff`, you need to look at the `Exit` value.

```
(Exit diffCode) <- command [] "diff" ["-r", source, target, "--exclude=*.js_hi",  "--exclude=*.js_o", "--exclude=.*"]
```

However, I would still be curious if there is a way to handle double quotes.

**Comment by ndmitchell** [comment]
Is this Windows or Linux? If Windows, which diff are you using? If you add
the Shell CmdOption does that work?

On Linux there is no notion of "quoted arguments" since I send the
arguments directly into the argv[] array, so in effect the command line is
quoted, or at least not expanded by the shell. On Windows I build a quoted
string, but there I think I quote everything. The command doc doesn't
really mention where quotes go because they are not necessary on Linux.
>
>

**Comment by mchaver** [comment]
This is on Linux (Ubuntu 16.04).

Here is a quick example to show the difference in quote behavior:

```
$ mkdir diff-test
$ mkdir diff-test2
$ touch diff-test/test.txt
$ touch diff-test2/.hidden-file.txt
$ diff diff-test diff-test2
Only in diff-test2: .hidden-file
Only in diff-test: test.txt
```

This works ok (ignore ".txt" files)
```
$ diff diff-test diff-test2 -x "*.txt"
Only in diff-test2: .hidden-file
$ diff diff-test diff-test2 -x *.txt
Only in diff-test2: .hidden-file
```

This breaks without quoting (ignore hidden files)
```
$ diff diff-test diff-test2 -x ".*"
Only in diff-test: test.txt
$ diff diff-test diff-test2 -x .*
diff: extra operand '..'
diff: Try 'diff --help' for more information.
```

**Comment by ndmitchell** [comment]
You certainly get a different quote behaviour on the command line, but if you run those through `command` do you see a difference? I would expect `command ["diff","diff-test","diff-test2","-x",".*"]` to have the same behaviour as the final example you gave, even though there are no quotes in the command line. Essentially the quotes are effecting what argv is being passed in, and I'm building the argv directly, so don't need to quote shell wildcards.

**Comment by mchaver** [comment]
Ah, I see that now. I think I was getting confused because of the way `diff` works. If the dirs are the same it returns exit code 0 and no text. If the dirs are different then it return exit code 1 and some text. If it tries to compare a non-existing dir, then it returns exit code 2 and some text.

```Haskell
λ> (Exit x) <- cmd "diff diff-test diff-test2 -x .*" :: IO Exit
Only in diff-test: test.txt
λ> x
ExitFailure 1
λ> (Exit x) <- cmd "diff diff-test diff-test2" :: IO Exit
Only in diff-test2: .hidden-file
Only in diff-test: test.txt
λ> x
ExitFailure 1
λ> (Exit x) <- cmd "diff diff-test diff-test2 -x .* -x *.txt" :: IO Exit
λ> x
ExitSuccess
λ> (Exit x) <- cmd "diff diff-test unknown-dir" :: IO Exit
diff: unknown-dir: No such file or directory
λ> x
ExitFailure 2
```
