### ISSUE TITLE
Handle symlinks to directories

### ISSUE THREAD

**Issue by matthiasgoergens** [ndmitchell/shake#498]
First, thanks for Shake!  I am replacing some old and crufty agglomeration of Makefiles and OMakefiles and worse, and it's going splendid.

But for this project I need a symlink to a directory to be created.  I had hoped to do something like this:

symlink %> createSymLink' from symlink

Alas, my 'from' is a directory, so shake doesn't like this at all.

The usual workaround for depending on directories, ie depending on a file inside the directory doesn't work: shake will just create a new empty directory where the symlink should be..

Any chance of fixing this, please?  (I would contribute a patch, but I have to properly figure out the open source policy of my new employer first..)

**Comment by ndmitchell** [comment]
So you want to depend on a directory? See this FAQ: http://shakebuild.com/faq#how-can-i-depend-on-directories - it's generally not a good idea.

Why not have an action, which is always run, along the lines:

```
action $ unlessM (doesDirectoryExist symlink) $ createSymLink' from symlink
```

(I am also still figuring out the open source policy of my new employer)

**Comment by matthiasgoergens** [comment]
Oh, I want to depend on a symlink as a symlink, not as a directory. (Ie,
don't dereference, just treat it as an opaque thing.)

I'll have a look at the FAQ entry you mentioned, and will try the
workaround you suggested.

**Comment by averagehat** [comment]
Does allow rules for symlinks at all? It seems it doesn't? I can't find any documentation on this.

**Comment by ndmitchell** [comment]
A comment (since deleted) asked about symlinks in general. The answer is Shake doesn't really handle them at all - worth calling out in the docs.

**Comment by ndmitchell** [comment]
I've released safe-0.3.12 with this included.

**Comment by ndmitchell** [comment]
Commenting on entirely the wrong ticket!

**Comment by ndmitchell** [comment]
Directories are special, and that's now called out. However, symlinks aren't special, and all the normal stuff should work with them fine, so nothing to say.

**Comment by matthiasgoergens** [comment]
Thanks. I also managed to change the way we build so we don't need to track that symlink any more.
