### ISSUE TITLE
Expose Filepatterns Module

### ISSUE THREAD

**Issue by matthiasgoergens** [ndmitchell/shake#499]
I have a bunch of files where "prefix_*.extension" gets build from "another_prefix_*.another_extension".  It would be really handy to capture what the * matched.  And the Filepatterns module has exactly that `extract` function already.  Can we please expose it, or even the entire module?

Ideally, I'd want something like the following:

    [`"prefix_*.cpp", "prefix_*.h"] *&%> \([cpp, h], [cppAsterisk, hAsterik]) -> do
        someCommand (cppAsterik <.> xml)

But just exposing `extract` would already be a great bonus.

Thanks!

**Comment by ndmitchell** [comment]
Is https://github.com/ndmitchell/shake/issues/485 what you are after?

**Comment by matthiasgoergens** [comment]
Looks pretty much like what I want. Thanks!

Yes, thinking about the right API is the hard part.

I am usually not quite as happy with partial pattern matches as I am with
shake---because when shake fails as shake-runtime its compile-time for the
code I am actually interested in.

So I'd be reasonably happy with an API were the types don't do too much
work, just like the rest of shake.

**Comment by ndmitchell** [comment]
See also https://stackoverflow.com/questions/44799038/usefull-functionlity-hidden-away-in-development-shake-filepattern-hs

**Comment by nesqi** [comment]
If Shake already depends on TempalteHaskell, I would like a type-safe solution (with regard to arity) where you do not have to redefine (error prune) the matching pattern within the action.

If Shake does not depend on TemplateHaskell, it feels overkill to add that dependency. In that scenario I don't see how you could type-check without changing the type of FilePattern to something non-backward-compatible. So, personally I would have just exposed extract instead.

The perfect solution would be something like

    "build/year-" <*> "-loc-" <*> ".json" !> \(out, (year, loc)) -> buildJSONFor year loc

that is type-checked. But I'm not sure it's worth it.

**Comment by ndmitchell** [comment]
I exposed a safe version of extract:

```
-- | Like '?==', but returns 'Nothing' on if there is no match, otherwise 'Just' with the list
--   of fragments matching each wildcard. For example:
--
-- @
-- 'filePattern' \"**\/*.c\" \"test.txt\" == Nothing
-- 'filePattern' \"**\/*.c\" \"foo.c\" == Just [\"",\"foo\"]
-- 'filePattern' \"**\/*.c\" \"bar\/baz\/foo.c\" == Just [\"bar\/baz/\",\"foo\"]
-- @
--
--   Note that the @**@ will often contain a trailing @\/@, and even on Windows any
--   @\\@ separators will be replaced by @\/@.
filePattern :: FilePattern -> FilePath -> Maybe [String]
```

Is that sufficient?

@nesqi, it seems that #485 is going in that general direction?

**Comment by nesqi** [comment]
Nice, big improvement! Accessing the matching functionality is the important stuff. Defining new operators that reduce boilerplate is secondary and could be done separately.

Thanks!

**Comment by ndmitchell** [comment]
I'll let people play around with filePattern and figure out things after.

**Comment by ndmitchell** [comment]
I forked the entire library into https://github.com/ndmitchell/filepattern and rewrote it a lot. If you want file pattern functionality, there's a good place to go. As part of #551 I'll be switching Shake to use it.
