### ISSUE TITLE
withResource/need should be an error

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#504]
```
withResource res 1 $ do
    need ["test.extra"]
```

That's meant to raise an error, but it doesn't. Spotted by https://github.com/snowleopard/hadrian/issues/295

**Comment by Mathnerd314** [comment]
Couldn't `need` just release the resource temporarily?

**Comment by ndmitchell** [comment]
Could do... I guess if it does that the semantics of `withResource res 1 $ foo >> bar` could be considered equivalent to `withResource res 1 foo >> withResource res 1 bar` - and keeping the resource is just an optimisation. I do wonder if that means some resources don't work though - if people are using them more like locks, or there is a `withResource res 1 $ do acquire; use; release` pattern.

**Comment by Mathnerd314** [comment]
Throttles don't really fit that semantics, since they aren't really releasable to begin with. But finites are indeed just like locks.

**Comment by ndmitchell** [comment]
The check and test got added as #32, during 0.10.7 - and I can't reproduce. I've no idea why Hadrian didn't run into an error.

**Comment by snowleopard** [comment]
See my comment [here](https://github.com/snowleopard/hadrian/issues/295#issuecomment-269842476), explaining why Hadrian didn't run into an error.

**Comment by ndmitchell** [comment]
`withResources` is really just a sequence of `withResource` calls, so that makes a lot of sense.
