### ISSUE TITLE
Suggestion for running build process

### ISSUE THREAD

**Issue by SamTay** [ndmitchell/shake#505]
I noticed in the demo and tutorial that there is an intermediary `build.sh` that compiles the `Build.hs` into the `./_build/` directory. I was wondering why this is felt necessary. I think it is a bit confusing, especially having to execute a .sh file with stack, via `stack exec ./build.sh`.

I would suggest changing this proess to just use the [script interpreter](https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter) capabilities native to stack. That is, remove `build.sh`, elevate executable permissions on `Build.sh`, and add the shebang and stack directives to `Build.sh`:
```haskell
#!/usr/bin/env stack
-- stack runghc --resolver lts-7 --install-ghc --package shake

import Development.Shake
-- ... rest of file is the same
```

Now, we get to remove `build.sh` and we just run the build process via `./Build.hs` (or `stack Build.sh` on non-Unix systems).

Let me know what you think. I can send a PR for docs if desired.

**Comment by ndmitchell** [comment]
I don't really want Shake to "pick" either stack or cabal, and the current approach was about the best I could find that targets both. I'm also keen not to have to go in and patch to `lts-8` etc as each new `lts` arrives. That said, if you rely on `cabal` sandboxing the thing probably doesn't work either... It's a bit of a mess trying to permit both so giving up might be the easiest way out.

**Comment by SamTay** [comment]
I see, makes sense. The above approach might be worth mentioning for the stack users, but I suppose it's pretty easy to figure out. I'll close out, thanks.
