### ISSUE TITLE
Error during `stack install shake`

### ISSUE THREAD

**Issue by alx741** [ndmitchell/shake#510]
`stack install shake` fails with the following message: http://pastebin.com/6kfKLW9T
Specifically:

```
    Declaration for duration2
    Unfolding of duration2:
      Can't find interface-file declaration for variable getCTimespec1
        Probable cause: bug in .hi-boot file, or inconsistent .hi file
```

Which (presumably) then leads to:

```
    [53 of 54] Compiling Development.Make.All ( src/Development/Make/All.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/shake/shake-tmp/Development/Make/All.o )
    [54 of 54] Compiling Run              ( src/Run.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/shake/shake-tmp/Run.o )
    Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/shake/shake ...
    /home/alx/.stack/snapshots/x86_64-linux/nightly-2016-09-04/8.0.1/lib/x86_64-linux-ghc-8.0.1/extra-1.4.10-2LEZ2hBhlUuEhqffYmrH30/libHSextra-1.4.10-2LEZ2hBhlUuEhqffYmrH30.a(Extra.o):(.text+0xee9): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info'
    /home/alx/.stack/snapshots/x86_64-linux/nightly-2016-09-04/8.0.1/lib/x86_64-linux-ghc-8.0.1/extra-1.4.10-2LEZ2hBhlUuEhqffYmrH30/libHSextra-1.4.10-2LEZ2hBhlUuEhqffYmrH30.a(Extra.o):(.data.rel.ro+0xf8): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure'
    /home/alx/.stack/snapshots/x86_64-linux/nightly-2016-09-04/8.0.1/lib/x86_64-linux-ghc-8.0.1/extra-1.4.10-2LEZ2hBhlUuEhqffYmrH30/libHSextra-1.4.10-2LEZ2hBhlUuEhqffYmrH30.a(Extra.o):(.text+0x876): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info'
    /home/alx/.stack/snapshots/x86_64-linux/nightly-2016-09-04/8.0.1/lib/x86_64-linux-ghc-8.0.1/extra-1.4.10-2LEZ2hBhlUuEhqffYmrH30/libHSextra-1.4.10-2LEZ2hBhlUuEhqffYmrH30.a(Extra.o):(.text+0x916): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info'
    /home/alx/.stack/snapshots/x86_64-linux/nightly-2016-09-04/8.0.1/lib/x86_64-linux-ghc-8.0.1/extra-1.4.10-2LEZ2hBhlUuEhqffYmrH30/libHSextra-1.4.10-2LEZ2hBhlUuEhqffYmrH30.a(Extra.o):(.data.rel.ro+0xf0): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure'
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)
```

`ghc --version`  = 8.0.1
`stack --version` = Version 1.3.2 x86_64
`uname -a` = Linux amy 4.8.13-1-ARCH 1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Comment by ndmitchell** [comment]
See #508 for a possible fix - does that work for you? The fact it's happening to more than one person is worrying...

**Comment by alx741** [comment]
Yep, removing `~/.stack` worked, thanks!

**Comment by ndmitchell** [comment]
Can you give your OS, GHC and Stack versions? Let's look for commonalities with other failures.

**Comment by alx741** [comment]
I backed up the old `~/.stack` dir: https://mega.nz/#!6It3kZRL!9WPeiC7Ri7q_c9kb7urqbBtgHZ476Z_3HnPOhklJ0Sg

with the hope it is useful for replicating and debugging this issue.

The versions are already in the original issue comment, but here they are again with some additional info:

- `ghc --version`  = 8.0.1
- `stack --version` = Version 1.3.2 x86_64
- `uname -a` = Linux amy 4.8.13-1-ARCH 1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
- OS = GNU/Linux - **Archlinux**
- Both *stack* and *ghc* are installed from the Archlinux repositories

**Comment by arianvp** [comment]
Okay so I have the exact same setup as @alx741 
except I had Version 1.3.0 x86_64 of stack.   I don't have my original ~/.stack

**Comment by ndmitchell** [comment]
See also https://groups.google.com/d/msg/shake-build-system/G78DCmOEwx0/E6x1DPuNAQAJ - a stack build error that resulted in a segfault at runtime.

**Comment by anfelor** [comment]
I just had that problem too:

 - stack: `Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0`
 - ghc: `7.10.3`
 - Ubuntu `16.04`
 - `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

Error:
```Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/shake/shake ...
    /home/me/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/lib/x86_64-linux-ghc-8.0.1/random-1.1-54KmMHXjttlERYcr1mvsAe/libHSrandom-1.1-54KmMHXjttlERYcr1mvsAe.a(Random.o):(.text+0x1391): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info'
    /home/me/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/lib/x86_64-linux-ghc-8.0.1/random-1.1-54KmMHXjttlERYcr1mvsAe/libHSrandom-1.1-54KmMHXjttlERYcr1mvsAe.a(Random.o):(.data.rel.ro+0xfc0): undefined reference to `timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure'
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)
```

After removing `~/.stack` the problem disappeared.

**Comment by ndmitchell** [comment]
This issue went through a spate of happening to a few people, but now seems to have stopped. I assume some stack bug was fixed, or the situation changed to subtly avoid the problem.
