### ISSUE TITLE
Documentation: ChangeModtimeAndDigestInput and input.

### ISSUE THREAD

**Issue by pacak** [ndmitchell/shake#511]
I'm trying to use `ChangeModtimeAndDigestInput` and find it surprisingly undocumented: there's no examples of using it anywhere in the documentation or on http://shakebuild.com. The only comment related to it mentions input/source files and again no explanation of what shake sees as input files.

Compilation system I made works mostly fine but under some scenarios I see recompilations that I don't expect. I'm using an older version of shake and problem might just go away once I update it, but documentation improvement should be beneficial anyway.

**Comment by ndmitchell** [comment]
Thanks for pointing out that. The best docs are at https://hackage.haskell.org/package/shake-0.15.10/docs/Development-Shake.html#v:ChangeModtimeAndDigestInput, but I agree more would be better. An input file is anything that doesn't match a rule and falls through to checking the file exists. There were some bugs in earlier versions of Shake around changing between modes so an upgrade and clean build between mode switches is advisable.

**Comment by ndmitchell** [comment]
I wrote down what an input file was, which completes the docs. I think a large part of the confusion was because of bugs making the result pretty confusing, so hopefully that's the main fix here :).
