### ISSUE TITLE
Ambiguous withCreateProcess

### ISSUE THREAD

**Issue by Rockfordal** [ndmitchell/shake#513]
/tmp/stack23712/shake-0.15.10/src/General/Process.hs:160:9: error:
        Ambiguous occurrence ‘withCreateProcess’
        It could refer to either ‘System.Process.withCreateProcess’,
                                 imported from ‘System.Process’ at src/General/Process.hs:20:1-21
                              or ‘General.Process.withCreateProcess’,
                                 defined at src/General/Process.hs:134:1
Im using ghc-8.0.2
same with version 0.15.9, 0.15.8, 0.15.7

**Comment by ndmitchell** [comment]
0.15.10 has an upper bound on process of <1.4.3 (which was manually edited in by the Hackage maintainers). I would have thought that excluded the process that ships with ghc-8.0.2? How are you using stack which doesn't yet reference ghc-8.0.2?

The real solution is to release shake with the name clash fixed, which I'll hopefully do tonight or tomorrow.

**Comment by ndmitchell** [comment]
I've just released 0.15.11 which removes the upper bound and doesn't conflict with the newer process.
