### ISSUE TITLE
`cmdArguments` and `Arg(..)` are not exposed.

### ISSUE THREAD

**Issue by NorfairKing** [ndmitchell/shake#514]
I would like to make some helper functions that allow for the usage of `Path` and `Path.IO` so I would like to instantiate `Arg` for my own data type `data PathCmdOption = forall r. PathCwd (Path r Dir)`

**Comment by ndmitchell** [comment]
Do you need `cmdArguments` exposed? Or just `Arg(..)`? If exposing I'd be tempted to rejig it and expose:

```
data CmdArgument
instance Monoid CmdArgument

class IsCmdArgument a where
     toCmdArgument :: a -> CmdArgument
instance IsCmdArgument String
instance IsCmdArgument [String]
instance IsCmdArgument CmdOption
instance IsCmdArgument [CmdOption]
instance IsCmdArgument a => IsCmdArgument (Maybe a)
```

Would that be enough for you?

**Comment by NorfairKing** [comment]
I think so. That would allow me to define my own command arguments, which is what I'm looking for.

**Comment by NorfairKing** [comment]
Any progress here?

**Comment by ndmitchell** [comment]
Not recently - I hope to circle back to Shake hacking in a few days time. It's a fairly easy change, so I hope it will be in the next release.

**Comment by ndmitchell** [comment]
Maybe having `CmdOption` opaque is just too much hassle - being honest and saying it's `([CmdOption],[String])` might give more flexibility for other people to reuse the same mechanism.

**Comment by NorfairKing** [comment]
I'll leave it up to you. My use-case is to be able to use a `Path` from [`path`](https://hackage.haskell.org/package/path) as a command argument.

**Comment by ndmitchell** [comment]
Done as part of #526.
