### ISSUE TITLE
Only record each dependency at most once

### ISSUE THREAD

**Issue by pacak** [ndmitchell/shake#520]
```
import Development.Shake
import Development.Shake.FilePath

main = shakeArgs shakeOptions { shakeVerbosity = Diagnostic, shakeChange = ChangeModtimeAndDigest } $ do
    want ["a.txt"]

    "a.txt" %> \out -> do
        need $ replicate 10 "b.txt"
        need $ replicate 10 "d.txt"
        writeFileChanged out out
        
    "b.txt" %> \out -> do
        need $ replicate 10 "c.txt"
        writeFileChanged out out

    "c.txt" %> \out -> do
        need $ replicate 10 "d.txt"
        writeFileChanged out out


    "d.txt" %> \out -> do
        writeFileChanged out out
```

Code like this results in dependencies that look like this:

% Chunk 3 [len 130] 0000000300070000000000000005612e747874010006f4a39d5f000000070ec3502d0000000400000004020a000000040000000400000004000000040000000400000004000000040000000400000004000000040a0000000500000005000000050000000500000005000000050000000500000005000000050000000539dda26600 (Id 3,(a.txt,Loaded (Result {result = File {mod=0xF4A39D5D,size=0x5,digest=0xEC3502B}, built = Step 4, changed = Step 4, depends = [[Id 4,Id 4,Id 4,Id 4,Id 4,Id 4,Id 4,Id 4,Id 4,Id 4],[Id 5,Id 5,Id 5,Id 5,Id 5,Id 5,Id 5,Id 5,Id 5,Id 5]], execution = 4.22734e-4, traces = []})))

^ Id 4 and Id5 are mentioned 10 times each. While this snippet makes no sense I think it's a closest approximation of a build system I'm trying to debug - there project with ~50 files produce ~1500 individual dependencies on one file (combined).

**Comment by pacak** [comment]
Fragment of a dependency list in a real project:

```[[Id 9],[Id 1124],[Id 1126],[Id 9],[Id 1124],[Id 1126],[Id 9],[Id 1124],[Id 1126], ....```

That is it depends on each of Id 9, Id 1124 andId 1126 165 times.

**Comment by ndmitchell** [comment]
Thanks for the report. This is known and not harmful. It was assumed people would avoid doing multiple `need`'s on the same thing, and thus the memory required to avoid duplicates would be a bit of a waste. As you have demonstrated, that's clearly not the case, so I'll add duplicate removal. That said, if you are calling `need` 165 times more than necessary, you might want to consider simplifying something.

**Comment by pacak** [comment]
They are kind of simple. Every file needs a timestamp that changes when
cabal stuff gets updated, every .o file needs .hs  (one) and .hi (several),
binary needs all the .o files. That timestamp file gets needed a lot of
times via all the dependencies.

On Mar 24, 2017 3:21 PM, "Neil Mitchell" <notifications@github.com> wrote:

Thanks for the report. This is known and not harmful. It was assumed people
would avoid doing multiple need's on the same thing, and thus the memory
required to avoid duplicates would be a bit of a waste. As you have
demonstrated, that's clearly not the case, so I'll add duplicate removal.
That said, if you are calling need 165 times more than necessary, you might
want to consider simplifying something.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ndmitchell/shake/issues/520#issuecomment-288951100>,
or mute
the thread

**Comment by pacak** [comment]
They are kind of simple. Every file needs a timestamp that changes when
cabal stuff gets updated, every .o file needs .hs  (one) and .hi (several),
binary needs all the .o files. That timestamp file gets needed a lot of
times via all the dependencies.

**Comment by ndmitchell** [comment]
What does the code doing that look like? It seems like lots of individual need calls, whereas one single need call with all the dependencies is more efficient, has better scope for parallelism and already removes duplicate dependencies. Of course, it's also sometimes more effort to orchestrate and thus not worth it, but for Cabal tracking it might not be.

**Comment by ndmitchell** [comment]
Cool. However, I'm still not quite sure why a single output generates many dependencies on the same input. Is that bit of your Shake system available online? Not really a problem though - I agree the underlying thing can be optimised anyway.

**Comment by pacak** [comment]
Not yet available but I'll look into making it available. I can certainly
post it here when I get to my computer.

**Comment by pacak** [comment]
This chunk will parse makefile and create a map  with dependencies: .o -> [.hs, *.hi] plus a bit more magic plus support for profiling

```
    makerule' <- newCache $ \_ -> do
        need extsrc
        sources <- readFileLines allSourceFilesFile
        let opts = ghcBuildOptions buildOptions { optimization = 0, prof = False }
            dirs = ghcBuildDirOptions $ traderObjectFileDir buildOptions
            tmp = "_mk/tmp/makefule"

        () <- cmd "ghc -M -dep-suffix=" [""] "-dep-makefile" [tmp] sources opts dirs (Traced "ghc -M: create Makefile")
        mk <- liftIO $ parseMakefile <$> readFile tmp

        -- ghc -M won't track external dependencies since it's not running TH code
        thMk <- parseMakefile <$> readFile' allDepsFilesFile

        -- TH modules and where to find them (if there's any)
        (Exit _, Stdout (lines -> thModules)) <- cmd "grep -l"
            ["import .*Language\\.Haskell\\.TH"]
            sources

        let -- helper
            rulesFromList = foldr (uncurry $ Map.insertWith (++)) Map.empty

            -- profiling files are created similarly to regular files
            to_p v = case splitExtension v of
                        (base, ".o") -> base <.> "p_o"
                        (base, ".hi") -> base <.> "p_hi"
                        _ -> v

            -- how to find specific Haskell module
            hs2mod (a, b) = do
                b' <- listToMaybe b
                case splitExtension b' of
                    (base, ext) -> do
                        base' <- stripPrefix "src/" base
                        guard $ ext == ".hs"
                        return (replaceChar '/' '.' base', [a])

            -- to compile .hi file we can simply compile .o file
            hi2o v = case splitExtension v of
                        (base, ".hi") -> Just (v, [base <.> "o"])
                        (base, ".p_hi") -> Just (v, [base <.> "p_o"])
                        _ -> Nothing

        let rm = rulesFromList $ map (swap . ((:[]) *** head)) mk
            ths = concat $ mapMaybe (flip Map.lookup rm) thModules
            typechecker = (typecheckPhony, ths)

        let allRules = rulesFromList $ concat
                [ mk
                , thMk
                , map (to_p *** map to_p) mk
                , typechecker : map (to_p &&& (:[])) ths
                , mapMaybe hs2mod mk
                , mapMaybe (hi2o . head . snd) mk
                ]
        liftIO $ mapM_ print (mapMaybe hs2mod mk)
        return $ \src -> Map.findWithDefault [] src allRules

    -- we want to run action only once and then cache function it creates
    let makerule :: FilePath -> Action [FilePath]
        makerule src = makerule' "O_o" <*> pure src
```

this collects all the object files for given executable
```

    -- gets list of object files required by any module
    let execObj :: String -> Action [FilePath]
        execObj name = do
            let go :: Set.Set FilePath -> FilePath -> Action (Set.Set FilePath)
                go s f
                    | f `Set.member` s = return s
                    | otherwise = do xs <- makerule f
                                     foldM go (Set.insert f s) xs

            filter ("//*.o" ?==) . Set.toList <$> go Set.empty name
```

It's possible to write `mkObjFile` using `|%>` but at some point it starts trying to compile both .o and .p_o versions even when only one is  requested.

```
    -- compiles *.o / *.p_o file by using dependencies
    let mkObjFile f = do
            deps <- makerule f
            need deps
            let hs = filter ("//*.hs" ?==) deps
            cmd "ghc -c -g" hs (ghcBuildOptions buildOptions { prof = "//*.p_o" ?== f })
                         (ghcBuildDirOptions $ traderObjectFileDir buildOptions)

    "//*.hi"   %> \hi -> need [hi -<.> "o"]
    "//*.p_hi" %> \hi -> need [hi -<.> "p_o"]

    "//*.p_o" %> mkObjFile

    "//*.o"   %> mkObjFile
```

the rest is mostly like this

```
    -- Building executables
    forM_ givenExecs $ \target -> executableFile buildOptions target %> \_ -> do

        let ExecInfo{..} = getExecutable target
        objectFiles <- adjustProf <$> execObj execModName
        need objectFiles


        buildExec objectFiles (mainSource execModName) ExecInfo{..}
```


There are much more code in whole build system that deals with building unrelated stuff (docs, tests, linting, compilation cache, ghcid on executables, etc)  but I think everything specific to executables is here.

**Comment by ndmitchell** [comment]
Just as a side note, `replaceChar '/' '.' base'` can be replaced by `replace "/" "." base'` using the `replace` function in `extra`. I had a version of `replaceChar` for years until someone showed me it can be easily generalised.

I think I understand why you are getting lots of dependencies repeated - it is almost certainly due to going through the cache. What you are doing seems quite sensible (the deduped version would have to break through lots of layers of abstraction), so I'll adjust to dedupe dependencies.

**Comment by pacak** [comment]
> Just as a side note, replaceChar '/' '.' base' can be replaced by replace "/" "." base'

True, but with `runhaskell` approach to run stuff I suspect `replaceChar` will be faster. Don't have any numbers to confirm that though.

**Comment by ndmitchell** [comment]
Turns out it wasn't very difficult to add, a fairly sensible and cheap optimisation. No tests since it's non-observable, but I checked and saw it having the desired effect in my examples.
