### ISSUE TITLE
Should `copyFile` create parent directories if they don't exist?

### ISSUE THREAD

**Issue by seagreen** [ndmitchell/shake#522]
I'm currently using Shake as a static site generator, and having to remember to add `createDirectoryIfMissing` before every invocation of `copyFile` isn't great.

(This goes for `copyFileChanged` as well).

PS Thanks again for Shake!

**Comment by ndmitchell** [comment]
My thoughts are yes, it should, since if you don't then things break randomly. I originally didn't because `copyFile` in Haskell doesn't - but I somewhat view that as a bug. Let's fix Shake.

**Comment by ndmitchell** [comment]
BTW, if the files are output files, then it will have already created the directory, so lacking `copyFile` might be a sign that you haven't got the files properly tracked as outputs, and if you were to delete them it wouldn't rebuild.

**Comment by ndmitchell** [comment]
Another note, `provides` should probably do a `createDirectoryIfMissing` - to be consistent.

**Comment by seagreen** [comment]
Sounds great!

> BTW, if the files are output files, then it will have already created the directory, so lacking copyFile might be a sign that you haven't got the files properly tracked as outputs, and if you were to delete them it wouldn't rebuild.

Thanks for the tip. I'm using `Development.Shake.Forward` though, which if I understand it right doesn't track outputs at all.

**Comment by ndmitchell** [comment]
That makes a lot of sense - I'll make `copyFile` create the directory.

**Comment by ndmitchell** [comment]
Fixed as part of #526.
