### ISSUE TITLE
Why shakeLintIgnore doesn't turn off validity check for certain files?

### ISSUE THREAD

**Issue by izgzhen** [ndmitchell/shake#531]
A minimal example: https://gist.github.com/izgzhen/74dd1672727ce19e2e3ca58b9299b982 shakeLintIgnore

When the build system built `main.o` and sleeps, I can modify the `main.o` on the fly. If nothing is provided, then the ultimate build will fail due to a lint error saying that the `main.o` has changed. However, I can _NOT_ turn off this behavior by either `shakeLintIgnore` or `trackAllow`. Is there something I've missed?

**Comment by ndmitchell** [comment]
There are really two lint modes - LintBasic and LintFSATrace. The latter is influenced by `trackAllow` and `shakeLintIgnore`, but in your case it's the basic lint that is triggering, so the functions have no effect.

The reason you can't disable this lint warning (short of turning off lint altogether) is that it's seriously problematic. You have a rule that has built `main.o`, and then you have another rule that modifies `main.o` afterwards. As a consequence, next time you run the build `main.o` will have changed and you'll have to rebuild it again, so the build won't even _finish_ in a clean state.

Does that all make sense?

**Comment by izgzhen** [comment]
> Does that all make sense?

Sure, I see. Thanks a lot!
