### ISSUE TITLE
shake windows build has been failing tests for a month

### ISSUE THREAD

**Issue by philipcraig** [ndmitchell/shake#532]
The Appveyor build:

https://ci.appveyor.com/project/ndmitchell/shake/build/1.0.549

passes tests, but newer builds fail tests. Sadly, appveyor has still been reporting a successful build.

stack resolved to lts-8.22

The breaking commit seems to be:

https://github.com/ndmitchell/shake/commit/15d78737ed5d4921030b0212cec7efb6191869c0

The failure can be seen in the AppVeyor logs thus:

```
## FINISHED TESTING directory
## BUILD docs test
## TESTING docs
## BUILD docs --abbrev=output=$OUT -j3
# runhaskell (for ../../dist/setup-config)
Configuring shake-0.15.11...
Error when running Shake build system:
* Success.txt
* Files.lst
* ../../dist/doc/html/shake/index.html
* ../../dist/setup-config
Error, rule failed to build file:
  ../../dist/setup-config
CallStack (from HasCallStack):
  error, called at src\Development\Shake\Internal\Rules\File.hs:171:58 in main:Development.Shake.Internal.Rules.File
TESTS FAILED
Completed 14 action(s).
Test suite failure for package shake-0.15.11
    shake-test:  exited with: ExitFailure 1
Logs printed to console
Downloading and running weeder...
= Package shake =
No warnings
Ignored 65 weeds (pass --show-all to see them)
Updating build cache...
Cache entry not found: c:\sr
Build success
```

Edit: on local Win7 workstation, git checkout of 5ede5b5d76f658644834931c268ea1b2208be508 and forcing stack resolver to use lts-8.17 still fails tests with a core dump, even though that build worked on AppVeyor.

Edit:  Testing shake from hackage 0.15.11 release seems fine. Bizarrely, it wasn't fine (ghc core dump) if run in a cmd prompt with admin access.

**Comment by ndmitchell** [comment]
I've fixed all the test suites. They were all minor details, flags renaming etc, and nothing that could core dump. What are your local symptoms? What core dumps? Building? Testing?

**Comment by philipcraig** [comment]
Symptom was core dumping during the ``BUILD DOCS`` phase of ``stack test``. Now, having upgraded to stack 1.5.0, and on either lts-8.22 (as above) or lts-9.0, I have no local problems. It was my local problems that led me to check out the appveyor build as above.

**Comment by ndmitchell** [comment]
Great, if the segfault comes back, let me know.
