### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by NorfairKing** [ndmitchell/shake#533]
I have a build system with these characteristics

![shake](https://user-images.githubusercontent.com/3521180/28521289-3a0d3020-7073-11e7-89b7-bbd3a7ed8f55.png)

However, it takes quite long to boot:

![shake2](https://user-images.githubusercontent.com/3521180/28521313-502ad7b8-7073-11e7-8ae4-8e3d32e762c7.png)

Is this supposed to be the case?

**Comment by ndmitchell** [comment]
The 31% running rules is probably the 12 rules it had to rebuild in the last run. If you look at the more complete profile report, filter for run(0), you should be able to see which rules they are and how long each one took. If they don't add up to ~2.8s then you have more confusion.

For the @5.5s in function shake, I suggest running GHC Profiling, we should show where things are going. I usually don't see much time there at all.

**Comment by NorfairKing** [comment]
I'm mostly confused by the 'Function shake' part, the 'running rules' part is fine. I'll try profiling it.
Is shake supposed to be able to handle ~10k rules?

**Comment by ndmitchell** [comment]
Are they 10K rules using `%>`? Are they programmatically generated? If so, you might be better of using `?>` and a HashMap. Shake sometimes spots that and optimises it, and generally in a zero build this shouldn't show up under 'Function shake', but it's possible. I'd love to see the profile. What does `--no-build` take?

**Comment by NorfairKing** [comment]
> Are they 10K rules using %>?

Yes, I think so.

> Are they programmatically generated? 

Yes.

> If so, you might be better of using ?> and a HashMap. 

Interesting! I'll have a look. I thought this would be slower, given that it's more general.

> I'd love to see the profile

It's still building :p 

The project is here: https://github.com/NorfairKing/easyspec
It's very much a research project, so I wouldn't be surprised if something doesn't work.

**Comment by NorfairKing** [comment]
I tried the `--no-build` with `--profile`: 

```
$ stack exec easyspec-evaluate -- build +RTS -p -RTS -- --no-build
Warning: No want/action statements, nothing to do
Writing report to report.trace
Writing report to report.html
shakeArgsWith                     0.016s    0%                           
Function shake                    7.119s   80%  =========================
Database read                     0.166s    1%                           
With database                     0.013s    0%                           
Running rules                     0.000s    0%                           
Pool finished (1 threads, 1 max)  0.002s    0%                           
Profile report                    1.491s   16%  =====                    
Total                             8.806s  100%                           
Build completed in 0:09m
```

It looks like most of the time is spent in `parseAbsFile` and `liftIO`, weirdly.

**Comment by ndmitchell** [comment]
You should avoid putting parseAbsFile in the critical path. Do you have a Rule instance using Path?

I note that while it's not Shake's fault, almost all the functions `parseAbsFile` calls are in `filepath`, which I wrote, so might still track down to me! That said, better to avoid them on null builds rather than optimise them.

**Comment by NorfairKing** [comment]
> You should avoid putting parseAbsFile in the critical path.
> Do you have a Rule instance using Path?

Yes, I'm trying to make sure that all my paths are absolute, using `path`.
Unfortunately it seems that `path`, and `path-io` are a bit to slow to use when defining a build system.

Closing this issue as it's not `shake`s fault :)
