### ISSUE TITLE
Should `writeFileChanged` create parent directories if they don't exist?

### ISSUE THREAD

**Issue by seagreen** [ndmitchell/shake#534]
Same deal as #522.

**Comment by ndmitchell** [comment]
`writeFile'` and `writeFileChanged` should behave the same here. I benchmarked `writeFile' foo ""` (0.319s for 1000) with a `createDirectoryIfMissing` beforehand (0.421s for 1000), and then used a `doesDirectoryExist` test guarding the creation (0.361) - so I'll go with the last option.

**Comment by ndmitchell** [comment]
Done.
