### ISSUE TITLE
Get detailed information about inconsistent targets for use with `needHasChanged`.

### ISSUE THREAD

**Issue by erwo42** [ndmitchell/shake#543]
To get around the bug mentioned in #539 at the end of the discussion, there should be a way to get finer information about the state of the targets in a rule.

Quote from the discussion in #539 :

> The last test in Test.Basic demonstrates, that there is an open problem regarding the use case in #502 (slowCompile, fastUpdate) under the assumption, that you don't want to loose shakes nice property of detecting targets, with which has been messed. If no dependency is changed and the Action() is run, you can assume the target was messed with and rebuild it by slowCompile (as it can be altered in unanticipated ways). But if one changes the dependencies in a way, that triggers fastUpdate and the target was messed with, your screwed. At least I don't see, how you could detect this at the moment. (But I still think, my PR is a useful first step.)

and

> Regarding the bug you outline, agreed, it's a tricky case - sometimes you want to rebuild not because the dependencies have changed, but because the target has. Fortunately the people who are messing around with needHasChanged are probably not standard users, so a bit of a rough edge isn't the end of the world as a first step.

I would propose to add operators

```haskell
(%!>) :: FilePattern -> (FilePath -> Bool -> Action ()) -> Rules ()
(|%!>) :: [FilePattern] -> (FilePath -> Bool -> Action ()) -> Rules ()
(?!>) :: (FilePath -> Bool) -> (FilePath -> Bool -> Action ()) -> Rules ()
```
which would act like `(%>)`, `(|%>)` and `(?>)` but would call their second argument with the `FilePath` of the target to be build and a `Bool` indicating if the targets must be build independent of the state of the dependencies, as it was messed with and might even be deleted, for example. Those operators should be grouped under the "Batching" section of the documentation and be advised against their usage, as they are for advanced users only. `shakeRebuild` can be handled by not running the rule for `RebuildLater` and running the rule and pretending the target was messed with for `RebuildNow`.

For multiple target rules, there is the problem of properly handling the `shakeRebuild` option for them, so the api I propose is

```haskell
(&%!>) :: [FilePattern] -> ([FilePath] -> [Rebuild] -> Action ()) -> Rules () 
(&?!>) :: (FilePath -> Maybe [FilePath]) -> ([FilePath] -> [Rebuild] -> Action ()) -> Rules ()
```
where a value at some position in the `[Rebuild]` list specifies
 * whether the rule should rebuild the associated target normally (`RebuildNormal`), possibly depending on `needHasChanged` information or
 * whether the rule must rebuild the associated target (`RebuildNow`), as it was messed with and might be deleted or a `RebuildNow` option was given for the associated `FilePath` or
 * whether the rule must not rebuild the associated target (`RebuildLater`), as a `RebuildLater` option was given for the associated `FilePath`.

Hopefully that handles all cases and I didn't forgot something.

As `needHasChanged` is for file rules also, I think it would be okay to other these
features for file rules only too.

I would offer to implement this and make a PR for it, if you think, you might include something like that.

Possibly a bit ugly might be, that `(&%!>)`, `(&?!>)` and `(&%>)`, `(&?>)` would handle `shakeRebuild` a bit differently with some "bulk" semantics for `(&%>)` and some "finer" ones for `(&%!>)` and the like.

What do you think?

**Comment by ndmitchell** [comment]
This sounds like a lot of quite complicated operators, so seems a bit excessive - everything that is `O(n)` in the number of file operators seems a bit excessive. I wonder if a simpler `targetHasChanged :: Action Bool` would be easier? I don't think for the `&%>` family of rules we need to say exactly which target has changed (the whole point is you can't build them indivisibly anyway - otherwise you'd be better using `batch`). Not sure exactly how to implement `targetHasChanged` right away (might have to be a new thing?).

**Comment by erwo42** [comment]
1. Yes, duplicating all the file operators is excessive. I like the idea of having a `targetHasChanged`.
Maybe one could implement it similar to `getVerbosity`, `withVerbosity`? The user would call `targetHasChanged` and the implementor of the `BuiltinRule` would call `withTargetsChanged` or similar.
One could regard it as mildly unpleasant to have a field in `Local` which is (in my imagination so far) only used for file rules, but the information needs to be transported somehow.
2. Regarding the `&%>` family of rules, I think it's no harm to say exactly which target has changed.
It opens up the possibilty to implement "static batch rules" properly, where the batch is known a priori and not collected piece by piece, while the build system is running.
This is useful, in my opinion, if you know that the need for one file from your batch means all files from the batch will be needed at some time. Why not make all of them, that need redoing, then?

Of course, its your decision.

**Comment by ndmitchell** [comment]
Thinking further, would:

```haskell
fileHasChanged :: FilePath -> Action Bool
```

Be sufficient? With `&%>` you are free to call it on each of the targets. It doesn't have to be run in the rule building the file, but that would be the expected use. I suggest we rerun the "file has changed" check. This function should come with some serious health warnings as the value might change through an `Action` block, but it's for specialist use anyway.

**Comment by ndmitchell** [comment]
I pushed `resultHasChanged` and used it to clean up the test suite where it was previously failing. Thoughts?

**Comment by erwo42** [comment]
At a first glance everything looks good to me! Thank you!
