### ISSUE TITLE
shake --lint doesn't consider order-only transitive dependencies

### ISSUE THREAD

**Issue by RedBeard0531** [ndmitchell/shake#547]
I put all generated headers in a single phony target, and have all compiles depend on that. `shake --lint` still complains about a missing dependency. This is a small repro:

```
rule RUN
  command = $cmd

build generated_files: phony build/gen
build build/gen: RUN
  cmd = touch build/gen
build build/out: RUN || generated_files
  cmd = touch build/out; echo 'build/out: build/gen' > build/out.d
  depfile = build/out.d
```

```
> rm -r .shake build ; shake --lint
# gen (for build/gen)
# out.d (for build/out)
shake: Error when running Shake build system:
* build/out
Lint checking error - file in deps is generated and not a pre-dependency:
  File:  build/gen
```

**Comment by ndmitchell** [comment]
I'm running Windows and was unable to reproduce something I think should be equivalent. Can you try cutting it down in the following two ways and see if you still see the error:

* Replace `build/gen` with `build_gen`, so there are no paths in there.
* Remove the depfile, and thus also remove echoing out to the `out.d` file.

From what I can tell reading the code, neither should have any impact, and then I can make my Windows test case significantly closer to your Linux one and explore a simpler variation.

**Comment by RedBeard0531** [comment]
How's this:

```
rule RUN
  command = $cmd

build generated_files: phony gen

build gen: RUN
  cmd = touch gen

build out: RUN || generated_files
  cmd = touch out;  echo 'dep: gen'
  deps = msvc
  msvc_deps_prefix = dep:
```

```
> rm -r out gen .shake; shake --lint out -j1 --verbose --verbose; ll out gen
# out
# gen
'touch gen'
'touch out;  echo '\''dep: gen'\'''
shake: Error when running Shake build system:
* out
Lint checking error - file in deps is generated and not a pre-dependency:
  File:  gen


-rw-r--r-- 1 mstearn mstearn 0 Nov  8 19:52 gen
-rw-r--r-- 1 mstearn mstearn 0 Nov  8 19:52 out
```

Note that it does build gen before out (due to the transitive dependency), then complains that there isn't a dependency. If there wasn't, why was gen build? Adding gen as a direct non-transitive order-only dependency of out makes the lint error go away, but there should really be no difference between direct and transitive order-only dependencies.

**Comment by RedBeard0531** [comment]
Actually, I noticed that the behavior when the dependencies actually *are* wrong is really weird. It builds gen after building out, even though out's deps say that gen must be build first.

```
rule RUN
  command = $cmd

build generated_files: phony gen

build gen: RUN
  cmd = touch gen

build out: RUN
  cmd = touch out;  echo 'dep: gen'
  deps = msvc
  msvc_deps_prefix = dep:
```

```
> rm -r out gen .shake; shake --file build.ninja out -j1 --verbose --verbose; ll out gen
# out
'touch out;  echo '\''dep: gen'\'''
# gen
'touch gen'
-rw-r--r-- 1 mstearn mstearn 0 Nov  8 20:13 gen
-rw-r--r-- 1 mstearn mstearn 0 Nov  8 20:13 out
```

**Comment by ndmitchell** [comment]
Reproduced now - I was doing something dumb which made it not happen now. I wasn’t seeing through phony in the check, so I’ve fixed that, will push this evening.

For the behaviour without lint, Shake treats a post dependency without lint as a need, which is a reasonable encoding if you haven’t screwed up the dependencies. If you have, it’s probably slightly better than the Ninja approach as the build reaches a stable fixed point rather than having stuff to do next time as well.

**Comment by ndmitchell** [comment]
All fixed.
