### ISSUE TITLE
Rebuild build.ninja first, then use the new version

### ISSUE THREAD

**Issue by RedBeard0531** [ndmitchell/shake#548]
I've noticed that shake will rebuild build.ninja in the middle of a run as it were a normal output. I think ninja has the correct behavior in this case: first rebuild build.ninja, then reload the new dependency graph, repeat if needed until build.ninja is up to date, then build whatever targets are actually supposed to be built. This ensures that you are using the correct rules and dependencies that match the code you are trying to build.

**Comment by ndmitchell** [comment]
Done - I didn't realise Ninja did this (it's not documented in the manual) but easily replicated.
