### ISSUE TITLE
General/Bilist.hs fails to compile with recent GHC HEAD

### ISSUE THREAD

**Issue by ggreif** [ndmitchell/shake#554]
```
[13 of 57] Compiling General.Bilist   ( src/General/Bilist.hs, dist/build/General/Bilist.o )

src/General/Bilist.hs:22:10: error:
    * No instance for (Semigroup (Bilist a))
        arising from the superclasses of an instance declaration
    * In the instance declaration for `Monoid (Bilist a)'
   |
22 | instance Monoid (Bilist a) where
   |          ^^^^^^^^^^^^^^^^^
```

**Comment by ggreif** [comment]
This is another occurrence
```
src/General/Binary.hs:71:10: error:
    * No instance for (Semigroup Builder)
        arising from the superclasses of an instance declaration
    * In the instance declaration for `Monoid Builder'
   |
71 | instance Monoid Builder where
   |          ^^^^^^^^^^^^^^
```

**Comment by ggreif** [comment]
I am preparing a PR, no need to hurry.

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/shake/pull/549 as well. Happy for you to build on that or start afresh. I guess I want a dependency on semigroup package on older GHC?

**Comment by ggreif** [comment]
I guess there are 2 options:
- add the `Semigroup` dependency for older GHCs
- use `language CPP` to only implement `Semigroup` instances when SMP is in place

Currently I am fixing things (e.g.) in this way:

``` haskell
instance Semigroup Progress where
  (<>) = mappend
```

which should be sufficient for some more generations.

**Comment by ggreif** [comment]
@angerman seems to do the _Right Thing (TM)_, but that solution will definitely need the `Semigroup` dependency for older GHCs.

**Comment by ndmitchell** [comment]
I really dislike CPP, so I guess an extra dependency to the previous PR is a reasonable way to go.

**Comment by ggreif** [comment]
@ndmitchell okay, maybe you know how to put that in? Then you can merge the PR #555 if you think it is good.

**Comment by angerman** [comment]
I'm terribly sorry for now having pick that up yet. I'm a bit under water with so much going on. I'll try to carve out a few minutes to fix this up tomorrow. Sorry to inconvenience everyone involved :(

**Comment by ggreif** [comment]
@angerman don't worry! Stuff gets done :-)

**Comment by angerman** [comment]
@ggreif updated my PR to add the semigroup dependency.

**Comment by ndmitchell** [comment]
And merged :). I've also been underwater this week, or would have finished off @angerman's great work.

**Comment by ggreif** [comment]
Great job, all!
