### ISSUE TITLE
getDirectoryFilesIO does not accept absolute paths?

### ISSUE THREAD

**Issue by peti** [ndmitchell/shake#557]
Is the following behavior to be expected or is that a bug?

~~~
λ> getDirectoryFilesIO "/tmp" ["*"]
[".X0-lock"]
λ> getDirectoryFilesIO "" ["/tmp/*"]
[]
~~~

It certainly feels counter-intuitive to me. I'm using `shake-0.16` with GHC 8.0.2 on Linux.

**Comment by ndmitchell** [comment]
Expected - you are saying use `.` as the root directory, and thus below that, you can't find any absolute files. You can do `getDirectoryFilesIO "/" ["tmp/*"]` as an alternative. I'll clear up the docs calling out this special case.

**Comment by peti** [comment]
`getDirectoryFilesIO "/" ["tmp/*"]` won't give me absolute path results, though, which is what I'd hoped to get.

**Comment by ndmitchell** [comment]
Indeed it won't - and I can't think of any way to track `getDirectoryFilesIO` into doing so. It basically takes an absolute or relative path as its first argument, then a list of patterns to match and return relative to that base. That means the patterns are necessarily matched as absolute. You should be able to fake it with:

```haskell
getDirectoryFilesAbs root pats = fmap (map (root </>)) pats
```

However, in Shake, people should almost always be working with relative paths (so builds aren't tied to a particular location), so things in Shake tend to default to relative paths.

**Comment by peti** [comment]
OK. I see your point. Thank you for the quick response.
