### ISSUE TITLE
Preserve output color of command

### ISSUE THREAD

**Issue by BjornMelgaard** [ndmitchell/shake#558]
```hs
#!/usr/bin/env stack
{- stack
  script
  --resolver lts-9.18
  --package shake-0.16
  --
  +RTS -s -RTS
-}

import           Development.Shake (shakeArgs, ShakeOptions(..), shakeOptions, phony, putNormal)
import           Development.Shake.Command (CmdOption(..), cmd)
import           Development.Shake.FilePath ()
import           Development.Shake.Util ()

main :: IO ()
main = shakeArgs shakeOptions{shakeColor=True} $ do
  phony "lint" $ do
    cmd "ls -a"
```

gives 
![2017-12-17-14 05 10-screenshot](https://user-images.githubusercontent.com/7573215/34079272-5eed81c8-e333-11e7-84b5-b80f695d4f88.png)

Expected: 
`stack runghc -- Shakefile.hs lint` preserve color of `ls -a` if `shakeColor=True`

**Comment by BjornMelgaard** [comment]
sorry, I'm dumb, I had to use 

`    cmd "ls -a --color=auto"
`

**Comment by ndmitchell** [comment]
Shell alias for `ls`? Yep, that's a common setup on Linux machines.
