### ISSUE TITLE
Optimise the model

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#561]
Shake is basically modelled as:

```
type Local = Key -> (Value, [(Key, Value)])
```

Namely for each `Key` we have a `Value`, and for all dependencies we record their values too. In practice we actually record:

```
type Local = Key -> (Value, Time, Time, [(Key, Time)])
```

Where the `Time` is the time of rebuild, `Time` of change, and `Time` of change for each of our dependencies. @snowleopard wonders if you actually need the `Time` for each dependency or if it's implicit because you know the time of rebuild, and thus anyone who changed after that is dirty, anyone who changed before it is correct. I think he's right, but need to do some experiments.

**Comment by ndmitchell** [comment]
We never recorded `[(Key, Time)]`, it was always just `[[Key]]` (to account for `need` doing a parallel fetch). Concretely:

```haskell
data Result a = Result
    {result :: a -- ^ the result associated with the Key
    ,built :: {-# UNPACK #-} !Step -- ^ when it was actually run
    ,changed :: {-# UNPACK #-} !Step -- ^ the step for deciding if it's valid
    ,depends :: [Depends] -- ^ dependencies (don't run them early)
    ,execution :: {-# UNPACK #-} !Float -- ^ how long it took when it was last run (seconds)
    ,traces :: [Trace] -- ^ a trace of the expensive operations (start/end in seconds since beginning of run)
    } deriving (Show,Functor)

newtype Depends = Depends {fromDepends :: [Id]}
```

So yes that's a sensible optimisation, and I already did it. Thanks to "Build Systems a la Carte" we can now talk about this optimisation in isolation, which is super helpful.

**Comment by snowleopard** [comment]
> Thanks to "Build Systems a la Carte" we can now talk about this optimisation in isolation, which is super helpful.

Cool :-)
