### ISSUE TITLE
Consider a way to get the benefits of applicative-do

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#568]
There are two cases where we might be able to get more parallelism:

```haskell
foo !> \_ -> do
    need [file1]
    need [file2]
    ...
```

and:

```haskell
foo !> \_ -> do
    ... some IO operation ...
    need [file1]
    need [file2]
    ...
```

It would be nice to execute only a single need fetching both items. In the first example, it would also be useful to delay starting the `foo` computation until after all the `need`'s have completed, in effect providing an applicative build system.

The disadvantage is that if a user deliberately wants to do files in sequence they can't - but introducing a `barrier` could solve that. This would be easy enough with by making `Action` a free monad, which should be investigated.

**Comment by ndmitchell** [comment]
I tried converting `Action` into an explicit GADTs with an interpreter, which slowed down the `Action` monad from 0.6s to 2.62s in one artificial benchmark. That would give us the ability to do applicative steps in parallel, and I suspect time running the `Action` monad is rarely a benchmark, but it feels a shame that it's 3 times slower... Code at https://gist.github.com/ndmitchell/87e06a0a6cc30ffec8b254a298ed91b8 for if I decide it should be done.

**Comment by ndmitchell** [comment]
Using the benchmark:

```haskell
neil :: RAW Int Int Int
neil = do
    replicateM_ 10000000 $ do
        x <- getRO
        modifyRW (+x)
    getRO
```

It used to be 0.6s. The initial ADT/interpreter approach made that 2.6s. Optimising the GHC Core got it down to 0.4s - so now it's a speed win. I don't do the Applicative trick yet, but that should be possible to wire in.

**Comment by dwijnand** [comment]
Done as of Shake 0.18, right?

https://neilmitchell.blogspot.com/2019/05/shake-with-applicative-parallelism.html?m=1

**Comment by ndmitchell** [comment]
Yep, thanks!
