### ISSUE TITLE
return a value from an action

### ISSUE THREAD

**Issue by shmish111** [ndmitchell/shake#572]
Why does `action` have the type `Action a -> Rules ()` and not `Action a -> Rules a`?

I'm in a situation where I need to use actions to build up a list of files I want to produce, I'm then going to `files **> produce them` however I can't do this because everything I do inside an action is void.

**Comment by ndmitchell** [comment]
@shmish111 That's deliberate because the steps in Rules are run in parallel. Can you say more about your desire to do this accumulation? An alternative formulation is to use a `.stamp` file, say you `want "foo.stamp"`, and then say `foo.stamp` can be build by doing the action you mention.

**Comment by ndmitchell** [comment]
Oh, and `Rules` has a `MonadIO` instance which might be what you want, if your action is not necessary to live in `Action`?

**Comment by shmish111** [comment]
I'm refactoring your code from 2015 here :-)

So I only want to use library a if I'm in debug mode, if I am then I want to copy if from some lib directory into my _make directory. The way I know if I'm in debug mode is by checking an env var. I *could* use `IO` to get the env var but really I want this stored in the shake db through an `askOracle`, right? My assumption here is that I want the shake db to know my entire environment so that it can know what it needs to rebuild, is this correct?

**Comment by shmish111** [comment]
I've worked out that the logic wasn't really working the way shake wants it anyway, I can need for all the files I want in a single action (which can get helper info from `askOracle` and then have rules to explain how to copy these files (which may also require `askOracle`). I think I see now why there is no `Action a -> Rules a`.

I would still like to know if storing env vars in the Oracle is the correct thing to do? I'm not sure what goes on behind the scenes but it feels like shake db should know everything and sneaky a `liftIO` could break the logic as to whether a rule should be rerun or not.

**Comment by shmish111** [comment]
I think what I need to understand is what is the reason for using an Oracle when I could just get the information I want directly from IO?

**Comment by shmish111** [comment]
Presumably reaching into IO to get information will make chaching impossible in the future?

**Comment by mitchellwrosen** [comment]
@shmish111 Have you seen [`getEnv`](https://hackage.haskell.org/package/shake-0.16.3/docs/Development-Shake.html#v:getEnv)? It adds a dependency on the given env var.

**Comment by shmish111** [comment]
yes, I just saw this. Sorry for this ticket, I think it was due to a misunderstanding of these functions.

**Comment by ndmitchell** [comment]
Sounds like you were starting from code written by a moron 😈 

An `action` is the way to go here. Once you are using an action, whether the information is tracked via `getEnv` or not is irrelevant - actions are always rerun from scratch so doing IO actions in them isn't a problem.
