### ISSUE TITLE
tutorials: encourage the name “Shakefile.hs”

### ISSUE THREAD

**Issue by mcandre** [ndmitchell/shake#582]
The online tutorials for shake strangely don’t use the right name (the main project build script should be called `Shakefile.hs` or `Shakefile.lhs` for literate Haskell), which causes the `shake` command to fail in practice because it mainly looks for these two filenames.

Could the tutorials emphasize this filename scheme for a more seamless first time experience?

**Comment by ndmitchell** [comment]
Good point. It's a historical artefact - when the tutorials were written Shake didn't look for `Shakefile.hs` specially, but should definitely be updated now - thanks!
