### ISSUE TITLE
Add missing replaceDirectory1

### ISSUE THREAD

**Issue by ad-si** [ndmitchell/shake#583]
There is `dropDirectory1` and `takeDirectory1`, but I'm missing `replaceDirectory1`.

```hs
replaceDirectory1 :: FilePath -> String -> FilePath

replaceDirectory1 "root/file.ext" "/directoy" == "/directory/file.ext"
replaceDirectory1 "root/foo/bar/file.ext" "/directory" == "/directory/foo/bar/file.ext"
```

What do you think?

**Comment by ndmitchell** [comment]
Not averse to this - seems like logical extension of what is already there. Is this something you thought about as an obvious logical extension, or did you actually have a need for it?

**Comment by ad-si** [comment]
I actually need it 😛.
I use shake for a blog and I preprocess / optimize all the files:

`source/images/icon.png` => `build/images/icon.png`
...

**Comment by ndmitchell** [comment]
Do you have an implementation already done? If so, want to paste it here (or even a PR, although happy to take it from here). My guess is it's obvious, but always easier to go from tested code.

**Comment by ndmitchell** [comment]
Added.

**Comment by ad-si** [comment]
Sorry, you were too fast for me =P.
Thanks for implementing it!
