### ISSUE TITLE
`getDirectoryDirsIO` should be exposed?

### ISSUE THREAD

**Issue by dented42** [ndmitchell/shake#594]
`getDirectoryDirsIO` looks useful, having it hidden doesn't really make sense when `getDirectoryFilesIO` is exposed.

**Comment by ndmitchell** [comment]
Thanks for the idea. However, my inclination is that `getDirectoryDirsIO` would be better placed in the Extra library, adjacent `listFiles` - https://hackage.haskell.org/package/extra-1.6.6/docs/System-Directory-Extra.html#v:listFiles - likely called `listDirectories`. The reason for exposing `getDirectoryFilesIO` was all the complex filepattern stuff which is much harder to move out of Shake, but the same restrictions don't apply to `listDirectories`. Thoughts?

**Comment by dented42** [comment]
It's simple enough that duplicating it makes a lot of sense, I'd go with that.

**Comment by ndmitchell** [comment]
Added to extra-1.6.8 which I just released, so closing this PR.
