### ISSUE TITLE
Encoding dependency on 1 or more generated file

### ISSUE THREAD

**Issue by theindigamer** [ndmitchell/shake#606]
The documentation on `need` says:

> This function should not be called with wildcards (e.g. `*.txt` - use `getDirectoryFiles` to expand them),

But this "doesn't work" if the files don't exist already -- the returned list is empty.[1] For example,

```
let foogen = "bar" </> "*.foo"
foogen %> const (cmd [Cwd "bar"] "python3 generate.py")
phony "run-myscript" $ do
  need =<< getDirectoryFiles "bar" ["*.foo"]
  -- need trivially succeeds if the files don't exist
  cmd "myscript"
```

Whenever you want to generate some new files and use them, both `myscript` and `generate.py` need to be updated. In the current situation, it seems like the actual file names _also_ need to be hard-coded in the build system (indirectly computing them is not an option because they're generated from scratch, not from some other files).

However, the build system doesn't need to care about this. All it needs to know is that `generate.py` will make 1 or more `.foo` files, which are needed by `myscript` (because `myscript` will anyways fail if it doesn't find the files it needs). Is there a way of encoding predicates in `need`?

You might be wondering: what's the use case here? In my case, the python script is generating some dummy files for benchmarking and the `myscript` is running some benchmarks on them. While `myscript` itself could trigger the generation if the files don't exist, I was considering separating out the logic into the build system so that files always exist when you start running the benchmark.

I suppose one way to "fake" this would be hard-code 1 file name (which we know will not change) and actually generate everything else as well (but don't track the other files). Would you suggest using that approach or something else?

[1] Yes, I realize that `*` encodes 0 or more, so I've put "doesn't work" in quotes.

**Comment by ndmitchell** [comment]
Yes, there is also a note on `getDirectoryFiles` that:

> You should normally only call this function returning source files

So calling it on a file that is generated is a bad plan.

My suggestion is to create a `.stamp` file, so have `gen.stamp` as the thing produced by `python3 generate.py`, and just touch it at the end. Then have `run-myscript` depend on `gen.stamp`. An alternative approach would be to have `generate.py` write to stdout where it put the file. My concern is that if `generate.py` and `myscript` are communicating via files, and the files aren't known, if you don't clean up between runs it's going to give the wrong answer.

**Comment by theindigamer** [comment]
I think I'll hard-code the file names for now, but I can switch over to the stamp solution once there are many files.

> if you don't clean up between runs it's going to give the wrong answer.

That's a good point, I hadn't thought of that at all. Now my code looks like:

```
    phony "generateFoos" $ cmd "python3 generate.py"

    "*.foo" %> \_ -> need ["generateFoos"]

    "generate.py" %> \_ -> need ["generateFoos"]

    phony "run-myscript" $ do
      -- if either thing changes, their rules should fire
      need ["generate.py", "x.foo"]
      cmd "myscript"
```

I'm not sure if I've created a race condition though (because both `need` rules might run in parallel), or whether the two will resolve correctly and run `generateFoos` only once (assuming I modified `generate.py` and deleted `x.foo`).

**Comment by ndmitchell** [comment]
`generateFoos` will be called at most once - there is no race condition. They might run in parallel, but Shake correctly starts each rule with a lock held, then has the other execution wait for it.

**Comment by theindigamer** [comment]
Ah okay. That's one less concern. On a related note, I was at first expecting that command to not re-run `generateFoos` in case both `generate.py` and `x.foo` are unchanged since we last ran `run-myscript`. However, that doesn't seem to be the case. 

1. Is it because `generateFoos` is phony, so it is always counted as "dirty" (hence we must re-build `generate.py` and `x.foo` always)?
2. More generally, if `X` needs `Y` which is phony, then the rule for `Y` will always fire if you transitively have a `need [X]` somewhere?

**Comment by ndmitchell** [comment]
Sorry for not responding earlier, I missed this notification.

1. Yes. Phony rules always rebuild.
2. Yes, Phony rules always change, so depending on a phony ensures ordering (the phony completes first), but otherwise is equivalent to `alwaysRerun`.

**Comment by theindigamer** [comment]
No worries, that resolves it. Thanks!
