### ISSUE TITLE
Composing batching and built in rules

### ISSUE THREAD

**Issue by rohit507** [ndmitchell/shake#610]
TL:DR; I want to create a rule for `apt install` that will batch install operations together for some bootstrap scripts. I have no idea how to actually do this. 

I've got code that can successfully detect whether a package has already been installed, and to run he actual install script, but composing them has me stumped. 

```
newtype AptPkg = AptPkg String
    deriving (Eq, Show, Typeable, Hashable, Binary, NFData)

getPkg :: AptPkg -> String 
getPkg (AptPkg s) = s

type instance RuleResult AptPkg = ()


-- | given a list of packages, splits them into two sets 
--   fst is ones that are installed, snd is those that aren't. 
splitInstalled :: [AptPkg] -> Action ([AptPkg],[AptPkg])
splitInstalled pkgs = ... 

-- | Installs the list of packages available, after filtering out those that are already installed 
batchAptInstall :: [AptPkg] -> Action () 
batchAptInstall pkgs = ...

-- | current attempt at building a general way to add rules that apply to the newtype 
addRuleForm :: (AptPkg -> Action ()) -> Rules () 
addRuleForm evalAction = addBuiltInRule noLint 
    where
        builtInRun :: (AptPkg -> Action ()) 
                   -> AptPkg 
                   -> Maybe ByteString
                   -> Bool 
                   -> Action (RunResult ())
        builtInRun = undefined 

-- | trying to actually write the rule
aptInstallRule :: Rules ()
aptInstallRule = batch 20 addRuleForm return aptInstallMultiple
```

**Comment by typetetris** [comment]
Are you sure, you know how to add new styles/types/sorts of rules? (type is really an overloaded term here, sigh.) Calling addBuiltInRule more then once per sort of rule seems wrong.

Maybe first take a look at [Builtin.hs](src/Test/Builtin.hs). After you something similar like `fileNeed` and `fileRule` defined there, using `batch` will be more obvious.

**Comment by ndmitchell** [comment]
I'd be tempted to keep it simple to start with - define a file rule that builds the file `*.apt` by installing an APT package with the right name - you can then `need ["gcc.apt"]` to install gcc. Then enable batching with the existing `batch` working exactly like it described. Then if you want to get rid of the file, move to `addOracleCache`. Then, only if you want to get really fancy, should you take a look at Builtin rules.

**Comment by ndmitchell** [comment]
I think it just works, hopefully improvements to the docs will have made it easier to follow, but the advice to stay away from builtin rules. I've made that advice more visible in the docs, so hopefully that will push more people towards the simpler end of things.
