### ISSUE TITLE
Describe how to use AutoDeps

### ISSUE THREAD

**Issue by kingofthebongo2008** [ndmitchell/shake#613]
Hello,
When one has a tool that produces artifacts, with msbuild and visualstudio one can hook into the process and record implictly the dependencies.

Like dlls whch this file depends on, what files the tool opens during the transformation and potential outputs. This functionality is important in the context of game development for example, during the so called binarization or cook process, when you produce data from binary files with tools, not typical code compilation, also the tools change quite often there,.

How this can be done in shake in a similar way, sort of automatic dependency generation.

All the best.

**Comment by ndmitchell** [comment]
There is an option to use https://github.com/jacereda/fsatrace with the [`AutoDeps`](https://hackage.haskell.org/package/shake-0.16.4/docs/Development-Shake.html#v:AutoDeps) flag to `cmd` - which you can turn on globally with [`shakeCommandOptions`](https://hackage.haskell.org/package/shake-0.16.4/docs/Development-Shake.html#v:shakeCommandOptions). I confess I haven't really tried this mode much, so it is insufficiently documented and insufficiently tested - but it does have some tests and some docs - so I'd be very keen to know your experiences with it.

**Comment by Neppord** [comment]
@ndmitchell I dont get AutoDeps to work on windows with shake from stack lst-12.11

I try to use it when running (python) nose tests to find which files it should re run the tests for.
```
"report" %> \out -> do
     files <- getDirectoryFiles "" ["//test*.py"]
     need files
     cmd_ AutoDeps (EchoStderr True) (FileStderr out) "python" (["-m", "nose"] ++ file  s)
```
touching one of the test files works, but they are also needed in the action. touching any files used by the test does not allow a rebuild.

running
```
./fsatrace r - -- python -m nose
```
lists the test dependency. so I don't know what I'm doing wrong and why shake don't `needes` the files it should.
