### ISSUE TITLE
Hidden directories and hidden files in getDirectoryFiles 

### ISSUE THREAD

**Issue by minad** [ndmitchell/shake#616]
Hi @ndmitchell,

is it possible to avoid walking inside hidden directories and matching on hidden files with `getDirectoryFiles`? I tried using `getDirectoryFilesIO` with filtering, but this does't yield the desired tracking. And I think calling `need` afterwards on the filtered result is semantically different?

I've seen https://github.com/snowleopard/hadrian/issues/254, where you suggested to use more precise patterns. However I don't think the pattern language is powerful enough to specify such things.
Would it be possible to provide a `getFilteredDirectoryFiles` function?

**Comment by ndmitchell** [comment]
Sorry for not responding sooner, I suspect this got lost in some pile somewhere. Whoops.

You want a getDirectory function based on [getDirectoryFilesIgnore](https://hackage.haskell.org/package/filepattern-0.1.1/docs/System-FilePattern-Directory.html#v:getDirectoryFilesIgnore). Plan is to switch to the `filepattern` library in #550, and then it's trivial, and you can specify files and directories to avoid, efficiently.

**Comment by minad** [comment]
Thank you! Sounds good. When will this be available in shake?

**Comment by ndmitchell** [comment]
The main issue is I want to prove the library in HLint and it's going to take a 0.1 since it changes the semantics of every FilePattern (only slightly).

**Comment by minad** [comment]
Ok no hurry! I think I circumvented the issue I had in other ways, however this would be still nice to have at some point.

**Comment by ndmitchell** [comment]
Merging this in with https://github.com/ndmitchell/shake/issues/540#issuecomment-464360637 since it's turning into an FAQ.
