### ISSUE TITLE
Add a batch that has no max count

### ISSUE THREAD

**Issue by Neppord** [ndmitchell/shake#622]
I like the design of the batch rule but fore some batches I don't care for the maximum number of files to batch, testing and linting.

Currently I'm just setting a high number, the number of files in the project * 2, to use as the max batch size. But it would be nice to have a bachAll rule that gives shake full flexibility to pick as many and as few it think is good.

**Comment by ndmitchell** [comment]
Generally for batch processes the cost is `c +n*m` - where the cost per item is `m`, and there is some `c` constant overhead. It's always the case that if you scale up `n` high enough `c` becomes irrelevant, and that's probably the number you should be aiming for. If you put everything in one batch then Shake can't benefit from any parallelism to optimise things, which can sometimes mean you get higher throughput with lower numbers.

If you really want an unlimited batch then just pass 1000 and it's unlikely you'll ever hit actual splitting in practice.

**Comment by Neppord** [comment]
If I understand it correctly. Shake will break things up in smaller batches even if you put over 9000 as batch size.

I basically want to tell shake that it can break at as big batches as it think is appropriate.

I also don't want my build script to contain numbers with no real meaning. I could create a
``` haskell
largBatch = batch 9000
``` 
function in my script. It seams general enough that others would like it too.

**Comment by ndmitchell** [comment]
Shake will only break things up if it has nothing else to do. If you have 8 threads, it will still try and do 1 huge batch on a single thread. It only breaks up batches if it has literally nothing else to do, in which case it will do a batch with whatever has accumulated thus far.

`batch maxBound` would be the right way to go about it, if you don't want magic numbers. Not sure that will work with overflow, but that might be a nice way out.

**Comment by Neppord** [comment]
Thanks! Yes maxBound is a good enough solution, I'll try it out!

**Comment by ndmitchell** [comment]
The odds of Int overflow are very very high - I'll add it to the test suite and check it works (likely fixing the overflow issues).

**Comment by ndmitchell** [comment]
I wrote a test case which seemed to work fine. An audit showed one place that made me nervous, so I rewrote that to be safe, but I'm pretty sure I convinced myself it was safe before too. So yes, `maxBound` is the way to go.

**Comment by ndmitchell** [comment]
A while. But it's always worked with maxBound, so I think you'll be fine, no need to wait.

FWIW I recommend never to use Stackage LTS, as it delays fixes. http://neilmitchell.blogspot.com/2015/12/whats-point-of-stackage-lts.html

**Comment by Neppord** [comment]
Thanks again! That leads to a second question: how long time does it take for changes in shake to end up in stackage (nightly)? And how do I know that the version I use have the changes I am waiting for :)?

Hypothetical, since as you said I am not waiting for any changes this time :).

**Comment by ndmitchell** [comment]
The timeline of changes is:

* I make them in Shake HEAD, or someone sends a PR I accept
* I release them in a Shake release, which is when I have a good set of useful stuff, but can be immediate if there is any actual demand
* Gets into Stackage Nightly within 1-3 days
* Gets into Stackage LTS either about a week later (I didn't change the API in a backwards incompatible way), or 3-6 months (I did change the API)
