### ISSUE TITLE
Can I use `shakeCloud` in `0.17`?

### ISSUE THREAD

**Issue by jwoudenberg** [ndmitchell/shake#624]
More of a question than an issue: I noticed `0.17` introduces a `shakeCloud` configuration option for setting up shared caches but didn't find it in the other documentation. I imagine this is part of the 'Build Systems a la Carte' work? Exciting! I was curious if this can already be used!

**Comment by ndmitchell** [comment]
Answer is sadly no. Some of it works, but the networking bit isn't implemented, so it's not enough to use. However, shakeShare probably mostly works, if you have a shared directory in common between your builds (either on a single machine, or network mounted for multiple users). Obviously fixing this up for shake 0.17.N is top of the todo list.

**Comment by jwoudenberg** [comment]
This is great, thank you!
