### ISSUE TITLE
Allow `command` / `cmd` / ... to choose the name of the executable used in output

### ISSUE THREAD

**Issue by christianlavoie** [ndmitchell/shake#627]
When running a command in a "subshell" type environment (eg: "stack exec myexec2" or "nix-shell ... --run myexec") the shake stdout will include things like:

```
# nix-shell (for mytarget)
# nix-shell (for mytarget)
# stack (for mytarget2)
```

Sometimes repeated (especially in the `nix-shell` case if multiple commands are used to process an input into an output). It would be useful for `CmdOption` to include something like `StepName` to change that to:

```
# myexec (through nix-shell, for mytarget)
# myexec3 (through nix-shell, for mytarget)
# myexec2 (through stack, for mytarget2)
```

**Comment by ndmitchell** [comment]
Is `Traced` what you want? You should be able to do `Traced "nix-shell mytarget"` or similar. https://hackage.haskell.org/package/shake-0.17/docs/Development-Shake.html#t:CmdOption

**Comment by christianlavoie** [comment]
Doh. Yes.
