### ISSUE TITLE
priority vs deprioritise is confusing

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#629]
The priority function sets the preference of which rule to pick. The deprioritise function takes a running task and reduces its execution priority. Using the same name for both is a bad idea. Should I rename one of them? Renaming deprioritise would be easier since it's newer, but not essential.

My best thought so far is to rename `priority` to `preference`, but I'm welcome to better suggestions.

**Comment by sjakobi** [comment]
> rename `priority` to `preference`

:+1:

**Comment by dwijnand** [comment]
So I just learnt about `priority` and I think (despite doing the rename) I prefer `priority` as the UX for the build author.

How about `renice` for changing the execution priority of tasks?

**Comment by ndmitchell** [comment]
Great thing about the rename is that it's still not made it into a release, so we've got plenty of scope to change it now.

What's your reasoning about preferring `priority` to `preference`? I saw CSS does it with priority, e.g. http://qnimate.com/dive-into-css-specificity/. But I tend to associate `priority` with a more dynamic sense of execution than `preference`.

I like the idea of `renice`, but worry it's baking Unix-style knowledge in. How many Haskell programmers know what `nice` is? Of web devs? (Genuine question - I have no idea how much of what I know is arcane knowledge of standard terms...) Another option in that vein is `reschedule`, which has the advantage of making it explicit that you can't boost the priority, you can only `reschedule` with a priority that isn't "now".

I think my preference would therefore be `priority` goes  back to how it was, but what used to be `deprioritise` becomes `reschedule`? Thoughts?

**Comment by dwijnand** [comment]
Even. Better.  Nice one.

WRT preference, maybe it's just me, but it gave me a snobby, upper-class feel, where Sir Shake has a _preference_ for rules written like this over rules that look like that...  I dunno. :-)
