### ISSUE TITLE
Performance hit with many cores

### ISSUE THREAD

**Issue by guillaumecherel** [ndmitchell/shake#633]
Performance seems to decrease when using many cores. I am trying to run shake on a 64 cores machine, and each build rule seems to take much longer (3 times or more) than they to when I turn off parallelism by removing the -threaded option.

To investigate, I've tried building 4 targets using 64 cores. Each target can be run in parallel. I expected that I would see only 4 cores active only with htop. Instead, many (30-40) cores were being used. I'm taking it as a clue that the overhead comes from Shake spawning many threads (i.e. not just 1 thread per rule as I naively expected), and that the performance hit comes from them being divided among many cores. (I'm not familiar with how threads distribution on multiple cores plays with performance.)

Does my guess make any sense? If so, is there a way to control the distribution of threads on cores? I'm not quite sure how to approach this, but I'm thinking of something like: Do all of shake's internal book-keeping and machinery on a single core (or thread) to avoid the performance hit from dispatching many threads on many cores, but still dispatch individual build rules on other cores.

As recommended, I've used the options `-threaded -rtsopts "-with-rtsopts=-I0 -qg -qb"`

**Comment by ndmitchell** [comment]
Oh dear - sadly I don't have 64 cores to test! What is your `-j` setting? `-j64`? Or `-j4`?

> Instead, many (30-40) cores were being used.

Do you mean that 30-40 cores were being used simultaneously? Or over the course of an execution there are on average 4, but that they migrate between 40 cores.

Shake uses the GHC Haskell compiler. The way it works is the GHC runtime spawns N threads (equivalent to whatever you pass as `-j`), then treats the Shake threads as green threads a. Shake doesn't spawn all that many threads - but it isn't super careful about avoiding killing/respawning new threads if there is temporarily no work to do. Shake could spawn its threads with `forkOn`, which ties them to one OS thread, but I would hope GHC's scheduler is smart enough not to require that.

Are most of your Shake rules running external commands? If so, running without `-threaded` won't necessarily disable parallelism. Trying no `-threaded` and `-j40` or similar might still get reasonable parallelism, while pinning GHC/Shake to only one thread.

**Comment by guillaumecherel** [comment]
My setting was -j64, and explicitly running shake passing 4 targets as command line arguments. The 30-40 cores were used simultaneously. Also probably important, each core wasn't being used at 100% but much less, around 50%.

These shake rules don't run external processes. They perform pure computations and write their results to files. Could it be that ghc takes advantage of the multiple cores to split computation between them in a way that is suboptimal, even though I don't use any parallelism/concurrency like Control.Parallel or Control.Concurrent?

I will run it with -j40 and the profiling options to watch for the number of threads created. Do you think it can help?

**Comment by ndmitchell** [comment]
Do these 4 targets have dependencies? Do they have dependencies that fan out? If you pass -j64 and use a parallel `need` or similar Shake will take advantage of additional parallelism. Generally GHC won't use speculatively parallelism unless you explicitly ask for it.

If you run Shake with `--timing` what does the `Pool finished` line say? That should say how many threads the pool went through, and what was the peak number of threads Shake was using at one time.

**Comment by guillaumecherel** [comment]
The targets don't have any dependencies.

I ran it again with --timing and the RTS option -s to get garbage collection info, pasted below. It seems that only 7 threads were used, if I read it right? And the cpu usage was even less than I thought, less than 20%, very variable. Could it be that the threads keep bouncing from one core to another, resulting in the many cores being used only for a short time or below their maximum capacity? Could that reduce performance?

```
shakeArgsWith                     0.001s    0%
Function shake                    1.229s    0%
Database read                     0.035s    0%
With database                     0.002s    0%
Running rules                   254.683s   99%  =========================
Pool finished (7 threads, 5 max)  0.002s    0%
Total                           255.950s  100%
Build completed in 4:16m

  89,195,215,672 bytes allocated in the heap
          17,512 bytes copied during GC
         889,320 bytes maximum residency (1 sample(s))
         605,720 bytes maximum slop
           67612 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         1 colls,     0 par    1.147s   1.606s     1.6061s    1.6061s
  Gen  1         1 colls,     0 par    0.221s   0.321s     0.3214s    0.3214s

  TASKS: 136 (1 bound, 135 peak workers (135 total), using -N64)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    1.588s  (  0.117s elapsed)
  MUT     time  758.857s  (258.244s elapsed)
  GC      time    1.367s  (  1.927s elapsed)
  EXIT    time    0.027s  (  0.008s elapsed)
  Total   time  761.839s  (260.296s elapsed)

  Alloc rate    117,538,859 bytes per MUT second

  Productivity  99.6% of total user, 99.2% of total elapsed

gc_alloc_block_sync: 0
whitehole_spin: 0
gen[0].sync: 0
gen[1].sync: 0

real    4m25.686s
user    12m41.874s
sys     3m9.286s

```

**Comment by guillaumecherel** [comment]
I've just seen some improvement with the RTS option -qa, which tries to pin a thread to a core (https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-concurrent.html#rts-options-for-smp-parallelism). I'm guessing that the performance drop comes from threads bouncing between cores. I will test more and report here later.

**Comment by guillaumecherel** [comment]
So, indeed, running shake with `+RTS -qa -RTS`, I see 4 cores running at 100%. The 4 tasks with -j64 took more than 4min to be built without `-qa`. With it, it takes about 2 min.

Now, when I increase the number of rules to build, more than the 64 cores can handle, (say hundreds), I see those 64 cores being used but only at about 40%. I'm not sure where that may come from, probably not from threads load-balancing anymore. I am not sure that I'll investigate much further, but any idea is welcome.

**Comment by guillaumecherel** [comment]
It's worse than I thought. Running 4 of my jobs sequentially with -j1 runs faster than running them in parallel with -j4. (1min 42s vs 3min 48s). I'm completely confused, no idea where to go from there.
 
But it doesn't seem to be a problem with shake. I've tried with simple rules that just sum a very big list with `foldl' (+) 0 [1..1e7]` and write the result to files. Those rules behave well in parallel: it actually more efficient using 4 cores than 1. So the problem has to lie somewhere in the nature of the computations that I am doing, related to memory management or something like that. I think we can close this issue.

**Comment by ndmitchell** [comment]
I'd recommend running with `+RTS -s` both ways around. That might shed light if one is doing more GC than the other.

**Comment by guillaumecherel** [comment]
Thanks, I'll look into it. I did what I probably should have tried to begin with, I ran those computations in parallel without shake, trying both Control.Concurrent and Control.Parallel, and the problem persists. It's obviously unrelated to shake, so I'm closing this issue. Thank you for your help!

**Comment by ndmitchell** [comment]
Thanks for letting me know - good luck! If the solution you find is generally applicable let me know - I have a feeling other Haskell heavy shake users might hit it.
