### ISSUE TITLE
Allow arbitrary transformations after deserialization from shake database

### ISSUE THREAD

**Issue by afranchuk** [ndmitchell/shake#637]
I'm using a custom builtin rule through which almost all operations are performed. It's worked well up to this point, but I'm in the midst of a refactor and having a tricky time.

Previously, the data which was used as a key for the custom rule had a type field, which was a normal sum type (and rather extensive). I wanted to make this more modular by breaking up that sum type to be separate types defined in separate modules. This immediately causes problems because the binary deserialization needs to know the type it's deserializing. I had been using static pointers previously to solve this (as the key type also contains arbitrary data unrelated to type), and I know that works (P.S. thanks for your post on just that problem). However, I wanted to move away from the static pointers and instead try to use a registry of types indexed by UUID, and serialized with that ID. The trouble is that the Binary.get implementation must be pure, so there's no opportunity for my code to post-process the loaded data to properly lookup by uuid and deserialize the "untyped" data.

I have been trying to work around this, and thought I had a solution that would work, but something is amiss and the deserialization is failing in a non-obvious way.

The shake database does not allow users to insert some operation between deserialization and hashing/equality checking. If there was a way to set such an operation, it would solve my problem. I'm thinking it would be most appropriate to specify such an operation with `addBuiltinRule`. Otherwise, I might just go back to using static pointers, because that did at least work before.

**Comment by ndmitchell** [comment]
I guess my first question would be why you don't have multiple rules? It seems if you are doing registry etc you are duplicating something Shake itself is doing, and which is pretty difficult to do correctly, so might as well steal from Shake.

Is your code available anywhere, or is it private?

**Comment by afranchuk** [comment]
It is private unfortunately. I understand your point, and it's a bit difficult to explain, but it does require a single builtin rule for this, as there is shared information that must be present for all keys (i.e. there is one key type which contains 'sub-keys' of sorts). Internally the implementation is using a few builtin rules, but there is a single rule that all client code uses. Basically, I've built up a library over shake which more accurately stores and uses arbitrary information about intermediate results (as opposed to just interacting with files). I suppose I could flip that: allow client code to key off of arbitrary data (make their own rules), and make a type class to pull the shared information out. But that would imply a decent amount of boilerplate for clients, and probably some other things I haven't thought of yet.

FYI I did just now find the small bug that was preventing the type registration to deserialize properly in some cases, so it is working. However, my original request still stands, because (for instance) now the `Show` instance doesn't have enough information to `show` correctly before the extra information is deserialized. It seems like the `show` always uses the deserialized key data rather than the runtime-constructed key which matched it. Would it be possible to prefer/use the runtime-constructed key instead?

Also note that technically, because the builtin rule **result** is passed as just a bytestring, doing this sort of thing on the result type *is* possible since the implementer controls the deserialization. But I realize that case is simpler than the key case since the key is used in a hashmap.

**Comment by afranchuk** [comment]
For the time being, I ended up putting some `unsafePerformIO` in the `Binary` instances to access the registry of dynamic types (I realized I didn't need to go back to static pointers regardless). It works well now. But it would be nice to achieve the same thing without doing unsafe IO. In this case it's going to be safe because it's only doing reads of an IORef during `Actions`, which won't change beyond the initial `Rules` evaluation.

**Comment by ndmitchell** [comment]
Is https://hackage.haskell.org/package/shake-0.17.3/docs/src/Development.Shake.Internal.Core.Rules.html#addBuiltinRuleInternal addBuiltinRuleInternal what you're after? The BinaryOp is basically a ByteString to and from value.

**Comment by afranchuk** [comment]
Actually yeah, that's exactly what I'd like to have. That would allow me to define deserialization that used the state built up before adding the built-in rules.

**Comment by ndmitchell** [comment]
Next question is whether it should be a variant of that which works on `Binary` types `Get` and `Put`, one that works on ByteString directly, or something else?

**Comment by afranchuk** [comment]
Good question. I guess since the value/answer functionality gives a `ByteString` to decode, it might be consistent to also have the variant operate on `ByteString`s directly. Though I was wondering why `BuiltinRun` provides a `ByteString` as opposed to an `Either String value` where the `Left` is the `decodeOrFail` error string.

**Comment by ndmitchell** [comment]
`BuiltinRun` doesn't require `Binary`, and all the Shake internal rules don't use it, preferring more efficient storage solutions. Some literally shuffle the bytes around manually.

**Comment by afranchuk** [comment]
Ah I see, makes sense.

**Comment by ndmitchell** [comment]
So I don't have a good name for this function, and I don't have a good type for it, being somewhat torn between Binary instance types and direct ByteString types, when the actual real types underneath aren't ones I want to expose. Given all the uncertainty, and a reasonable (but very grim) path of a global IORef, I am starting to wonder if it's worth doing. Although that may be a way of saying "I wonder if other peoples pain matters less than my own"... I'd appreciate your viewpoint.

**Comment by ndmitchell** [comment]
There is a solution, it could be cleaner, but I suspect it's a rare problem. Closing for now, but do shout if it causes ongoing pain.
