### ISSUE TITLE
Choose a better color when Shake warns about database rule changes

### ISSUE THREAD

**Issue by thoughtpolice** [ndmitchell/shake#640]
When database rules change, Shake will rerun rules affected by that. However, when using `--color` to make the output pretty, *everything* is printed in blue, including my rules and the warning:

```shell
./shake.hs --color
Shake database rules have changed for the following types:
  File:  .shake/.shake.database
  Type:  OracleQ Config {7daca85a005f975e}
  Type:  OracleQ ConfigKeys {3cf7c26d5ae5e884}
All rules using these types will be rebuilt

...
```

This is pretty easy to miss, especially if your build has a lot of rules you didn't expect to rebuild. It would be nice if this was a distinct color in the terminal output (for example, yellow.)

**Comment by dwijnand** [comment]
Sadly, I can't find any docs on database rules.

If someone could provide a minimal reproduction of the behaviour described here I'd be willing to take a swing at improving it.

**Comment by ndmitchell** [comment]
If you add an oracle with addOracle, run a build that uses that oracle, then remove that call to addOracle, you should reproduce this error. Agree it should be a more prominent colour. 

Other related colour is if you have shakeVersion of "x" and change it to "y" then I suspect you want more prominent colour (I think there is another ticket for that)
