### ISSUE TITLE
Flag to detect file creation

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#642]
Perhaps a flag `--poison=foo.txt` which fails any rule that produces a file `foo.txt` would be useful to get cloud builds work. Likely the problem is that you fail to declare a `produces`, and using `--poison` plus `-j1` you could detect what that was.

CC @snowleopard

**Comment by snowleopard** [comment]
Running Shake with `--poison=foo.txt -j1` looks like the right solution to me. 

I think this feature is generally useful (not just for cloud builds). The question: "Who put this file here?" comes up quite often in my experience.

**Comment by ndmitchell** [comment]
I guess all it needs is a good flag name then...

**Comment by snowleopard** [comment]
I think I'm fine with `--poison`, although it could also be `--blame`, `--locate`, `--finger`, `--whereis`, etc :)

**Comment by ndmitchell** [comment]
I added `--lint-watch` which takes a pattern and on every rule that completes scans for the pattern. The more precise the file, the less scanning it has to do, so be nice to Shake...
