### ISSUE TITLE
Internal error from --shared

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#646]
@snowleopard reports:

```
Got: Development.Shake: Internal error, please report to Neil Mitchell (File.ruleIdentity has no result for _build/test/ghcconfig)
src/Development/Shake/Internal/Rules/File.hs:207:30-94:
```

Reading into the code, that means the answer to this file is Nothing. That should only be the case for `phony` rules, but it doesn't seem to be the case here. So first question is what type of file is `_build/test/ghcconfig`? Is it a source file? Generated? If so, where is the rule that generates it?

I added a test that `--shared` works with phony, and updated the comments in a few places based on more thorough understanding.

**Comment by ndmitchell** [comment]
My hunch is it's https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Internal/Rules/File.hs#L307 at fault, as that gives you an answer phony without disabling the history. Need to figure out how you get to that line...

**Comment by ndmitchell** [comment]
Looking at line 307, it only comes into play if check creation is disabled, which is only really done for compatibility with Ninja, so I doubt anyone is even aware of it. There was a bug there, which I fixed, but I very much doubt it's what @snowleopard hit.

**Comment by snowleopard** [comment]
@ndmitchell In case this helps, here is the build rule for `_build/test/ghcconfig`:

https://gitlab.haskell.org/ghc/ghc/blob/180c9762d4565f0e8b192abf95d2bed57765e0c5/hadrian/src/Rules/Test.hs#L36

**Comment by ndmitchell** [comment]
Thanks, I think a phony rule you depend on probably causes this issue. I'll figure out what the invariant is I'm violating.

**Comment by ndmitchell** [comment]
I'm pretty sure this code breaks if you have a phony rule you depend on. In your case, you depend on `_build/test/ghcconfig` and it's a phony. But that's a terrible thing to do! Essentially every time around it recomputes `_build/test/ghcconfig`, and everything that depends on it reruns too. As a first approximation, never depend on a phony.

All three rules in https://gitlab.haskell.org/ghc/ghc/blob/180c9762d4565f0e8b192abf95d2bed57765e0c5/hadrian/src/Rules/Test.hs#L30-42 look like someone really liked the `~>` operator, but should have actually been using `%>`, perhaps in conjunction with `alwaysRerun`.

**Comment by snowleopard** [comment]
@ndmitchell Ouch, I'm not sure how this sneaked past my review.

I'm pretty sure this was unintended -- simply a novice Shake user typing in a wrong operator, perhaps, simply by copying the existing phony rule `test`.

**Comment by snowleopard** [comment]
> As a first approximation, never depend on a phony.

Perhaps, you can flag this in Lint mode?

**Comment by ndmitchell** [comment]
Another option would be lint warning about a file that exists and also is a phony. The problem is, both these things are possible, and sometimes having one phony depend on another isn't a terrible idea, and due to composition, I can't really tell the two apart.

**Comment by ndmitchell** [comment]
I think having more diagnostics in profile mode, e.g. saying this rule will always rerun, and these things will always rerun etc, so highlighting the always repeating part of the build.

**Comment by ndmitchell** [comment]
You can now depend on a phony in a shared rule. I still wouldn't, but hey...
