### ISSUE TITLE
cmd fails to run programs with spaces in the path

### ISSUE THREAD

**Issue by alpmestan** [ndmitchell/shake#647]
Consider the fofllowing trivial "build system":

``` haskell
import Development.Shake
import System.FilePath

main :: IO ()
main = shakeArgs shakeOptions $ do
  shellFile1 %> \_ -> writeFile' shellFile1 (shellScript 1)
                   >> cmd "chmod +x" [shellFile1]
  textFile1 %> \_ -> need [shellFile1] >> cmd shellFile1

  shellFile2 %> \_ -> writeFile' shellFile2 (shellScript 2)
                   >> cmd "chmod +x" [shellFile2]
  textFile2 %> \_ -> need [shellFile2] >> cmd shellFile2

dir1, dir2 :: FilePath
dir1 = "some dir with spaces"
dir2 = "somedirwithoutspaces"

textFile1, textFile2 :: FilePath
textFile1 = "foo1.txt"
textFile2 = "foo2.txt"

shellFile1, shellFile2 :: FilePath
shellFile1 = dir1 </> "foo.sh"
shellFile2 = dir2 </> "foo.sh"

shellScript :: Int -> String
shellScript n = unlines
  [ "#!/usr/bin/env sh"
  , "echo hello > foo" ++ show n ++ ".txt"
  ]
```

Asking for `foo1.txt` doesn't work, but asking for `foo2.txt` does, as you can see below.

``` sh
$ ./shake-bug foo1.txt
# chmod (for some dir with spaces/foo.sh)
# some (for foo1.txt)
Error when running Shake build system:
  at src/Development/Shake/Internal/Args.hs:81:69-79:
* Depends on: foo1.txt
* Raised the exception:
some: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

$ ./shake-bug foo2.txt
# chmod (for somedirwithoutspaces/foo.sh)
# foo.sh (for foo2.txt)
Build completed in 0.00s
```

We can make the `foo1.txt` case work by doing something like `cmd [Cwd dir1] "foo.sh"` (but we then have to say that we want to generate `foo.txt` "one level up", in the parent dir). Without that workaround, Shake apparently won't escape the command properly when running it, but it will escape the directory properly when `cd`ing into it. This has bitten me a few times in Hadrian but I never took the time to write a small reproducer until today.

i'd classify this as a bug, as I'd expect Shake to do the right thing for the command to be executed properly whether it contains spaces or not. Do let me know if you disagree. :-)

**Comment by ndmitchell** [comment]
Does `need [shellFile2] >> cmd [shellFile2]` work - namely putting square brackets around the `shellFile2` in `cmd`? If so, I'll explain why.

**Comment by alpmestan** [comment]
You meant `shellFile1` (since `dir1` is the one with spaces in it) I suppose. And yes, that surprisingly (to me) fixes it!

**Comment by ndmitchell** [comment]
The existing documentation attempts to explain that, see https://hackage.haskell.org/package/shake-0.17.5/docs/Development-Shake.html#v:cmd.

I've given it a tidy up, so it now says much higher up:

```
--   Typically only string literals should be passed as @String@ arguments. When using variables
--   prefer @[myvar]@ so that if @myvar@ contains spaces they are properly escaped.
```

Is that now clear to you? If not, what would make it clear?

**Comment by alpmestan** [comment]
It is a lot clearer now, indeed, thanks!

Are you however not convinced that it's `cmd`'s job to look at the command it's issuing and to escape it properly whenever appropriate, and not the user's? I obviously am, but if you're not then we can close this issue.

**Comment by ndmitchell** [comment]
It's really handy to write `cmd "stack run hadrian -- --help"` without having to do `cmd "stack" "run" "hadrian" "--" "--help"` or `cmd ["stack","run","hadrian","--","--help"]`. In both second cases you can see a lot more gunk than the standard command line you'd write in the shell. I don't know of any way to get the auto-escaping when you want it, but not when you don't. The `String` vs `[String]` distinction is pretty effective in practice, albeit a little surprising.

**Comment by alpmestan** [comment]
I see your point, fair enough.
