### ISSUE TITLE
Inspect and modify the shared cache

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#649]
Currently you may wish to:

* See what is in a cache file.
* Delete a specific cached entry, or a pattern describing cached entries.

**Comment by ndmitchell** [comment]
CC @snowleopard

**Comment by ndmitchell** [comment]
See `--share-list` to get a dump of what is in the shared drive, and `--share-remove=Foo` to delete all keys with `Foo` as a substring.

**Comment by snowleopard** [comment]
Awesome, thanks!
