### ISSUE TITLE
Run shake without GHC installed

### ISSUE THREAD

**Issue by joneshf** [ndmitchell/shake#655]
I'd like to use shake in more places (different CIs, other people's machines, etc.), but it seems like it needs GHC in order to run. Forcing GHC to be installed makes using shake a non-trivial thing to do. Is there a way to run shake without requiring GHC be available on the machine? Ideally, there would be a single `shake` binary that someone could put on a machine and it would execute a `Shakefile.hs` or whatever.

**Comment by ndmitchell** [comment]
Given a Shakefile.hs you can compile it with `ghc Shakefile.hs` and then distribute the resulting binary. Is that what you are after?

**Comment by joneshf** [comment]
I'm not sure. Would that binary be able to dynamically change what it does based on the rules in another `Shakefile.hs`, or is its behavior statically the same based on the `Shakefile.hs` it was compiled from? I'm hoping for a workflow similar to how someone might use a `Makefile`: change a recipe, push to CI, it runs the new recipe with the same old `make` binary.

**Comment by ndmitchell** [comment]
Unfortunately the build script itself is written in Haskell, so there's no real chance of compiling the Shakefile.hs without a Haskell compiler. If you want to avoid that problem, you might want to write your own build system using Shake, which evaluates a simpler non-Haskell configuration language in the most case. I gave a talk about this a while back - https://ndmitchell.com/#shake_09_oct_2015 - e.g. slides at https://ndmitchell.com/downloads/slides-defining_your_own_build_system_with_shake-09_oct_2015.pdf, about slide 12.

**Comment by joneshf** [comment]
I think that will work. Thanks!
