### ISSUE TITLE
Shake 0.7.17 doesn't work with GHC<=7.8.4

### ISSUE THREAD

**Issue by vmchale** [ndmitchell/shake#659]
Visible on the Hackage matrix [here](https://matrix.hackage.haskell.org/#/package/shake).

**Comment by kirbyfan64** [comment]
#651

**Comment by vmchale** [comment]
The problem is that the package bounds were not restricted, so this causes build failures.

**Comment by ndmitchell** [comment]
Thanks, I've restricted the bounds on base in the source, and made a Cabal revision as well.
