### ISSUE TITLE
Merging share caches?

### ISSUE THREAD

**Issue by adamse** [ndmitchell/shake#671]
The [docs][1] suggest using rsync to distribute/share the share cache so we implemented a scheme where users & ci use rsync to read and write to a single global location.

It seems that this strategy is incompatible with the current on-disk layout for the cache, which I think looks like this:

```
cache/<hash-of-rule-key>/: the rule key is usually the filename for the rule?
  _key: [Entry]. Entry is the rule key, version, dependencies etc.
  <hash-of-result-file-1>: contents of result-file-1
  ...
```

Saving a result to the cache appends to _key and stores the files produced.

The problem is that when CI wants to write back into the global cache it will overwrite any entries in `_key` added since it last rsynced.

Is this correct? What can we do to support this use-case?

[1]: https://github.com/ndmitchell/shake/blob/master/docs/Cloud.md

**Comment by ndmitchell** [comment]
Hmm, very true. The rule key is indeed usually the filename for that rule. The `_key` file is a list of `[Entry]`. As you can see in https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Internal/History/Shared.hs#L122, the file is basically a sequence of blocks, so if you just append two files together, that still forms a valid file. Of course, then you end up with duplicates, which would duplicate without end if you aren't careful. Of course, you could then deduplicate. That leads to a few options:

* If you copy the key files specially, and append, you can then dedupe on loading the file (if you see duplicates then write out a fresh non-dupe version) or have a --dedupe flag.
* If copying with appending for those is a pain, you could imagine a merge flag that merges two sets of keys, finding them nearby somehow.

What makes sense with rsync or similar?

**Comment by adamse** [comment]
rsync does have a `--append` flag but I don't think that will do what we want, so plain rsync will not be sufficient here. 

So either we:

- Change the on disk format to something rsync compatible
- Write a little tool to do proper merging according to the current format. Where either strategy you suggest could be incorporated.

**Comment by ndmitchell** [comment]
At the moment the key file is the one that is a list, everything else is a blob. To change it to be rsync compatible we'd want to change the key to be a directory, and store things by some hash. Finding an entry would then require a `getDirectoryContents` and opening many files, but you'd be rsync compatible. Simplicity and rsync compatible, but potentially slower IO. My inclination is to make that change, and then later, if the IO starts to dominate, do something about it. Seem a reasonable approach?

**Comment by adamse** [comment]
That seems like a good approach!

**Comment by ndmitchell** [comment]
The cache should now be rsync-mergeable. Let me know if it's not, or if I screwed something else up in the process.

**Comment by adamse** [comment]
Thanks! We'll let you know how it goes!
