### ISSUE TITLE
Cannot run shake when build using cabal v2-* in windows

### ISSUE THREAD

**Issue by Rizary** [ndmitchell/shake#677]
I use windows to develop haskell project, and choose cabal instead of stack at the moment.

I got an error when running `shake.exe --help` which shows `shake.exe: Could not find 'build.ninja'`

Step to reproduce:
1. Install ghc and cabal-install using `chocolatey`
2. Clone shake repo
3. build shake using `cabal v2-build`
4. run `shake.exe --help`

However, I can run `cabal v2-run shake --help` smoothly but not the `--demo` option (as I refer to shake's documentation).

 running `shake.exe --demo` after building it using `cabal v2-build` comes with an error:
```
% Welcome to the Shake v0.17.9 demo mode!
% Detecting machine configuration... WARNING: cache is out of date: C:/ProgramData/chocolatey/lib/ghc/tools/ghc-8.0.2\lib\package.conf.d\package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
done

% You don't have the 'shake' library installed with GHC, which is required to run the demo.
```

the weird thing is I have 3 ghc installed in the `C:/ProgramData/chocolatey/lib/ghc/tools/` which is ghc-8.0.2, ghc-8.2.2, and ghc-8.4.3.

**Comment by ndmitchell** [comment]
To fix the demo issue try running "ghc-pkg recache". It does look like your package cache needs updating.

For the first issue, I suspect that's now standard behaviour- but not good behaviour. I'll have a go at doing better.

**Comment by ndmitchell** [comment]
I fixed the second issue so it now displays the help. Thanks for the report.

**Comment by Rizary** [comment]
@ndmitchell thanks.. i will look into it again..
