### ISSUE TITLE
How to soft assert?

### ISSUE THREAD

**Issue by mcandre** [ndmitchell/shake#684]
Hi, I'm a fan of Shake and love how it helps to ensure my Haskell projects build more reliably on different platforms!

One thing I am curious about with Shake is how to write tasks as soft assertions. For example, what syntax could I use so that a task tree called `lint` with several child linter shell commands, allows the full linter suite to run in the event of any error codes, and only reports the error code at the very end of the `lint` execution?

**Comment by ndmitchell** [comment]
Sorry I missed this question entirely (I think I was on holiday and it must have got buried in my inbox).

To do something like a linter that runs multiple linters I'd make each of the linters always succeed, and put their output (exit code, list of errors) into a file. Then I'd write a top-level (probably `phony`) target that does `need` on all those linters and, if any have errors, report them.

The other approach is to use `--keep-going`  which means that any errors aren't reported immediately, but are reported once everything else finishes.

**Comment by ndmitchell** [comment]
I think https://stackoverflow.com/questions/36889699/detect-errors-and-build-report-in-case-of-failure-in-shake-build/36917779#36917779 answers this question too.
