### ISSUE TITLE
suggestion: allow adding 'extra help' to --help output

### ISSUE THREAD

**Issue by thoughtpolice** [ndmitchell/shake#689]
I have some extra options and target descriptions in my build tool, so the output of `--help` looks like this:

```
./bake.hs --help
...
Extra options:
  --way=WAY                   Set the build 'way'
  --mix=[MIXES...]            Set the build mixes that are included in the 'way'

Targets:
  - clean - Clean all build objects
  - build/debug/src/testing/testing
  - build/debug/src/testing/*.c.o
  - build/debug/src/testing/*.p.h
  - build/debug/src/testing/*.p.o
  - build/release/src/testing/testing
  - build/release/src/testing/*.c.o
  - build/release/src/testing/*.p.h
  - build/release/src/testing/*.p.o
  - all - Build all default targets
  - test - Run the test suite
```

I would like the ability to add *another* section to the help output here, after the `Targets` output, in order to help users a bit more about how to invoke targets and options. Something like:

```
User information:

There are multiple ways to invoke a build...
```

Why do this? In my case, the `--way` and `--mix` options are somewhat complicated to explain inline in the `GetOpt` documentation; notably they can have comma/additive syntax (for instance, `--way=debug,release --mix=asan+lto,ubsan` is a valid incantation that builds the cartesian product of `(Way, [Mix])` variations).

I would like to also indicate to the user things like "what environment variables can impact the build", and so on and so forth, and this seems like a reasonable place to explain it as well. (In theory depending on how it's set up, maybe you could even do things like dump the output of `HashMap String String` for the config files you loaded during the `Rule` phase -- perhaps, so that users can see what build configuration options might be impacting them when they run `--help`)

I suppose simply adding a phony `help` target would also work here, since it would also be listed in the target output under `--help`, so if this seems unnecessary I'm fine with doing that too.

**Comment by ndmitchell** [comment]
Seems reasonable to add something. Does `addHelpSuffix :: String -> Rules ()` seem to fit the model?

**Comment by thoughtpolice** [comment]
That would work well for me!

**Comment by ndmitchell** [comment]
PR most welcome.
