### ISSUE TITLE
Make '-j0' the default for the 'shake' executable

### ISSUE THREAD

**Issue by thoughtpolice** [ndmitchell/shake#690]
I'm currently using Shake's Ninja compatibility to build a CMake project at work (and it's even faster than ninja at full rebuilds!) However, I constantly need to remember to pass `-j` to the command line to make it use all my cores, while `ninja` does this automatically by default. This is a huge competitive advantage that's being ignored! So, I would like to propose enabling `-j0` by default for the shake executable only.

Unfortunately, `Run.main` already launches `shake` with `shakeThreads=1` (the default) by the time it looks for `build.ninja`, but I think just setting it `=0` anyway is fine, probably? I guess if you ever expected to add other language compat shims, it would mean they all use parallelism by default, I suppose...

**Comment by ndmitchell** [comment]
I thought Ninja used `-j1` by default? Hence I was copying Ninja. But yeah, change it to shakeThreads=0 - I'm happy with that. PR welcome.

**Comment by thoughtpolice** [comment]
Actually, ninja does even more than that: it picks `ncpus + 2` for all `ncpus > 2`, see [here](https://github.com/ninja-build/ninja/blob/master/src/ninja.cc). This is used to set the default `config->parallelism` setting. With `-j` it actually uses `INT_MAX`, I assume, because it restricts the total number of outstanding jobs anyway during build so it doesn't run haywire.

For reader reference, `-j0` in Shake causes it to parse `/proc/cpuinfo` in order to get the number of cores. Everything else aside, I think this is a better and more sensible choice, so `-j0` by default sounds good to me.

---

Side note: perhaps oversubscription is what is partially causing the disparity between `shake` and `ninja` in my case. Though oversubscription in theory is supposed to help, I think it's actually pretty build dependent: the core assumption is some I/O paths will hold up threads, meaning 1 or two extra will mop up those I/O paths while other CPUs can continue by being rescheduled. But hard drives are really fast these days, so there isn't as much time spent waiting on I/O (a scheduler could reasonably determine to let the I/O complete rather than reschedule.) In our case, we have lots of relatively small objects and no gigantic link times, so the I/O requirements are very meager. Meaning you can probably just flat out oversubscribe the machine with too many CPU-bound jobs. In my case, `-j4` (number of CPUs) and `-j5` give no meaningful timing difference.

**Comment by joneshf** [comment]
> Actually, ninja does even more than that: it picks `ncpus + 2` for all `ncpus > 2`, see [here](https://github.com/ninja-build/ninja/blob/master/src/ninja.cc).

Do you mean the [`GuessParallelism`](https://github.com/ninja-build/ninja/blob/e0bc2e5fd9036a31d507881e1383adde3672aaef/src/ninja.cc#L227-L238) function?

**Comment by thoughtpolice** [comment]
Yes, fixed!

**Comment by ndmitchell** [comment]
Thanks for the detective work and PR! I guess Ninja changed since I last checked. My experience is that over parallelising when you have more than 1 IO job is particularly terrible. Shake uses a random thread pool, which I suspect is at least helping with the Ninja performance - otherwise you can end up queuing up all CPU jobs followed by all IO jobs, whereas any random interleaving is probably "not too bad".
