### ISSUE TITLE
getDirectoryFiles is stale if a directory is deleted but it was in shake cache

### ISSUE THREAD

**Issue by louispan** [ndmitchell/shake#729]
I may be misunderstanding `getDirectoryFiles` and `getDirectoryFilesIO` or how to use Shake, but it appears not to contain recent file changes in preceding actions, if:

* an action depends on a file inside a directory,
* shake has run successfully for that action before (cached)
* that directory is then deleted from the filesystem
* if the shake build is executed, and a action recreates that deleted directory
* Then getDirectoryFiles doesn't see the recreated directory

https://github.com/louispan/shaketest is a minimal example to reproduce.

# Steps to reproduce

First build is ok
```
./build.sh
```
```
Up to date
# mkdir (for foo/.bar)
["LICENSE","Setup.hs","Shaketest.hs","build.sh","cabal.project","shaketest.cabal"]
# touch (for foo/.bar)
Build completed in 0.01s
```

try again - no work to do - OK
```
./build.sh
```
```
Up to date
Build completed in 0.01s
```

delete foo - shake is expected to regenerate foo directory
But shake doesn't see "foo", and getDirectoryFilesIO also doesn't see "foo"
```
rm -rf foo
./build.sh
```
```
Up to date
# mkdir (for foo/.bar)
["LICENSE","Setup.hs","Shaketest.hs","build.sh","cabal.project","shaketest.cabal"]
Error when running Shake build system:
  at want, called at Shaketest.hs:6:5 in main:Main
* Depends on: foo/.bar
* Depends on: getDirectoryFiles foo [*/.bar]
* Raised the exception:
foo: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

But foo was created
```
ls -1 | grep foo
```
```
foo
```

Running build.sh again works
```
./build.sh
```
```
Up to date
# mkdir (for foo/.bar)
["LICENSE","Setup.hs","Shaketest.hs","build.sh","cabal.project","shaketest.cabal"]
# touch (for foo/.bar)
Build completed in 0.01s
```

Trying again but also delete .shake cache
Shake build ok if .shake cache is also deleted
```
rm -rf foo
rm -rf .shake
./build.sh
```
```
Up to date
# mkdir (for foo/.bar)
["LICENSE","Setup.hs","Shaketest.hs","build.sh","cabal.project","shaketest.cabal"]
# touch (for foo/.bar)
Build completed in 0.01s
```

# build.sh
```
#!/bin/sh
cabal --ghc v2-build shaketest && cabal v2-exec shaketest -- "$@"
```

# cabal
I use cabal to build the shake build script
```
executable shaketest
  hs-source-dirs:      .
  main-is:             Shaketest.hs
  ghc-options:         -Wall -threaded -rtsopts -with-rtsopts=-I0
  build-depends:       base >= 4.7 && < 5
                     , shake
  default-language:    Haskell2010
```

# Shaketest.hs
```
import Control.Monad
import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions $ do
    want ["foo/.bar"]

    "foo/.bar" %> \out -> do
        cmd_ "mkdir -p foo"
        ls <- liftIO $ getDirectoryFilesIO "." ["*"]
        liftIO $ putStrLn $ show ls
        void $ getDirectoryFiles "foo" ["*/.bar"]
        cmd_ "touch foo/.bar"
```

**Comment by ndmitchell** [comment]
Thanks for the detailed report. Have you seen the warning on [`getDirectoryFiles`](https://hackage.haskell.org/package/shake-0.18.3/docs/Development-Shake.html#v:getDirectoryFiles) that says:

> You should normally only call this function returning source files.

It seems like you are calling it on files generated by the build system? That won't work well. I suspect the warning needs to be even stronger and sooner - it's pretty easy to miss at the moment...

**Comment by louispan** [comment]
Sorry about that. I don't know how I missed the documentation on not using getDirectoryFiles for generated files.

What about the untracked getDirectoryFilesIO? Should that also be avoided for generated files? I noticed that getDirectoryFilesIO also can't see the regenerated "foo"

**Comment by louispan** [comment]
I think I know what my mistake is. I thought getDirectoryFiles is shorthand for

do
   ls <- cmd "ls"
   need ls

But getXXX is actually another more fundamental operation that just tracks without "need"ing the file to be created by the build

**Comment by louispan** [comment]
I had wanted to avoid running `npm install` if I can avoid it. I managed to do this with `newCache`
```
want ["node_modules/.done"]

-- run npm_install with the same key each time to avoid redoing work.
npm_install <- newCache $ \_ -> cmd_ "npm install"

"package.json" %> \out -> npm_install "once only"

"nodemodules/*/package.json" %> \out -> npm_install "once only"

"node_modules/.done" %> \out -> do
    need ["package.json"]
    Stdout ls <- cmd "find node_modules -name package.json"
    need $ words ls
    cmd_"touch node_modules/.done"
```

**Comment by ndmitchell** [comment]
You can freely use getDirectoryFilesIO on generated files, it takes a snapshot as of now, and repeatedly reruns if you call it afresh. In your example, doing: `newCache $ \() -> ...` means you can pass `()` to `newCache`, avoiding the possibility of accidentally passing different names.

**Comment by louispan** [comment]
Thank you for the tip about passing `()` to `newCache`, make does make it safer.
