### ISSUE TITLE
trackFile dependency without `need`ing it to be built

### ISSUE THREAD

**Issue by louispan** [ndmitchell/shake#730]
I had wanted to avoid running npm install if I can avoid it. I managed to do this with newCache below.

However, in the `need $ words ls` below, I don't really require a `need` because at that stage I'm not demanding those files to be built (they are already built), but I just want to track those files as a dependency, and rerun the `node_modules/.done` rule if any of them changed.

If there is a `trackFile` primitive, then I will not need to define the `node_modules/*/package.json` rule

```
-- want [build </> "hsMain.js", "npm install" ]
want ["node_modules/.done"]

-- run npm_install with the same key each time to avoid redoing work.
npm_install <- newCache $ \_ -> cmd_ "npm install"

"node_modules/.done" %> \out -> do
    npm_install "once only"
    Stdout ls <- cmd "find node_modules -name package.json"
    need $ words ls -- but really I don't `need` them to built, I want to rerun if these files changed
    copyFile' "package.json" "node_modules/.done"

-- If there is a track dependency, then I won't need this rule
"node_modules/*/package.json" %> \out -> npm_install "once only"
```

**Comment by louispan** [comment]
I managed to emulate `trackFiles` with 
```
trackFiles ls = withTempFile $ \f -> traverse_ (`copyFile'` f) ls
```

But it would be nice to have something that doesn't do extra copying

**Comment by louispan** [comment]
I'm silly.` copyFile'` uses `need`.

**Comment by ndmitchell** [comment]
Indeed it does - there is a normal `copyFile` in the Haskell base package.

Using `need` to assert a file has already been built is very common in Shake. If you really want to demand it doesn't rebuild as a consequence, `needed` can be used, which asserts the file doesn't rebuild.

**Comment by louispan** [comment]
My goal was to not require a `npm_install "once only"` in the implementation of the "node_modules/*/package.json" file pattern rule.

If I deleted that rule, then when I used `need` or `needed`, if I deleted a node module (eg `node_module/y18n`), Shake will detect that `node_module/y18n` is stale and attempt to rebuild it, usually before trying to build `node_module/y18n` (which had the npm install), and error with rule not found for a file path.

If I had a dummy implementation `pure ()` for that file pattern, the Shake detects that nothing was built.

I also experimented with using the example `newtype File = File FilePath` rule in [Development.Shake.Rule](https://hackage.haskell.org/package/shake-0.18.3/docs/Development-Shake-Rule.html)

This still requires definition of the rules for the file patterns, but allows a dummy `pure ()` as the implementation.

```
    fileRule "node_modules/yallist/package.json" $ pure ()
    fileRule "node_modules/yallist/package.json" $ pure ()
```

However, this is less satisfactory, as it required a lot more code than just the original code of `"node_modules/*/package.json" %> \out -> npm_install ()`

Closing this issue, as now that I understand Shake a bit more, I think the original code is sufficient - I just had to understand how Shake works.
