### ISSUE TITLE
actionFinally not running cmd invoked inside handler

### ISSUE THREAD

**Issue by symbiont-arnaud-bailly** [ndmitchell/shake#731]
I have the following code fragment: 
```
withContainer :: String -> (String -> Action a) -> Action a
  cid <= cmd "docker" [ "run" , "--rm", "-d", my_image ]
  ... 
  actionFinally (action containerName) $ do
    cmd_ "docker" [ "rm", "-f", filter (/= '\n') cid ]
```
which supposedly kill containers whether or not the action succeeds. However I noticed containers are still left up and running when the action fails, which is annoying. What am I doing wrong?

**Comment by ndmitchell** [comment]
That looks totally plausible. Can you replicate this bug with print statements instead of cmd? I'm keen to blame one piece or the other.

**Comment by symbiont-arnaud-bailly** [comment]
I did that :
```
   actionFinally (action containerName) $ do
     print $ "cleaning up " <> cid
     -- cmd_ "docker" [ "rm", "-f", filter (/= '\n') cid ]
```
and introduced an error in the build which lead to:

```
"cleaning up 64fc6480062d8b45606a69cf164306445608d5ea158eb241ba0a161038fd917a\n"
Error when running Shake build system:
  at src/Development/Shake/Internal/Args.hs:81:69-79:
```
which seems to confirm the "finally" block is working. Could it be some issue with laziness of `cmd_`?

**Comment by symbiont-arnaud-bailly** [comment]
I think it actually works as expected but as usual, it might fail in some circumstances to catch all failures and all exceptions?

**Comment by ndmitchell** [comment]
It should catch all exceptions, or nearly all - it's a ResourceT style construction. Is there an example where the print doesn't work? Or only where the command doesn't work? If you can reproduce on the small scale I'd be keen to see the code.

**Comment by symbiont-arnaud-bailly** [comment]
Unfortunately no, I wasn't able to reproduce the issue at a small scale. I suspect that there might be some additional level of quirkiness introduced by docker which, perhaps, leads to this odd behaviour?

**Comment by ndmitchell** [comment]
Could well be - I don't know enough about Docker to know how it behaves.
