### ISSUE TITLE
MonadThrow instance

### ISSUE THREAD

**Issue by picca** [ndmitchell/shake#733]
Hello, would it be possible to add a MonadThrow instance to shake ?

thanks for considering

Frederic

**Comment by ndmitchell** [comment]
Unfortunately that requires an additional dependency, and given the role in bootstrapping GHC, that's a bad thing.

**Comment by picca** [comment]
In that case do you know how to use a MonadThrow within shake ?

**Comment by ndmitchell** [comment]
Shake has a `LiftIO` instance for `Action` and `Rules`, so `liftIO $ throwM ...` should be sufficient where you need it.

**Comment by picca** [comment]
In fact I have a method with this signature

parseAbsDir :: MonadThrow m -> FilePath -> m (Path Abs Dir)

but it seems that I cannot use in inside a rules.

**Comment by picca** [comment]
something like this

```
                                    -- (Rule 1) job done
                                    uploaded %> \_ -> do
                                      need [archive, ruche]
                                      _ <- parseRelFile archive
                                      command [] "touch" [uploaded]
```

here the error message

```
src/Thumbnail.hs:174:44-63: error:
    • Could not deduce (MonadThrow
                          shake-0.16.4:Development.Shake.Internal.Core.Types.Action)
        arising from a use of ‘parseRelFile’
      from the context: (MonadIO m, MonadReader Beamline m, MonadThrow m)
        bound by the type signature for:
                   thumbnail' :: forall (m :: * -> *).
                                 (MonadIO m, MonadReader Beamline m, MonadThrow m) =>
                                 ThumbnailInput -> m ()
        at src/Thumbnail.hs:114:1-89
    • In a stmt of a 'do' block: _ <- parseRelFile archive
      In the expression:
```

**Comment by picca** [comment]
sorry, my bad, with liftIO it works.

sometimes, I forget to use my brain...

**Comment by ndmitchell** [comment]
Given you are already using Path, it might be that https://gitlab.com/shake-plus/shake-plus is a good fit for you - and asking for MonadThrow there sounds like an entirely reasonable idea - it seems to fit well with their other enhancements.

**Comment by ndmitchell** [comment]
Request raised at https://gitlab.com/shake-plus/shake-plus/-/issues/1

**Comment by ndmitchell** [comment]
Closing this on the basis that MonadThrow introduces an additional dependency for minor benefit giving liftIO, so not worth the trade-off.
