### ISSUE TITLE
Typo in --help?

### ISSUE THREAD

**Issue by bgamari** [ndmitchell/shake#738]
The `--help` message for `--rebuild` and `--no-rebuild` is quite perplexing:
```
  -B[PATTERN], --rebuild[=PATTERN]
                              Rebuild matching files.
  --no-rebuild[=PATTERN]      Rebuild matching files if necessary (default).
```
What is the distinction that is being drawn here? I would have thought that `--no-rebuild` would *not* rebuild the matching files.

**Comment by ndmitchell** [comment]
`--rebuild` builds the files that match. `--no-rebuild` builds the files that match _if necessary_. And `--skip` is "Don't rebuild matching files this run". These correspond to `RebuildNow`, `RebuildNormal` and `RebuildLater` in this enumeration: https://hackage.haskell.org/package/shake-0.18.4/docs/Development-Shake.html#t:Rebuild. Does that make sense? And if so, what text would you have suggested to make it clear?

**Comment by dwijnand** [comment]
👨‍🎨 maybe something like the following?

```
  -B[PATTERN], --rebuild[=PATTERN]
                              Build matching files, forcing them to rebuild.
  --no-rebuild[=PATTERN]      Build matching files, with no unnecessary rebuilding.
```

**Comment by ndmitchell** [comment]
Seems good to me. @bgamari - would the above have clarified it for you?

**Comment by ndmitchell** [comment]
In fact, I'm not sure "Build matching files" is correct - it doesn't actually build the files that match, it builds whatever it was going to, and if they match the pattern then do what it says. I've updated to:

```
  -B[PATTERN], --rebuild[=PATTERN]
                              If required, these files will rebuild even if nothing has changed.
  --no-rebuild[=PATTERN]      If required, these files will rebuild only if things have changed (default).
```

Let me know if someone thinks of something better, or if it's not clear.
