### ISSUE TITLE
CmdArgument should be instance of IsCmdArgument

### ISSUE THREAD

**Issue by jpcooper** [ndmitchell/shake#739]
What do you think about the following?

```Haskell
instance IsCmdArgument CmdArgument where
  toCmdArgument = id
```

This makes it possible to define a part of a command separately and then incorporate that part into a larger command:

```Haskell

includeDirectories :: CmdArgument
includeDirectories = cmdArguments mempty ["-Ix"] ["-Iy"] ["-Iz"]

compile = cmd_ "clang" "asfdsafd" includeDirectories ["-o", "output"]
```

Or is there an existing alternative to this?

**Comment by ndmitchell** [comment]
Sounds like a very good idea, patch most welcome. But does the `cmdArguments mempty ["-Ix"]` style really work? I'm not sure how the types work out for that...

**Comment by jpcooper** [comment]
Thanks. The style works for what I have used it for. I defined the following function:

```Haskell
buildCmdArguments :: CmdArguments t => t
buildCmdArguments = cmdArguments mempty
```

You can then call it with whatever arguments you need. Is there any way of getting around the requirement for `mempty` at the beginning?

I will make a PR for this issue some time soon.

**Comment by ndmitchell** [comment]
No way I can see. Want to raise a PR for buildCmdArguments? That function is more subtle, so it would be great to include an example in the docs of how to use it.

**Comment by jpcooper** [comment]
Will do.

**Comment by jpcooper** [comment]
@ndmitchell So I've looked into this a bit more, and I've realised that `cmd` is defined in exactly the same way as `buildCmdArguments`, apart from the extra `withFrozenCallStack`. I defined this before I fully understood the types behind `cmd`. I will use `cmd` from now on.

**Comment by ndmitchell** [comment]
Cool - and very non obvious. I suggest we document how to use `cmd` to specify sub commands, since I certainly had no idea!

**Comment by jpcooper** [comment]
You're right. I will make a PR with added docs.
