### ISSUE TITLE
Can Shake not handle UTF-8 files?  

### ISSUE THREAD

**Issue by JonathanReeve** [ndmitchell/shake#756]
I keep getting errors like: 

```
myfile: hGetContents: invalid argument (invalid byte sequence)
```

I'm guessing this is because Shake is trying to read a UTF-8 file as if it were ASCII? I've been trying to get around them by using `Data.Text` instead of `String`, but it seems there's something built into Shake. That is, I can roll my own version of Shake's `readFile'` like this: 

``` haskell
import qualified Data.Text.IO as TIO

readFileText text = need [text] >> liftIO (TIO.readFile text)
```

But I still get the same error. Am I doing something wrong?

**Comment by ndmitchell** [comment]
Text.readFile doesn't read UTF8, but the current system locale - it's a function I recommend avoiding. The normal readFile' uses whatever the locale is too, mirroring the mistake readFile made. 

I'd recommend using readFileUTF8 from the extra library which gets this right. If that fixes it, I should probably add a note to readFile' that it's locale is system dependent.

**Comment by JonathanReeve** [comment]
What's strange then is that I'm using a UTF8 locale. Not an English one, but a utf8 one nonetheless. I think I started getting errors when I had Greek characters in my file.

**Comment by ndmitchell** [comment]
Does `Prelude.readFile` work for you?  I think that should obey the locale. If it doesn't, that would be the place to investigate.

**Comment by JonathanReeve** [comment]
Yep, I'm getting the same error there, as well. Everything was working until I added Greek characters. Yet my locale supports UTF8, so I'm not sure what's up. I'll keep investigating, but you're probably right that this isn't a Shake problem, but something bigger. Thanks for your help. I'll close this issue.
