### ISSUE TITLE
Negative (or exclusion) match in FilePattern?

### ISSUE THREAD

**Issue by saurabhnanda** [ndmitchell/shake#762]
`FilePattern` doesn't allow negation, right? 

https://hackage.haskell.org/package/shake-0.19/docs/Development-Shake.html#v:-63--61--61-

Consequently, what is the best way to express the following: `removeFiles` that match the following pattern/s EXCEPT a few specific files?

Should I use `getDirectoryFiles`, apply the negative filter, and pass the result to `removeFiles`?

**Comment by ndmitchell** [comment]
Something like [listFilesInside from extra](https://hackage.haskell.org/package/extra-1.7.3/docs/System-Directory-Extra.html#v:listFilesInside) can help. But `getDirectoryFiles` works too. Using [getDirectoryFilesIgnore from filepattern](https://hackage.haskell.org/package/filepattern-0.1.2/docs/System-FilePattern-Directory.html#v:getDirectoryFilesIgnore) could work too.

**Comment by saurabhnanda** [comment]
Thanks 👍
