### ISSUE TITLE
pkg-config/formatting: beginner module

### ISSUE THREAD

**Issue by agander** [ndmitchell/shake#766]
After finding this advice about pkg-config:
[using-Shake-to-compile-c](http://haskell.1045720.n5.nabble.com/using-Shake-to-compile-c-td5860321.html)

I am having some trouble with the output from `cmd`

The code:

```
    "_build//*.o" %> \out -> do
        let cpp = dropDirectory1 $ out -<.> "cpp"
        let m = out -<.> "m"
        StdoutTrim includes <- cmd "pkg-config" ["glibmm-2.4", "--cflags"]
        let includes =  filepath_to_str ifp
        cmd_ "g++ -c" [cpp] "-o" [out] "-MMD -MF" [m] [includes]
        needMakefileDependencies m

filepath_to_str :: FilePath -> String
filepath_to_str [] = []
filepath_to_str xs = xs
```

and the output from shake:

```
# pkg-config (for _build/histdedup.o)
# g++ (for _build/histdedup.o)
In file included from histdedup.cpp:2:
histdedup.hpp:14:10: fatal error: glibmm.h: File o directory non esistente
   14 | #include <glibmm.h>
      |          ^~~~~~~~~~
compilation terminated.
Error when running Shake build system:
  at want, called at Shake.hs:11:5 in main:Main
* Depends on: _build/run
  at need, called at Shake.hs:20:9 in main:Main
* Depends on: _build/histdedup.o
  at cmd_, called at Shake.hs:33:9 in main:Main
* Raised the exception:
Development.Shake.cmd, system command failed
Command line: g++ -c histdedup.cpp -o _build/histdedup.o -MMD -MF _build/histdedup.m '-I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include'
Exit code: 1
```

How do I drop the single quotes surrounding the `includes`?

**Comment by ndmitchell** [comment]
If you know you are always precisely dropping the first and last element of the string, then:

```
filepath_to_str x = init (tail x)
```

Will do it. `tail` drops the first element. `init` drops the last (available in `Data.List`).

**Comment by agander** [comment]
Thanks @ndmitchell. 
That works fine but these quotes aren’t part of the string.
Is there a function to represent the output string from `cmd` so that it looses the quotes?

**Comment by ndmitchell** [comment]
Ah, yes, just remove the square brackets from around includes in cmd. That will mean it is treated as a sequence of space separated arguments, and should work properly.

**Comment by agander** [comment]
Thanks again @ndmitchell 

I'm still curious but why are `[cmd]`  and `[m]` not quoted in the final output?

**Comment by agander** [comment]
... referring to these statements:
```
        let cpp = dropDirectory1 $ out -<.> "cpp"
        let m = out -<.> "m"
```

**Comment by ndmitchell** [comment]
Those expressions don't have any spaces or special characters in, so don't need quoting. If they did, they would get quoted. There's also a slight divergence between what gets passed to the execution method (which actually takes a list of arguments) and how we display it to the user (which wants to be roughly compatible with the shell) - in reality there aren't quotes around anything, but they are a single element in the argument array.

**Comment by agander** [comment]
Thank @ndmitchell
