### ISSUE TITLE
can't fully disable file-embedding

### ISSUE THREAD

**Issue by juhp** [ndmitchell/shake#768]
I was trying hard to disable file-embed in shake for dependency reasons, and finally I noticed:
https://github.com/ndmitchell/shake/blob/master/shake.cabal#L237
which seems to prevent me from doing so.

Is it intentional that the shake executable has file-embed always?
Or could it also be conditional on the `file-embed` flag?

**Comment by ndmitchell** [comment]
That should have been:

```
    if flag(embed-files)
        cpp-options: -DFILE_EMBED
```

Like it is in the library. Might need other tweaks, since I imagine we forgot to test this. I'll take a look tonight, unless you want to patch it before.

**Comment by juhp** [comment]
I think that change is sufficient, though I haven't run the build yet.

**Comment by juhp** [comment]
Actually I should have tested more carefully - the file-embed dependency for the executable should also be conditional.
