### ISSUE TITLE
Recursive rules when using AutoDeps on Linux

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#778]
I've been upgrading a system and noticed that `fsatrace` on `ar` reports a read on the output file right after creating it. 

I started looking into this because shake was complaining with `Rules may not be recursive`. Looking at the code, it seems that the `need` performed in the `AutoDeps` case would need to filter out the output file to avoid the recursive rule.

If you need more info or want me to perform any test just ask.

**Comment by ndmitchell** [comment]
Thanks for the report. The issue will be at https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Command.hs#L314-L319. I look at FSARead, but it should really be FSARead minus FSAWrite - since a write and a read is usually just a write for build system purposes. Happy to take a patch doing that, or I'll get round to it in the next few days.

**Comment by ndmitchell** [comment]
I've pushed a fix. Let me know if it works for you.

**Comment by jacereda** [comment]
I had hopes I could work on this one this week, but in any case looks like your fix is faster than the naive `read \\ written` I had in mind. I'll try to test it this week and report the results.

**Comment by jacereda** [comment]
Almost there, I had to use `addFSAOptions "rwm"` and include also `[x | FSAMove x _ <- pxs]` in the `written` set.

Sorry for not PRing, that box is a throwaway docker I don't control and I don't have git setup there.

**Comment by jacereda** [comment]
And at this point it looks quite similar to what `fsalint` is doing, so I guess there's some refactoring opportunity here.

**Comment by ndmitchell** [comment]
Anything else to be done here other than a release?

**Comment by jacereda** [comment]
I'll try to test next week, but I think it's enough. I'll just close it and reopen if I find any problem.
