### ISSUE TITLE
Why should I not call doesFileExist or doesDirectoryExist on files/directores that are created by the buildsystem?

### ISSUE THREAD

**Issue by adamse** [ndmitchell/shake#787]
`doesFileExist` and `doesDirectoryExist` mention this in their [haddocks](https://hackage.haskell.org/package/shake-0.19.2/docs/Development-Shake.html#v:doesFileExist), but I don't understand why.

**Comment by ndmitchell** [comment]
I've expanded the haddocks significantly in 3d33f0ae39fdcfd0dd87ad71f895ce0b3c84241d. Does that explain why?

**Comment by adamse** [comment]
That makes it clearer. Thank you!
