### ISSUE TITLE
race two Action computations

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/shake#793]
I have two ways of implementing a rule with very different performance characteristics. The best way to combine them is to race them and pick the winner. Therefore, I need an `Action` combinator with the same signature and semantics as `Async.race`: 

    race :: Action a -> Action b -> Action (Either a b)

Let me know if this is a reasonable request and I'll be happy to give it a go

**Comment by ndmitchell** [comment]
This kind of thing scares me a lot. Generally any non-determinism in a rule is worrying. Does that mean the dependencies of a rule change non-deterministically based on who wins a race? And that means in future iterations, the dependencies of whoever won will be recorded in the Shake database and checked in advance in future.

Are you doing this to produce a rules value? Or are you doing this as top-level want statements? That would be a bit more plausible, but I'd want some API that prohibited working inside a rule, where it's super dangerous.

**Comment by pepeiborra** [comment]
I'm doing this in a rule implementation. Thanks for the early warning, I can see why you are concerned! Closing this as It doesn't seem such a good idea now that you point out that the set of dependencies will change non-deterministically.
