### ISSUE TITLE
What does historyDisable do?

### ISSUE THREAD

**Issue by omnibs** [ndmitchell/shake#795]
`historyDisable`'s docs say:

> This rule should not be cached or recorded in the history because it makes use of untracked dependencies (e.g. files in a system directory or items on the $PATH), or is trivial to compute locally.

I expected `historyDisable` to act like `alwaysRerun`, nothing would be cached so the rule would always be executed, but a rule like:

```hs
      "asd" %> \out -> do
        historyDisable
        putNormal "hello"
        writeFile' out "hihi"
```

Only prints "hello" once.

Its output file hash seems to get tracked too, since changing or removing the output file and re-running the rule prints `hello` again.

Its inputs seem to get tracked too, since changing it to:

```hs
      "asd" %> \out -> do
        historyDisable
        need ["lala"]
        putNormal "hello"
        writeFile' out "hihi"
```

Makes the rule be re-evaluated when the "lala" file changes.

With this example I couldn't see differences adding or removing `historyDisable`.

Also, what does "recorded in the history" from the docs mean? This function's docs are the only mention of the word "history" in all docs + getting started guide.

**Comment by ndmitchell** [comment]
The concept of history relates to Cloud Shake. I agree, these docs were completely unclear, so I rewrote them in 79a098c55f62de9efd851546435945b7f7f9b9df to say:

> This rule should not be saved to shared/cloud storage via 'shakeShare'.
>  There are usually two reasons to call this function:
>
>   1. It makes use of untracked dependencies that are specific to this machine,
>      e.g. files in a system directory or items on the @$PATH@.
>   2. The rule is trivial to compute locally, so there is no point sharing it.
>
>   If you want the rule to not be cached at all, use 'alwaysRerun'.

Does that answer all your questions?

**Comment by omnibs** [comment]
Ohh, makes total sense now! Thanks for updating the docs!
