### ISSUE TITLE
Variants can't share build directory?

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#819]
I  have been experimenting with `--share` and tried to make Debug and Optimized variants share the same directory, so that there's only a build directory and both variants get built there.

The problem is that after switching from an Optimized to a Debug build, the linker fails for some objects because it can't find some symbols. Looks like it didn't copy the corresponding inputs for the Debug build and just tries to link the Optimized inputs.

So, what does shake use to calculate the hashes? Is there something I can do to make such scenario work?

**Comment by jacereda** [comment]
I have isolated my problem to building a single object in debug and release mode:

`
<clean everything>
<my-build-release-script> -P b/python/Modules/_elementtree.c._elementtree.o -r -V
<my-build-debug-script> bbd -P b/python/Modules/_elementtree.c._elementtree.o -r -V
`

The second shake invocation won't execute anything. That object should be built according to a multiple-outputs rule (`&%>`) that states it generates the .o and the .pdb files. The command line invoked in debug and release modes is obviously different, but somehow isn't triggering a rebuild.

Any hint?

**Comment by jacereda** [comment]
I guess I need `addOracle` or some of its friends to make each rule depend on the command line. I'll just close this for now.

**Comment by ndmitchell** [comment]
There are two broad approaches:

* Put the debug and release builds in different directories - so you'd have `debug/Foo.o` and `release/Foo.o`
* Make the debug/release be part of an `addOracle`.

I usually go for the first, as then switching between release/debug doesn't cause any recompilation.

**Comment by jacereda** [comment]
Neil Mitchell ***@***.***> writes:

> There are two broad approaches:
>
> * Put the debug and release builds in different directories - so you'd have `debug/Foo.o` and `release/Foo.o`
> * Make the debug/release be part of an `addOracle`.
>
> I usually go for the first, as then switching between release/debug
> doesn't cause any recompilation.

I was using the former, but I make the mistake of compiling a version
and running the other so often that I'm considering alternatives :)

Thanks.
