### ISSUE TITLE
Shake as a real-world benchmark for unordered-containers

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/shake#825]
Are there ways to use shake that stress `unordered-containers` code? I.e. commands that are not dominated by file system operations or build actions?

And are there any sample build systems that could be used for benchmarking `unordered-containers`?

**Comment by ndmitchell** [comment]
Probably not - there's enough overhead that while Shake has come up with issues (e.g. when we accidentally hashed everything to the same hash key), it's just not significant enough in general. Shake was an early adopter of unordered-containers, so found plenty of bugs in it, but that was long ago.

**Comment by sjakobi** [comment]
Alright, thanks for the response! :)
